### ISSUE TITLE
the problem of submit jobs

### ISSUE THREAD

**Issue by XU-jialiang** [prisms-center/CASMcode#100]
![subimit](https://user-images.githubusercontent.com/31955412/35316422-705a63bc-010c-11e8-8904-5aeb32249dc6.png)
When I use the casm-calc --submit，it appear the problem as the picture show that.
I have installed the sh, but the problem is not solved.
My computer use the  slurm to submit the job.  maybe this is the reason,but I am not sure and don't know how to solve it.
Thank you!

**Comment by bpuchala** [comment]
It looks like you are using the wrong 'pbs' package.  The one for submitting jobs through CASM is not on PyPI, it is here:  https://github.com/prisms-center/pbs.  The latest fixes are in branch 2.X.

**Comment by XU-jialiang** [comment]
My computer use the slurm to submit the job，but CASM use the pbs. I know that changing the submitting code from pbs to slurm is necessary. But I don't know the place of the submit code. Can you help me change it ?
Thank you!

**Comment by XU-jialiang** [comment]
Preparing to submit a VASP relaxation PBS job
Counting atoms in the POSCAR
Constructing a PBS job
Submitting
sbatch: error: invalid partition specified: fluxoe
sbatch: error: Batch job submission failed: Invalid partition name specified
cannot concatenate 'str' and 'NoneType' objects

**Comment by bpuchala** [comment]
By default a config file is saved at ```$HOME/.pbs/config.json``` containing a ```"software"``` property that can be set to ```"slurm"``` or ```"pbs"```.  It tries to auto detect ```qsub``` or ```sbatch``` to set this automatically if the config file doesn't exist, but some systems have both available in which case it defaults to ```"pbs"```.  If you want to use a directory other than ```$HOME/.pbs``` you can set the environment variable ```PBS_JOBS_DB``` and the directory ```$PBS_JOBS_DB/.pbs``` will be used for storing the database and config file.

Relevant code is here: https://github.com/prisms-center/pbs/blob/2.X/pbs/jobdb.py in the ```"connect"``` function.

**Comment by DS-Wen** [comment]
Hi, I am also encountering a problem with job submission. The 'casm-calc --submit' gave me something like this: I don't know why it didn't submit the job. 

Construct a casm.vaspwrapper.Relax instance:
  Input directory: /home/wen94/test/Ni3_Al_Nb_SC/training_data/SCEL1_1_1_1_0_0_0/0
  Configuration: SCEL1_1_1_1_0_0_0/0
  Reading CASM settings
  Calculations directory: /home/wen94/test/Ni3_Al_Nb_SC/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default
  Reading relax.json settings file
  Read settings from: /home/wen94/test/Ni3_Al_Nb_SC/training_data/settings/calctype.default/relax.json
  DONE

Submitting...
Configuration: SCEL1_1_1_1_0_0_0/0
Calculation directory: /home/wen94/test/Ni3_Al_Nb_SC/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default
JobID: [u'5668259']
JobID: 5668259   Jobstatus: ?   Not submitting.
Construct a casm.vaspwrapper.Relax instance:
  Input directory: /home/wen94/test/Ni3_Al_Nb_SC/training_data/SCEL1_1_1_1_0_0_0/1
  Configuration: SCEL1_1_1_1_0_0_0/1
  Reading CASM settings
  Calculations directory: /home/wen94/test/Ni3_Al_Nb_SC/training_data/SCEL1_1_1_1_0_0_0/1/calctype.default
  Reading relax.json settings file
  Read settings from: /home/wen94/test/Ni3_Al_Nb_SC/training_data/settings/calctype.default/relax.json
  DONE

And after the above message, there was something else showing up: 

*** glibc detected *** /apps/rhel6/Python-2.7.2/bin/python: double free or corruption (!prev): 0x0000000001779dd0 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3efa875dee]
/lib64/libc.so.6[0x3efa878c80]
/lib64/libc.so.6(exit+0xe2)[0x3efa835992]
/lib64/libc.so.6(__libc_start_main+0x104)[0x3efa81ed24]
/apps/rhel6/Python-2.7.2/bin/python[0x400649]
======= Memory map: ========
00400000-00401000 r-xp 00000000 00:17 48461572                           /apps/rhel6/Python-2.7.2/bin/python
00600000-00601000 rw-p 00000000 00:17 48461572                           /apps/rhel6/Python-2.7.2/bin/python
0154d000-02c19000 rw-p 00000000 00:00 0                                  [heap]
3efa000000-3efa020000 r-xp 00000000 00:11 388385                         /lib64/ld-2.12.so
3efa220000-3efa221000 r--p 00020000 00:11 388385                         /lib64/ld-2.12.so
3efa221000-3efa222000 rw-p 00021000 00:11 388385                         /lib64/ld-2.12.so
3efa222000-3efa223000 rw-p 00000000 00:00 0 
3efa400000-3efa415000 r-xp 00000000 00:11 388439                         /lib64/libz.so.1.2.3
3efa415000-3efa614000 ---p 00015000 00:11 388439                         /lib64/libz.so.1.2.3
3efa614000-3efa615000 r--p 00014000 00:11 388439                         /lib64/libz.so.1.2.3
3efa615000-3efa616000 rw-p 00015000 00:11 388439                         /lib64/libz.so.1.2.3
3efa800000-3efa98a000 r-xp 00000000 00:11 388391                         /lib64/libc-2.12.so
3efa98a000-3efab8a000 ---p 0018a000 00:11 388391                         /lib64/libc-2.12.so
3efab8a000-3efab8e000 r--p 0018a000 00:11 388391                         /lib64/libc-2.12.so
3efab8e000-3efab90000 rw-p 0018e000 00:11 388391                         /lib64/libc-2.12.so
3efab90000-3efab94000 rw-p 00000000 00:00 0 
3efac00000-3efac83000 r-xp 00000000 00:11 388401                         /lib64/libm-2.12.so
3efac83000-3efae82000 ---p 00083000 00:11 388401                         /lib64/libm-2.12.so
3efae82000-3efae83000 r--p 00082000 00:11 388401                         /lib64/libm-2.12.so
3efae83000-3efae84000 rw-p 00083000 00:11 388401                         /lib64/libm-2.12.so
3efb000000-3efb002000 r-xp 00000000 00:11 388415                         /lib64/libdl-2.12.so
3efb002000-3efb202000 ---p 00002000 00:11 388415                         /lib64/libdl-2.12.so
3efb202000-3efb203000 r--p 00002000 00:11 388415                         /lib64/libdl-2.12.so
3efb203000-3efb204000 rw-p 00003000 00:11 388415                         /lib64/libdl-2.12.so
3efb400000-3efb417000 r-xp 00000000 00:11 388395                         /lib64/libpthread-2.12.so
3efb417000-3efb617000 ---p 00017000 00:11 388395                         /lib64/libpthread-2.12.so
3efb617000-3efb618000 r--p 00017000 00:11 388395                         /lib64/libpthread-2.12.so
3efb618000-3efb619000 rw-p 00018000 00:11 388395                         /lib64/libpthread-2.12.so
3efb619000-3efb61d000 rw-p 00000000 00:00 0 
3efb800000-3efb807000 r-xp 00000000 00:11 388397                         /lib64/librt-2.12.so
3efb807000-3efba06000 ---p 00007000 00:11 388397                         /lib64/librt-2.12.so
3efba06000-3efba07000 r--p 00006000 00:11 388397                         /lib64/librt-2.12.so
3efba07000-3efba08000 rw-p 00007000 00:11 388397                         /lib64/librt-2.12.so
3efbc00000-3efbc8b000 r-xp 00000000 00:11 389037                         /usr/lib64/libsqlite3.so.0.8.6
3efbc8b000-3efbe8b000 ---p 0008b000 00:11 389037                         /usr/lib64/libsqlite3.so.0.8.6
3efbe8b000-3efbe8e000 rw-p 0008b000 00:11 389037                         /usr/lib64/libsqlite3.so.0.8.6
3efbe8e000-3efbe8f000 rw-p 00000000 00:00 0 
3efc000000-3efc01d000 r-xp 00000000 00:11 388457                         /lib64/libselinux.so.1
3efc01d000-3efc21c000 ---p 0001d000 00:11 388457                         /lib64/libselinux.so.1
3efc21c000-3efc21d000 r--p 0001c000 00:11 388457                         /lib64/libselinux.so.1
3efc21d000-3efc21e000 rw-p 0001d000 00:11 388457                         /lib64/libselinux.so.1
3efc21e000-3efc21f000 rw-p 00000000 00:00 0 
3efc800000-3efc816000 r-xp 00000000 00:11 388427                         /lib64/libresolv-2.12.so
3efc816000-3efca16000 ---p 00016000 00:11 388427                         /lib64/libresolv-2.12.so
3efca16000-3efca17000 r--p 00016000 00:11 388427                         /lib64/libresolv-2.12.so
3efca17000-3efca18000 rw-p 00017000 00:11 388427                         /lib64/libresolv-2.12.so
3efca18000-3efca1a000 rw-p 00000000 00:00 0 
3efd000000-3efd1ba000 r-xp 00000000 00:11 388469                         /usr/lib64/libcrypto.so.1.0.1e
3efd1ba000-3efd3ba000 ---p 001ba000 00:11 388469                         /usr/lib64/libcrypto.so.1.0.1e
3efd3ba000-3efd3d5000 r--p 001ba000 00:11 388469                         /usr/lib64/libcrypto.so.1.0.1e
3efd3d5000-3efd3e1000 rw-p 001d5000 00:11 388469                         /usr/lib64/libcrypto.so.1.0.1e
3efd3e1000-3efd3e5000 rw-p 00000000 00:00 0 
3efd400000-3efd403000 r-xp 00000000 00:11 388463                         /lib64/libcom_err.so.2.1
3efd403000-3efd602000 ---p 00003000 00:11 388463                         /lib64/libcom_err.so.2.1
3efd602000-3efd603000 r--p 00002000 00:11 388463                         /lib64/libcom_err.so.2.1
3efd603000-3efd604000 rw-p 00003000 00:11 388463                         /lib64/libcom_err.so.2.1
3efe400000-3efe40a000 r-xp 00000000 00:11 388459                         /lib64/libkrb5support.so.0.1
3efe40a000-3efe609000 ---p 0000a000 00:11 388459                         /lib64/libkrb5support.so.0.1
3efe609000-3efe60a000 r--p 00009000 00:11 388459                         /lib64/libkrb5support.so.0.1
3efe60a000-3efe60b000 rw-p 0000a000 00:11 388459                         /lib64/libkrb5support.so.0.1
3efe800000-3efe8dc000 r-xp 00000000 00:11 388465                         /lib64/libkrb5.so.3.3
3efe8dc000-3efeadb000 ---p 000dc000 00:11 388465                         /lib64/libkrb5.so.3.3
3efeadb000-3efeae5000 r--p 000db000 00:11 388465                         /lib64/libkrb5.so.3.3
3efeae5000-3efeae7000 rw-p 000e5000 00:11 388465                         /lib64/libkrb5.so.3.3
3efec00000-3efec02000 r-xp 00000000 00:11 388455                         /lib64/libkeyutils.so.1.3Aborted

If you don't mind, please help me interpret these messages. Thank you!

**Comment by bpuchala** [comment]
@DS-Wen can you open a new issue? I'm afraid I'm not sure what that problem is. Perhaps if you include more information on the version, os, etc. someone will have an idea.

**Comment by XU-jialiang** [comment]
I can't submit all jobs in one time. I just submit the first one which has the primitive cell structure.
And just one job has been done. I'm sorry that I can't afford the picture successfully. So the results are as follow. Thank you very much.

casm) [umjzhh-3@mu07 Mg-test]$ casm-calc --submit
-- Construct: CASM Project --
from: "/lustre/home/acct-umjzhh/umjzhh-3/xjl/Mg-test"

-- Load project data --
read: "/lustre/home/acct-umjzhh/umjzhh-3/xjl/Mg-test/.casm/composition_axes.json"
read: "/lustre/home/acct-umjzhh/umjzhh-3/xjl/Mg-test/training_data/SCEL"
read: "/lustre/home/acct-umjzhh/umjzhh-3/xjl/Mg-test/.casm/config_list.json"

Construct a casm.vaspwrapper.Relax instance:
  Input directory: /lustre/home/acct-umjzhh/umjzhh-3/xjl/Mg-test/training_data/SCEL2_1_1_2_0_0_0/0
  Configuration: SCEL2_1_1_2_0_0_0/0
  Reading CASM settings
  Calculations directory: /lustre/home/acct-umjzhh/umjzhh-3/xjl/Mg-test/training_data/SCEL2_1_1_2_0_0_0/0/calctype.default
  Reading relax.json settings file
  Read settings from: /lustre/home/acct-umjzhh/umjzhh-3/xjl/Mg-test/training_data/settings/calctype.default/relax.json
  DONE

Submitting...
Configuration: SCEL2_1_1_2_0_0_0/0
Calculation directory: /lustre/home/acct-umjzhh/umjzhh-3/xjl/Mg-test/training_data/SCEL2_1_1_2_0_0_0/0/calctype.default
JobID: []
Constructing a VASP Relax object
  Relax directory: /lustre/home/acct-umjzhh/umjzhh-3/xjl/Mg-test/training_data/SCEL2_1_1_2_0_0_0/0/calctype.default
VASP Relax object constructed

Preparing to submit a VASP relaxation PBS job
Counting atoms in the POSCAR
Constructing a PBS job
Submitting
sbatch: error: invalid partition specified: fluxoe
sbatch: error: Batch job submission failed: Invalid partition name specified
cannot concatenate 'str' and 'NoneType' objects


![Uploading 2.jpg…]()

4) Calculate configuration properties
- Current calctype: default
- Current cluster expansion: formation_energy
- Number of configurations calculated: 1 / 13 generated (Update with 'casm update')

For the number of configurations generated, calculated,
 and selected by supercell, run 'casm status -d'

**Comment by jcthomas** [comment]
Is `fluxoe` a valid queue designation on the cluster where you are submitting jobs? All cluster-specific job-submission parameters should be defined within the file at `$ROOT/training_data/settings/$CURR_CALCTYPE/relax.json`. 

The queue/partition setting is specified by the `"queue"` key-value pair.

**Comment by XU-jialiang** [comment]
I'm sorry to bother you again.
"queue": queue to submit job in
I don't understand the meaning of the "queue"
in the example ,"queue": flux
I don't how to set this parameter.
In my system, I use  "squeue" to check the information of jobs(JOBID,NAME,TIME,TIME_LIMI and so on.)

**Comment by jcthomas** [comment]
If using Slurm, `"queue"` should be set to the name of the partition you want to run your jobs on. In other words, it should be the value `$PARTITION` that you would pass to `sbatch` viat the `-p` flag: `sbatch -p $PARTITION [additional arguments]`

**Comment by XU-jialiang** [comment]
thank you~
