### ISSUE TITLE
Converting weather API data from 2 decimal places to no decimal places?

### ISSUE THREAD

**Issue by richierockskool** [prisms-center/CASMcode#104]
if let mainDictionary = jsonObj!.value(forKey: "main") as? NSDictionary {
                            if let temperature = mainDictionary.value(forKey: "temp"){
                                
                               
                                let formatter = NumberFormatter()
                                formatter.numberStyle = .decimal
                                formatter.maximumFractionDigits = 0
                                _ = formatter.string(from: (temperature) as! NSNumber)!
                              
                                
                                DispatchQueue.main.async {
                                    
                                    self.weatherLabel.text = "Temperature: \(temperature)°C"
                                    
                                    
                                }
                            }

// no errors, but not doing the conversion...

**Comment by richierockskool** [comment]
func fixTempForDisplay(temp: Double) -> String {
                                    let temperature = round(temp)
                                    let temperatureString = String(format: "%.0f", temperature)
                                    return temperatureString
                                }
                                
                    
                                
                                DispatchQueue.main.async {
                                    
                                
                                    
                                    self.weatherLabel.text = "Temperature: \(fixTempForDisplay(temp: temperature as! Double))°C"
                                    
                                    
                                }
                            }

**Comment by richierockskool** [comment]
Fixed!!

**Comment by bpuchala** [comment]
Wrong project.
