### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ghost** [prisms-center/CASMcode#105]
Hello. My name is Kyungyeol Gu. Korean guy.

hi i'm linux beginner.

i have 1 question. 
when compile the CASM using scons.
i type the "scons install" in CASM directory.
but. i faced this error.

==================================================
File "/home/kyungyeol/work_dir/CASMcode-master/SConstruct", line 492
 print "rm", path 
SyntaxError : invalid syntax
==================================================

my environment is Ubuntu 17 version.
and i already compile g++, boost, python 2.7, scons

am i need other code?
i don't know. what is the problem. plz help me  thank you

**Comment by skk74** [comment]
It may be the case that your environment variables aren't set up correctly.
See that these steps in INSTALL.md were performed
The script casmenv.sh provides a list of environment variables that you are recogized by CASM during installation and use. A copy of this file can be used to configure your environment before installing or using CASM. For instance:

mkdir $HOME/modules
cp /home/kyungyeol/work_dir/CASMcode-master/casmenv.sh $HOME/modules/casm
... edit $HOME/modules/casm ...

Then to set your environment before installing or using CASM:

source $HOME/modules/casm

Alternatively : Attempt to install with autotools with the following commands in  /home/kyungyeol/work_dir/CASMcode-master/
mkdir build 
./bootstrap.sh
cd build
../configure
make 
make install

**Comment by ghost** [comment]
this CASM version support python2? or python3?
i ask same problem to other groups. they said "because u use python3"
so i'm very confused.

and then,when is type "./bootstrap.sh" 

==================================================
Updating version string in buid-aux/casm_version.txt
fatal: bad revision 'HEAD'
./bootstrap.sh : line 13 : autoreconf: can not found command
-> i solve this one by "sudo apt-get install autoconf" is it right?

**Comment by ghost** [comment]
i edit pring syntax in the INSTALL.md file 
i got this result
#####
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Install directory: "include/casm" as "/usr/local/include/casm"
g++ -o src/casm/external/gzstream/gzstream.os -c -DNDEBUG -O3 --std=c++11 -Wno-deprecated-register -Wno-deprecated-declarations -DEIGEN_DEFAULT_DENSE_INDEX_TYPE=long -Wno-unused-parameter -DNDEBUG -O3 -DGZSTREAM_NAMESPACE=gz -fPIC -Iinclude/casm/external/gzstream src/casm/external/gzstream/gzstream.C
sh: 1: g++: not found
scons: *** [src/casm/external/gzstream/gzstream.os] Error 127
scons: building terminated because of errors.
