### ISSUE TITLE
Running tests when installing with Make

### ISSUE THREAD

**Issue by ajjackson** [prisms-center/CASMcode#108]
I have attempted to build CASM using Make in a Docker container, based on guidance in #96 and #99 .
Here is the [Dockerfile](https://github.com/prisms-center/CASMcode/files/2005898/Dockerfile.txt) which appears to run `make test` successfully.

As far as I can tell `make test` only _builds_ the tests and does not run them. If I attempt to run the binary test files, this results in errors related to non-existent paths such as
```
root@c61f24c6e121:~/CASMcode# ./tests/unit/clex/run_test_clex
rm: cannot remove '/root/CASMcode/tests/unit/test_projects/*': No such file or directory
./tests/unit/clex/run_test_clex: line 6: /root/CASMcode/casm_unit_clex: No such file or directory
```

Is this unexpected behaviour, or are the tests currently configured for Scons only? Is there some syntax for calling them correctly?

I am also finding in that Docker that it is necessary to set `LD_LIBRARY_PATH=/usr/local/lib` in order to run the _casm_ command.

**Comment by bpuchala** [comment]
With autotools, use ``make check`` to build and run the tests.

**Comment by ajjackson** [comment]
That seems to work once LD_LIBRARY_PATH is set! Here is the [working version](https://github.com/ajjackson/casm-configs/blob/e5d656371a9f631a6b50b76cba2520183ca48e04/dockerfiles/make_build_and_test).

**Comment by bpuchala** [comment]
Great! Thanks, that will be useful for others too.
