### ISSUE TITLE
Error compiling clexulator.

### ISSUE THREAD

**Issue by XU-jialiang** [prisms-center/CASMcode#110]
Dear sir,
 When I use the 'casm best -u'  It appears this problem and I use the  'casm settings -l' ,there is nothing wrong. 

Looking for your reply,thank you very much.

**Error compiling clexulator. To fix:**
  - Check compiler error messages.
  - Check compiler options with 'casm settings -l'
    - Update compiler options with 'casm settings --set-compile-options '...options...'
    - Make sure the casm headers can be found by including '-I/path/to/casm'
  - The default compiler is 'g++'. Override by setting the environment variable CXX

terminate called after throwing an instance of 'std::exception'
  what():  std::exception
Aborted

**casm settings -l**
-- Cluster expansions --
formation_energy*:
      property: formation_energy
      calctype: default
           ref: default
          bset: default
           eci: test
-- Basis sets --
default*
-- Training Data & References --
default / default*
-- ECI for current cluster expansion settings group --
default
test*

*: indicates the default settings used by CASM whenever particular
settings are not explicitly specified (i.e. the basis set to evaluate
for 'casm query -k corr')

-- Compiler settings --
cxx: 'g++' (CXX)
cxxflags: '-O3 -Wall -fPIC --std=c++11' (default)
soflags: '-shared -lboost_system' (default)
casm_includedir: '/lustre/home/acct-umjzhh/umjzhh-3/xjl/envs/casm/include' (CASM_PREFIX)
casm_libdir: '/lustre/home/acct-umjzhh/umjzhh-3/xjl/envs/casm/lib' (CASM_PREFIX)
boost_includedir: '/lustre/usr/boost/1.54-gcc48/include' (CASM_BOOST_PREFIX)
boost_libdir: '/lustre/usr/boost/1.54-gcc48/lib' (CASM_BOOST_PREFIX)

compile command: 'g++ -O3 -Wall -fPIC --std=c++11 -I/lustre/home/acct-umjzhh/umjzhh-3/xjl/envs/casm/include -I/lustre/usr/boost/1.54-gcc48/include'

so command: 'g++ -shared -lboost_system -L/lustre/usr/boost/1.54-gcc48/lib -L/lustre/home/acct-umjzhh/umjzhh-3/xjl/envs/casm/lib'

-- 'casm view' --
command: 'casm.view VESTA'

**Comment by bpuchala** [comment]
I can't tell from this what the problem is.  One way to determine the issue is to try to compile the basis functions file (```basis_sets/bset.default/<YourProjectName>_Clexulator.cc```) manually.  The ```casm bset -u``` command attempts to do the following:

First, CASM will attempt to compile "compile command" shown:

```
g++ -O3 -Wall -fPIC --std=c++11 -I/lustre/home/acct-umjzhh/umjzhh-3/xjl/envs/casm/include -I/lustre/usr/boost/1.54-gcc48/include -o basis_sets/bset.default/<YourProjectName>_Clexulator.o -c basis_sets/bset.default/<YourProjectName>_Clexulator.cc
```

Then it will generate the shared library using the "so command":
```
g++ -shared -lboost_system -L/lustre/usr/boost/1.54-gcc48/lib -L/lustre/home/acct-umjzhh/umjzhh-3/xjl/envs/casm/lib -o basis_sets/bset.default/<YourProjectName>_Clexulator.so basis_sets/bset.default/<YourProjectName>_Clexulator.o
```

So doing these manually may help you determine the issue.

**Comment by XU-jialiang** [comment]
Normally I can get 5 new files after using the order "casm best -u"

basis.json  clust.json  MgAl_Clexulator.cc  MgAl_Clexulator.o  
MgAl_Clexulator.so

But I just have  3 files ,laking MgAl_Clexulator.o,  MgAl_Clexulator.so
Maybe this is the issue.

**Comment by bpuchala** [comment]
Does it print the MgAl_Clexulator.cc file?  Maybe there a problem with your bspecs.json file that CASM is not properly warning about?

**Comment by jcthomas** [comment]
The fact that MgAl_Clexulator.o, MgAl_Clexulator.so are missing means that
the clexulator is not compiling correctly.  Could you please send the files
bspecs.json and MgAl_Clexulator.cc (if it is being generated) to help
diagnose the problem?

**Comment by XU-jialiang** [comment]
This is the file for the Mg_Sn,the sam situation.I also try the demo again, it appears the same problem.
thank you very much again.
[Mg_Sn.zip](https://github.com/prisms-center/CASMcode/files/2131577/Mg_Sn.zip)

**Comment by XU-jialiang** [comment]
I have solved this problem. I load the icc and gcc in the same time. So the compiling progress is wrong.
Sorry to bother you～
Thank you very much!
