### ISSUE TITLE
libcasm.dylib: cannot open shared object file

### ISSUE THREAD

**Issue by lukejpan** [prisms-center/CASMcode#111]
Hi,

I compiled a version of CASM 0.2.X in a supercomputer with a CentOS 7 operating system. The compiled version works well for commands like "casm init" (it returns the message as it writes in the README file). But when I started to submit vasp jobs, it started to crash. For example, when I type "casm-calc --submit" and "casm-calc --setup", it kicks me back with the error message saying "$PATH-TO-CASM/CASMcode-0.2.X/lib/libcasm.dylib: cannot open shared object file: No such file or directory". I checked the files under ./CASMcode-0.2.X/lib, but only "libcasm.so" and "libccasm.so" are under that directory. 

Any suggestions?

**Comment by bpuchala** [comment]
This is a Python error?  When the Python package attempts to load the CASM shared libraries it should attempt the following (from https://github.com/prisms-center/CASMcode/blob/0.2.X/python/casm/casm/casm.py):

```
Order of priority for libcasm.*:
        1) $LIBCASM
        2) $CASM_PREFIX/lib/libcasm.*
        3) /usr/local/lib/libcasm.*

      Order of priority for libccasm.*:
        1) $LIBCCASM
        2) $CASM_PREFIX/lib/libccasm.*
        3) /usr/local/lib/libccasm.*
```
'libcasm.dylib' is not hard-coded anywhere, so I think it must be on your system in one of those locations. If it really isn't on your system, I'm not sure why this is happening, but you should be able to set the environment variables ```LIBCASM=$PATH-TO-CASM/CASMcode-0.2.X/lib/libcasm.so``` and ```LIBCCASM=$PATH-TO-CASM/CASMcode-0.2.X/lib/libccasm.so```.

**Comment by lukejpan** [comment]
Thanks for your quick response. I reset the environment variables and it circumvented the old error. But when I run the example ZrO projects (like "case-calc --setup"), the reading of relax.json file failed with the following error:

-- Construct: CASM Project -- 
from: "$PATH/CASM-trial/tutorial-ZrO"

-- Load project data -- 
read: "$PATH/CASM-trial/tutorial-ZrO/.casm/composition_axes.json"
read: "$PATH/CASM-trial/tutorial-ZrO/training_data/SCEL"
read: "$PATH/CASM-trial/tutorial-ZrO/.casm/config_list.json"

  Reading relax.json settings file
Using $PATH/CASM-trial/tutorial-ZrO/training_data/settings/calctype.default/relax.json as settings...
Error reading settings file: $PATH/CASM-trial/tutorial-ZrO/training_data/settings/calctype.default/relax.json
Expecting property name: line 11 column 1 (char 194)
*** Error in `python': double free or corruption (fasttop): 0x0000561bb6f4d290 ***

**Comment by bpuchala** [comment]
That is usually a "can't read invalid JSON" type of error.  Is the file format OK?

**Comment by lukejpan** [comment]
Yes, I think so. Since it is just a trial, I did not touch or change anything in the relax.json file. So it is what it is coming with the package.

**Comment by bpuchala** [comment]
Are you using the relax.json file from one of the CASMcode_demo examples?
Can you include it here?

**Comment by lukejpan** [comment]
Thanks for your message. Yes, I am using the ZrO files in the CASMcode_v0.2.1_demo folder. 

The following is the content in relax.json file:
*********
{
  "account":"prismsproject_fluxoe",
  "qos":"flux",
  "queue":"fluxoe",
  "priority":"-200",
  "walltime":"48:00:00",
  "pmem":"3800mb",
  "ppn":"16",
  "atom_per_proc":"2",
  "run_limit":10,
}
*******

**Comment by bpuchala** [comment]
There is an extra comma at the end.
https://jsoneditoronline.org/ is a useful site for finding JSON formatting
errors.

**Comment by lukejpan** [comment]
Thanks for your advice. The old error disapears. However, it still kicks me back with the error when I execute "casm-calc --setup" (this error is at the bottom of the old error):

*** Error in `python': double free or corruption (fasttop): 0x00005609552b3290 ***

**Comment by bpuchala** [comment]
I'm afraid I'm not sure what is causing that problem. Maybe an old Python dependency? You could attempt updating your Python packages and see if that resolves the issue.

As an alternative, we've been working to get a CASM conda package release ready.  If you install miniconda in your local user space you could then use conda to install a 0.3.X development version (based on this branch https://github.com/bpuchala/CASMcode/commits/0.3.X).

To install miniconda in your user space (on Linux):
```
CASM_CONDA_DIR=$HOME/.local/conda \
  && CASM_PYTHON_VERSION=3 \
  && curl -sSL https://repo.continuum.io/miniconda/Miniconda${CASM_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
  && mkdir -p $CASM_CONDA_DIR \
  && bash /tmp/miniconda.sh -bfp $CASM_CONDA_DIR \
  && PATH="$CASM_CONDA_DIR/bin:$PATH" \
  && rm -rf /tmp/miniconda.sh \
  && conda install -y  "python =$CASM_PYTHON_VERSION" \
  && conda update --all \
  && conda clean --all --yes
```

CASM needs to make use of a c++ compiler to compile the generated code that evaluates correlations. To use the system compiler (on Linux) install this:
```
conda create -n casm_0.3.dev132 --override-channels -c bpuchala/label/dev -c prisms-center -c defaults -c conda-forge "python =3" "casm 0.3.dev132+g5e2a68 devtoolset_0"
```

If that doesn't work, to use a compiler downloaded from conda, install this:
```
conda create -n casm_0.3.dev132 --override-channels -c bpuchala/label/dev -c prisms-center -c defaults -c conda-forge "python =3" "casm 0.3.dev132+g5e2a68 condagcc_0"
```

**Comment by lukejpan** [comment]
Thanks for your suggestions. I actually temporarily solved this problem by 
***
export MALLOC_CHECK_=0
***
It seems like a temporary solution. I guess, in the code, there is double free of memory. (It might be some unnecessary freeing of memory.) Thank you.

**Comment by lukejpan** [comment]
Does the code generate any PBS files that I can look into? I run a calculation and kicked me back wth the PBSError. It seems that it can only do iteratively but not submitted to the queue. 

When I executed "case-calc --run":
****
-- Construct: CASM Project -- 
from: "/$PATH"

-- Load project data -- 
read: "$PATH/.casm/composition_axes.json"
read: "$PATH/training_data/SCEL"
read: "$PATH/.casm/config_list.json"

  Reading relax.json settings file
Using $PATH/training_data/settings/calctype.default/relax.json as settings...
Relevant calculator is: vasp
Construct a casm.vaspwrapper.Relax instance:
  Input directory:$PATH/training_data/SCEL1_1_1_1_0_0_0/0
  Configuration: SCEL1_1_1_1_0_0_0/0
  Reading CASM settings
  Calculations directory: $PATH/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default
  Reading relax.json settings file
  Read settings from: $PATH/training_data/settings/calctype.default/relax.json
  DONE

Constructing a VASP Relax object
  Relax directory: $PATH/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default
VASP Relax object constructed

Status: complete
**PBSError**
****

**Comment by bpuchala** [comment]
The ```casm-calc --run``` option generates VASP input files and runs jobs immediately (interactively). The ```--setup``` option generates the VASP input files, and the ```--submit``` option generates the VASP input files and submits jobs.  The ```pbs``` Python package creates a database of submitted jobs that you can query using the ```pstat``` program.  See the ```pstat -h``` output for help.  The ```pstat -f``` option prints full details, including the PBS submit script.
