### ISSUE TITLE
invalid literal for int() with base 10: 'Version: 6' Segmentation fault

### ISSUE THREAD

**Issue by lukejpan** [prisms-center/CASMcode#112]
I recently installed PBS and prisms-jobs package and went back to run "casm-calc --run", but with the error message:
++  status: incomplete   next task: relax
Continue VASP job:
  Original: $PATH/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default/run.0
  Continuation: $PATH/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default/run.1
 backup:

  cp CONTCAR -> POSCAR
  mv: POTCAR 
  cp: INCAR KPOINTS 
  rm: 
 gzip: 

Begin vasp run:
  jobdir: $PATH/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default/run.1
  exec: vasp
Run complete
Most recent file output (std.out): 2.85036611557  seconds ago.

++  status: incomplete   next task: constant
Continue VASP job:
  Original: $PATH/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default/run.1
  Continuation: $PATH/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default/run.2
 backup:

  cp CONTCAR -> POSCAR
  mv: POTCAR 
  cp: INCAR KPOINTS 
  rm: 
 gzip: 

  Set INCAR tags: {'IBRION': -1, 'ISIF': 2, 'NSW': 0, 'SYSTEM': 'final', 'ISMEAR': -5} 

Begin vasp run:
  jobdir: $PATH/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default/run.2
  exec: vasp
Run complete
Most recent file output (std.out): 2.97657299042  seconds ago.

++  status: complete   next task: None
mv run.2 run.final
Complete VASP job: $PATH/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default/run.final
  rm: 
 gzip: 

**invalid literal for int() with base 10: 'Version: 6'
Segmentation fault**

**Comment by bpuchala** [comment]
On your system, what is the output for ```qstat --version```?

**Comment by lukejpan** [comment]
$  qstat --version
Version: 6.1.1.1
Commit: 22f28343b8ee83b1234479b20224353f6c2db317

**Comment by lukejpan** [comment]
Shall we modify the line in misc_torque.py  
***
def _qstat(jobid=None, username=getlogin(), full=False, version=int(getversion().split(".")[0])):
***

and 

the line in misc_slurm.py
****
def _squeue(jobid=None, username=getlogin(), full=False, version=int(getversion().split(".")[0]), sformat=None):

***
?

**Comment by bpuchala** [comment]
Which versions of CASM & 'pbs' or CASM and 'prisms_jobs' are you using?

**Comment by bpuchala** [comment]
It looks like getversion() in pbs/misc.py needs a fix:

```
# return the version number
return sout.read().rstrip("\n").lstrip("version: ")
```
->
```
# return the version number
return sout.read().rstrip("\n").lower().lstrip("version: ")
```

and similarly for slurm.  This has been done in 'prisms_jobs', which is the package that will be used in CASM v0.3 going forward.

**Comment by bpuchala** [comment]
Actually, I see this is fixed on the 2.X branch, so you can checkout and install that. I'm going to set 2.X as the primary branch, and delete the master and 3.X branches so they aren't so confusing.
