### ISSUE TITLE
unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by 91bsjun** [prisms-center/CASMcode#119]
Dear developers,

I faced an error when run 'casm calc --run'.

Anything I can fix this?
I think the problem caused from parsing run.x , run.final directories..

I installed CASM v0.3 using conda at CentOS<code>$ conda create -n casm --override-channels -c bpuchala/label/dev -c prisms-center -c defaults -c conda-forge casm </code>)

<pre>
(casm) [bsjun@aaaaaaa]$ casm calc --run
-- Construct: CASM Project -- 
from: "/home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2"

-- Load project data -- 
read: "/home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/.casm/composition_axes.json"
read: "/home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/training_data/SCEL"
read: "/home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/.casm/config_list.json"

  Reading relax.json settings file
Using /home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/training_data/settings/calctype.default/relax.json as settings...
Relevant software is: vasp
Construct a casm.vaspwrapper.Relax instance:
  Input directory: /home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/training_data/SCEL1_1_1_1_0_0_0/0
  Configuration: SCEL1_1_1_1_0_0_0/0
  Reading CASM settings
  Calculations directory: /home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default
  Reading relax.json settings file
  Read settings from: /home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/training_data/settings/calctype.default/relax.json
  DONE

Constructing a VASP Relax object
  Relax directory: /home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default
VASP Relax object constructed

Wrote /home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default/status.json
Begin VASP relaxation run

++  status: incomplete   next task: /home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default/run.0
Continue VASP job:
  Original: /home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default/run.0
  Continuation: /home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default/run.1
 backup:

  no CONTCAR: cp POSCAR -> POSCAR
  mv: POTCAR 
  cp: KPOINTS INCAR 
  rm: 
 gzip: 

Begin vasp run:
  jobdir: /home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default/run.1
  exec: mpirun -np 24 vasp
Run complete
Most recent file output (std.out): 3.5396478176116943  seconds ago.

++  status: incomplete   next task: constant
Continue VASP job:
  Original: /home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default/run.1
  Continuation: /home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default/run.2
 backup:

  cp CONTCAR -> POSCAR
  mv: POTCAR 
  cp: KPOINTS INCAR 
  rm: 
 gzip: 

  Set INCAR tags: {'ISIF': 2, 'ISMEAR': -5, 'NSW': 0, 'IBRION': -1, 'SYSTEM': 'final'} 

Begin vasp run:
  jobdir: /home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default/run.2
  exec: mpirun -np 24 vasp
Run complete
Most recent file output (std.out): 4.0523412227630615  seconds ago.

++  status: complete   next task: None
mv run.2 run.final
Complete VASP job: /home/bsjun/00JOBS/04_MetalAlloy/CASM/ZrO_tuto2/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default/run.final
  rm: 
 gzip: 

unsupported operand type(s) for +: 'int' and 'str'
</pre>

**Comment by bpuchala** [comment]
Which version or branch is this?

**Comment by 91bsjun** [comment]
I installed CASM v0.3 using conda at CentOS <code>$ conda create -n casm --override-channels -c bpuchala/label/dev -c prisms-center -c defaults -c conda-forge casm </code>
How can I install the v0.2 using conda?

**Comment by bpuchala** [comment]
Version 0.2 is not available via conda.  

About the error, was the "run.final" directory created?  Was the "properties.calc.json" file created?
The error may be with the format of a value in your "relax.json" file. Can you share your "relax.json" file?

**Comment by 91bsjun** [comment]
"run.final" was created but "properties.calc.json" was not.

<pre>
[bsjun@ calctype.default]$ ls
INCAR.base  run.0/  run.1/  run.final/  status.json
[bsjun@ calctype.default]$ ls run.final/
CHG     CONTCAR  EIGENVAL  INCAR    OSZICAR  PCDAT   POTCAR  std.err  vasprun.xml  XDATCAR
CHGCAR  DOSCAR   IBZKPT    KPOINTS  OUTCAR   POSCAR  REPORT  std.out  WAVECAR
</pre>

And this is my relax.json file
<pre>
{
  "queue":"batch",
  "ppn":"24",
  "atom_per_proc":"2",
  "walltime":"2:00:00",
  "ncpus":"24",
  "run_limit":10,
  "nrg_convergence":0.002,
  "npar":8
}
</pre>

**Comment by 91bsjun** [comment]
Fix this error by changing minor part in `prisms-center/prisms_jobs/__init__.py`
`self.jobid + ": " + self.msg` to `str(self.jobid) + ": " + self.msg`
I committed it.
