### ISSUE TITLE
Issues with 'Set chemical reference'

### ISSUE THREAD

**Issue by Sparkliang** [prisms-center/CASMcode#121]
Dear developers
Thank you for your software. But, I cannot set chemical reference. When I run 'set casm ref --set-auto', it shows 
'
  Set reference states automatically.

Global chemical reference:
  Li(0.25)Ni(0.25)O(0.5): -1.62283
  Co(0.25)Li(0.25)O(0.5): -1.62283
'
and then I run 'casm status -n'
it returns 'No chemical reference set.'
How can I figure out this problem? Thank you so much!

**Comment by bpuchala** [comment]
Thank you for raising an issue.  

- Which version of CASM are you using? 
- After running ```casm ref --set-auto```, is the ```"$ROOT/training_data/settings/$CURR_CALCTYPE/$CURR_REF/chemical_reference.json``` file created?
- What does ```casm ref --display``` show before / after doing  ```casm ref --set-auto```?

**Comment by Sparkliang** [comment]
Thank you for your replay!
- My version of  CASM is `casm version: 0.2.1+889e881`.
- After running `casm ref --set-auto`, there is no such file have been created.
- When I run `casm ref --display`, it shows that
`-- Construct: CASM Project -- `
`from: "/home/liangxing/path/to/test"`

`-- Load project data -- `
`read: "/home/liangxing/path/to/test/.casm/composition_axes.json"`
`read: "/home/liangxing/path/to/test/training_data/SCEL"`
`read: "/home/liangxing/path/to/test/.casm/config_list.json"`

`Error using 'casm ref --display': No reference found.`
 ` Expected file at: "/home/liangxing/path/to/test/training_data/settings/calctype.default/ref.default/chemical_reference.json"`
`Use 'casm ref --set' or 'casm ref --set-auto' to set a reference`
So, what can I do to figure this out? Thank you so much again!

**Comment by Yangxinsix** [comment]
Hi Sparkliang! This issue seems to be common because my task has just suspended at this step as well. If you have any ideas about this, could you please give me some instructions? Thanks!

**Comment by jcthomas** [comment]
I'm able to recreate this issue if I delete the directory at `$PROJECTDIRECTORY/training_data/settings/calctype.default/ref.default/`, which is constructed when the project is initialized. Did you delete this directory at some point? 

You should be able to get back on track by making the directory in that location, and then re-running `casm ref` to select appropriate references.

I'm going to mark this as a bug, since `casm ref` should create the appropriate directory if it doesn't already exist.

**Comment by Yangxinsix** [comment]
It works! Maybe I have unconsciously deleted the directory. Thank you!

**Comment by Sparkliang** [comment]
Thank you again! That's the perfect solution of this problem!
