### ISSUE TITLE
Issue with 'casm-learn --checkhull'

### ISSUE THREAD

**Issue by Sparkliang** [prisms-center/CASMcode#122]
Dear developers
Thank you for your useful software. When I went for step `(7) Fit effective cluster interactions (ECI)`, I found that I would get no response when I ran `casm-learn --checkhull`, that is:
`$ casm-learn --checkhull`
```
`/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module `was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
usage: casm-learn [-h] [--desc] [-s SETTINGS] [--format FORMAT]
                  [--settings-format] [--exLasso] [--exLassoCV] [--exRFE]
                  [--exGeneticAlgorithm] [--exIndividualBestFirst]
                  [--exPopulationBestFirst] [--exDirectSelection] [--hall]
                  [--indiv INDIV [INDIV ...]] [--select SELECT] [--checkhull]
                  [--checkspecs] [-q]

Fit cluster expansion coefficients (ECI)

optional arguments:
  -h, --help            show this help message and exit
  --desc                Print extended usage description
  -s SETTINGS, --settings SETTINGS`
......
```
So, what's the reason of this situation? Did I miss some steps or something?
Thank you so much! This codes help me a lot!

**Comment by bpuchala** [comment]
The ```--checkhull``` option, like most ```casm-learn``` options, uses values in your input settings file, so that file must also be specified:

```
casm-learn -s <settingsfile> --checkhull
```

By default it will check the hull for all solutions in your hall of fame, but you can also specify that it just check particular individual solutions with ```--indiv```, for example:

```
casm-learn -s <settingsfile> --checkhull --indiv 0
```

**Comment by Sparkliang** [comment]
Thank you for your reply! When I ran `casm-learn -s fit_1_ga.json --checkhull` I got this:
```
Writing: /home/liangxing/path/to/test/cluster_expansions/clex.formation_energy/calctype.default/ref.default/bset.default/eci.__tmp/eci.json 

Traceback (most recent call last):
  File "/usr/local/bin/casm-learn", line 84, in <module>
    casm.learn.fit.checkhull(input, existing_hall, indices=args.indiv, verbose=args.verbose)
  File "/usr/local/lib/python2.7/dist-packages/casm/learn/fit.py", line 2028, in checkhull
    write_eci(proj, indiv.eci, fit_details=casm.learn.to_json(indiv_i, indiv), clex=clex, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/casm/project/io.py", line 59, in write_eci
    with open(filename, 'w') as f:
IOError: [Errno 2] No such file or directory: u'/home/liangxing/path/to/test/cluster_expansions/clex.formation_energy/calctype.default/ref.default/bset.default/eci.__tmp/eci.json'

```
So, I think I still miss some steps.

**Comment by bpuchala** [comment]
I think this is probably due to your directory structure being out of sync with your project settings. Make sure that all of these directories exist: ```/home/liangxing/path/to/test/cluster_expansions/clex.formation_energy/calctype.default/ref.default/bset.default/eci.__tmp``` and create them if they don't.

You can also double check your current settings with ```casm settings -l``` and use ```casm format --dir``` to get a summary of what the directory structure is supposed to look like.

**Comment by Sparkliang** [comment]
Yes, it works. Thank you so much! But after I ran `casm-learn -s fit_1_ga.json --checkhull`, I found that the dirctory `/bset.default` disappeared, and there is no `eci.json`, so the process suspended at `7) Fit effective cluster interactions (ECI): FALSE`

**Comment by bpuchala** [comment]
The ```/home/liangxing/path/to/test/cluster_expansions/clex.formation_energy/calctype.default/ref.default/bset.default``` directory disappeared? If you re-create it is it deleted every time you run ```--checkhull```?

What are the current project settings from ```casm settings -l```?

Also, is this still version ```casm version: 0.2.1+889e881``` as in the other issue?

**Comment by Sparkliang** [comment]
Sorry, I mean the `eci.__tem` directory disappeared and if I re-create it, it will be deleted after I run `--checkhull`
My project settings is: 
```
-- Cluster expansions -- 
formation_energy*: 
      property: formation_energy
      calctype: default
           ref: default
          bset: default
           eci: __tmp


-- Basis sets -- 
default*

-- Training Data & References -- 
default / default*

-- ECI for current cluster expansion settings group -- 

*: indicates the default settings used by CASM whenever particular 
settings are not explicitly specified (i.e. the basis set to evaluate 
for 'casm query -k corr')

-- Compiler settings -- 
cxx: 'g++' (default)
cxxflags: '-O3 -Wall -fPIC --std=c++11' (default)
soflags: '-shared -lboost_system' (default)
casm_includedir: '/usr/local/include' (default)
casm_libdir: '/usr/local/lib' (default)
boost_includedir: '/usr/local/include' (default)
boost_libdir: '/usr/local/lib' (default)

compile command: 'g++ -O3 -Wall -fPIC --std=c++11 -I/usr/local/include -I/usr/local/include'

so command: 'g++ -shared -lboost_system -L/usr/local/lib -L/usr/local/lib'

-- 'casm view' -- 
command: 'casm.view VESTA'
```
Yeah, its version is `casm version: 0.2.1+889e881`

**Comment by bpuchala** [comment]
OK, yes, the way it is supposed to work is that you start with whatever your current eci setting is, say ```eci.default```, and the ```__tmp``` eci are supposed to be used only temporarily during ```--checkhull```, then once ```--checkhull``` finishes ```eci.__tmp``` get deleted and your project switches back to your original eci setting ```eci.default``` .  When ```casm-learn``` crashed, it stayed in ```eci.__tmp``` and did not revert to ```eci.default```.  

So:
- do ```casm settings --new-eci default``` to re-create and switch to the ```eci.default``` setting
- then run ```casm-learn -s fit_1_ga.json --checkhull``` again.

**Comment by Sparkliang** [comment]
After run these two command, I re-create and switch to the `eci.default`, but I still find there is no `eci.json` exists, and I still trap at the step 7)

**Comment by bpuchala** [comment]
The ```--checkhull``` command does not select a particular individual, it just checks the hull.  To select a eci solution and print the ```eci.json``` file you need to explicitly select it with ```casm-learn -s fit_1_ga.json --select <number>```.

The idea here is that CASM should not overwrite your existing eci without you explicitly running ```--select```. That's why ```--checkhull``` goes through the trouble of creating a temporary ```eci.__tmp```.

**Comment by Sparkliang** [comment]
Thanks a lot. And what does the `<number>` mean in `casm-learn -s fit_1_ga.json --select <number>`

**Comment by bpuchala** [comment]
When you check the solutions that have been generated and saved in your "hall of fame" with ```casm learn -s fit_1_ga.json --hall```, the solutions are sorted by CV score.  The ```<number>``` is the index of an individual in the hall of fame. So ```casm-learn -s fit_1_ga.json --select 0``` would select the first individual in the hall of fame which has the lowest CV score.

**Comment by Sparkliang** [comment]
Understood, I really appreciate the kindly help!

**Comment by jcthomas** [comment]
Marking this as suboptimal behavior, since casm-learn crashing really should not break the project settings. 

I think we could easily fix this by allowing an additional argument to the API calls in order to explicitly specify which settings to profile to use. Then casm-learn won't have to perform a hard set on the global settings profile.
