### ISSUE TITLE
Simple CV and RMS unit question with casm-learn

### ISSUE THREAD

**Issue by Erothch** [prisms-center/CASMcode#124]
Dear casm users and developers,

Apologies if this is in the documentation but I was not able to find it there. When using casm learn what are the units for the CV and RMS numerical error output in? It appears to be in meV but I cannot tell if it's meV per atom or per formula unit of the primitive cell. I really appreciate the help.

Best,
Eric

**Comment by bpuchala** [comment]
Typically ```casm learn``` output is in eV/unit cell, because that is the units for VASP data output by ```casm query``` / ```casm select```.  

But to be precise, ```casm learn``` does not know anything about the units itself, so if you give it custom data via ```"filetype": "csv"``` or ```"filetype":"json"``` the units will be the same units as whatever data you give.

**Comment by Erothch** [comment]
Understood - Thanks for the quick response!

Best,
Eric
