### ISSUE TITLE
no 'canonical' ensemble option for monte carlo calculation

### ISSUE THREAD

**Issue by jjcordell** [prisms-center/CASMcode#125]
Hi,
I would like to run monte carlo calculations (in this case just using the ZrO demo) using the canonical ensemble. I worked through some errors in my input file, but when I finally submit, I get this error:
```
Invalid ensemble: Canonical
Options are:
  GrandCanonical or grand_canonical
ERROR reading Monte Carlo settings.

ERROR: Invalid ensemble: Canonical
```
I tried both "canonical" and "Canonical" for ensemble, but got this error both times. The `casm monte` documentation lists this as an option, but the error suggests `canonical` is not an option. Is there a way to get around this?

Thanks

**Comment by bpuchala** [comment]
What version are you using?

**Comment by jjcordell** [comment]
0.2.X

**Comment by bpuchala** [comment]
If no one else has a quick answer, I'll try to check it out tonight.

**Comment by jjcordell** [comment]
Hi,
Just curious if anyone was able to find/avoid this error.

Thanks

**Comment by jcthomas** [comment]
Could you please share your settings file that is causing failure? 

Are you certain that you're using 0.2.X? Prior release that are still hosted in the repo do not support canonical simulations, and so would yield this error. If you navigate to [this line](https://github.com/prisms-center/CASMcode/blob/0.2.X/src/casm/monte_carlo/MonteDefinitions.cc#L9) in the version of the CASM source that you compiled locally, it should be identical to the line in the link. This is what makes the "Canonical"/"canonical" option reachable by the CLI.

**Comment by jjcordell** [comment]
Found the issue. It was a matter of version. 0.2.X is installed and all of the files check out, but I had been working out of a virtual environment and a previous version of CASM was sourced earlier in my `PATH`.

Thanks for your time.
