### ISSUE TITLE
creating dftb+wrapper to obtain properties.calc.json

### ISSUE THREAD

**Issue by Anshuman5** [prisms-center/CASMcode#126]
Hi developers,

I am trying to use dftb+ instead of VASP to calculate the 'DFT' energies. Can someone guide me here how to implement the dftb+wrapper instead of the VASP one ?

Thanks and Regards

**Comment by skk74** [comment]
Sorry for just now getting to this. Writing a new wrapper can be done by taking a little dive into the code to see how parsing is generally done with respect to the wrappers that we have. If you need additional help or want to set up a debriefing meeting, please email me skolli@ucsb.edu and we can set up a skype call to talk about what needs to be done.
