### ISSUE TITLE
Import/mapping of pure Va configuration fails

### ISSUE THREAD

**Issue by jcthomas** [prisms-center/CASMcode#13]
In a project that allows the pure Va configuration, mapping the pure-Va configuration onto the PRIM during either `casm update` or `casm import` results in segmentation fault.

**Comment by sriharsha09** [comment]
It still seg faults when I do casm update. I am using the properties.calc.json you sent me in the previous replies to set its energy. I am attaching the project. 
[proj.tar.gz](https://github.com/prisms-center/CASMcode/files/462977/proj.tar.gz)

**Comment by jcthomas** [comment]
I was only testing `casm import`, but there were some residual issues with
`casm update` that I missed.  Those should be fixed now.

**Comment by sriharsha09** [comment]
Hi John, that fixed the issue with casm update. But when I query its formation energy (after setting the proper references) it came out as '-nan' instead of 0. But it handled the relaxed_energy query properly.

**Comment by jcthomas** [comment]
This is due to the fact that formation energy is now calculated in terms of
atom fraction, instead of parametric composition.  The atom fraction of the
pure Va case is (0./0.) (which is nan) and the formation energy ends up
being something like (0./nan).

After giving it a bit of thought, the only reasonable solution I've come up
with would be to:
(a) Define the formation_energy and formation_energy_per_species to be 0
for the vacuum configuration; enforce with an if/else block. (b) Define
atom_frac("specie") to be zero for all species in the vacuum configuration;
enforce with an if/else block.  These are ad-hoc definitions, but could be
argued to be the most natural definitions for the vacuum state.

I'm inclined to suggest that find a different way to do what you're trying
to do (you could, in principle, come up with a query that gives the weights
you want).  I don't really see how having the vacuum configuration is going
to help you (it won't, for example, change the distances of any other
configurations to the convex hull.  Perhaps I'm misunderstanding why you
want this?

**Comment by sriharsha09** [comment]
Its not really crucial for me to have it. I was just wondering if it was possible. I can get around the issue by making custom weights.

**Comment by sjtuzhanglei** [comment]
Has this been fixed?
