### ISSUE TITLE
meanings of several characters

### ISSUE THREAD

**Issue by XU-jialiang** [prisms-center/CASMcode#130]
Dear developers,
  I have several questions.
1. when I submit jobs, some calculations don't get convergence. I want to rerun these works independently. But I don't know how to realize it.
2. The meanings of the follow characters are also needed.
susc_x(i,j) susc_x(S,i),susc_n(i,j),susc_n(S,i)
And  the phi is the free energy during the Phase diagram construction, isn't it?
3. Any more informations about the Monte Carlo calculate in CASM are need for me.
Thank you very much~

**Comment by bpuchala** [comment]
1. When a job fails to finish, it should generate a configuration-specific settings directory, for instance "<proj>/training_data/<scelname>/<config_id>/settings/<calctype>" with a copy of input files that will override the global input files in "<proj>/training_data/settings/<calctype>". So after making any input adjustments and increasing the "run_limit" in the configuration's relax.json file you are ready to re-submit.  The [pstat](https://prisms-center.github.io/prisms_jobs_docs/scripts/pstat.html) command line program that is part of the prisms-jobs package can then "--continue" any unfinished jobs.

2. Definitions of those susceptibilities are given in our description of the parameteric composition, available [here](https://prisms-center.github.io/CASMcode_docs/assets/definitions/CASM_param_comp.pdf).

3. The CASM tutorial available [here](https://github.com/prisms-center/CASMcode_demo/tree/master/TMS_ICME_PRISMS_workshop_May_2017) has some information about the Monte Carlo calculations and example scripts useful for generating a predicted phase diagram from the Monte Carlo results.
