### ISSUE TITLE
 join() argument must be str or bytes, not 'NoneType'

### ISSUE THREAD

**Issue by shaliu19900911** [prisms-center/CASMcode#131]
Dear developer,

I faced an error when run 'casm-calc --setup' and 'casm-calc submit'.

Anything I can fix this?
The error is below:

(casm) liusha@liusha-Ubt:calctype.default$ casm-calc --setup
-- Construct: CASM Project -- 
from: "/home/liusha/Documents/theta2"

-- Load project data -- 
read: "/home/liusha/Documents/theta2/.casm/composition_axes.json"
read: "/home/liusha/Documents/theta2/training_data/SCEL"
read: "/home/liusha/Documents/theta2/.casm/config_list.json"

  Reading relax.json settings file
Using /home/liusha/Documents/theta2/training_data/settings/calctype.default/relax.json as settings...
Relevant software is: quantumespresso
Working on directory /home/liusha/Documents/theta2/training_data/SCEL1_1_1_1_0_0_0/0
  Configuration: SCEL1_1_1_1_0_0_0/0
Reading CASM settings
Constructing a CASM QEWrapper Relax object
  Setting up directories
  Reading relax.json settings file
Using /home/liusha/Documents/theta2/training_data/settings/calctype.default/relax.json as settings...
Quantum Espresso Relax object constructed

join() argument must be str or bytes, not 'NoneType'

**Comment by skk74** [comment]
This is likely to be fixed in the most recent branch casm 0.3.X

**Comment by bpuchala** [comment]
QE setup issues addressed in #134 and #136
