### ISSUE TITLE
compatibility with python3?

### ISSUE THREAD

**Issue by DallasTrinkle** [prisms-center/CASMcode#132]
I'm trying to do an installation using `scons`, and within a python3 environment. I had to edit the `SConstruct` file to be compatible with python3 by changing the `print` statements to `print` functions, and adding `decode('utf-8')` to output of process to convert bytes to strings... but I'm still running into strange issues just getting `scons configure` to run. Has anyone had success in using CASM with python3?

**Comment by jcthomas** [comment]
From your question, it sounds like you are installing from branch 0.2.X or earlier, which is not python3 compatible. 

The latest version, [0.3.X](https://github.com/prisms-center/CASMcode/tree/0.3.X), does support python3. It is available as a conda package (details [here](https://prisms-center.github.io/CASMcode_docs/pages/installation.html)) or can also be installed from source following the procedure in [INSTALL.md](https://github.com/prisms-center/CASMcode/blob/0.3.X/INSTALL.md).

**Comment by DallasTrinkle** [comment]
Alright; I'll try out the latest branch instead--thanks!
