### ISSUE TITLE
-fdiagnostics-color not -fcolor-diagnostics

### ISSUE THREAD

**Issue by DallasTrinkle** [prisms-center/CASMcode#133]
In file `build_scripts/travis-variables-osx.sh`, the variable has a typo which causes the c++ compiler checks to fail on MacOS. From what I can tell, this is a typo, albeit a strange one. Perhaps an earlier version of the c++ compilers accepted `-fcolor-diagnostics`? This is the 0.3.X branch.

**Comment by DallasTrinkle** [comment]
This is with gcc8.

**Comment by bpuchala** [comment]
Thanks for the note. This seems to be a gcc vs clang issue. All our Mac testing is with clang right now.

**Comment by DallasTrinkle** [comment]
It looks like clang can take the option either way, so it's an easy change to make; --d

> On 2019Jan11 , at 2:35 PM, Brian Puchala <notifications@github.com> wrote:
> 
> Thanks for the note. This seems to be a gcc vs clang issue. All our Mac testing is with clang right now.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Dallas R. Trinkle
Professor, Associate Head
308 Materials Science and Engineering
University of Illinois, Urbana-Champaign
Phone: 217.244.6519
Fax: 217.333.2736
Email: dtrinkle@illinois.edu
Web: http://dtrinkle.matse.illinois.edu
