### ISSUE TITLE
structure score reference 

### ISSUE THREAD

**Issue by DS-Wen** [prisms-center/CASMcode#135]
Hi developers,

I am looking for reference to calculate the structure scores of configurations.

thanks,
Dongsheng

**Comment by jcthomas** [comment]
The structure scores for relaxed configurations are a weight average of the lattice deformation (L) and basis deformation (B), of the form S=w*L + (1-w)*B, where 'w' is on the interval [0,1).

The basis deformation (B) is the mean-square atomic displacement [Angstr.^2/atom], relative to the ideal positions in prim.json. It is not affected by a rigid translation of the crystal.

The lattice deformation (L) is defined as the mean-square displacement [Angstr.^2/atom] of the surface of a spherical shell having the Wigner-Seitz radius of the ideal crystal when it undergoes the same deformation transformation as the relaxed lattice. It only measures shape changes and is invariant to changes in volume. 

CASM robustly finds the mapping of relaxed structures to the ideal structure that minimizes the structure score, irrespective of rigid translation or rotation of the relaxed structure relative to the ideal structure.

Unfortunately, the mathematical details of CASM's structure mapping algorithm have not yet been published. I will post a link on this issue when the manuscript is available.
