### ISSUE TITLE
compute formation energy from cluster expansion

### ISSUE THREAD

**Issue by jjcordell** [prisms-center/CASMcode#138]
Hello developers,
I would like to use a cluster expansion set up in a CASM project to compute the energy of 1) a supercell in the training set, 2) another supercell without DFT calculations run yet and 3) ideally, an outside POSCAR, not enumerated in CASM. The first two seem fairly straightforward, but I have not been able to find a way to do this after much searching and experimenting. I have tried various queries and essentially run MC simulations with zero steps, but have run into various errors. What is the easiest way to calculate a structure's formation energy from a CE within the CASM framework?

I use CASM 0.2.X for the time being.

Thanks

**Comment by jcthomas** [comment]
Have you tried  `casm query -k "clex(formation_energy)"`?

In that example, 'formation_energy' refers to the name of the cluster expansion (typically the same as the name of the property being represented). 'formation_energy' is the default cluster expansion. If you have used `casm settings` to give your cluster expansion a different name (for example, 'my_formation_energy'), then the equivalent command would be `casm query -k "clex(my_formation_energy)"`.  

The query will be run on your current selection of configurations, which you can specify via `casm select`. You can also construct a custom selection file by hand having the form
````
#     name         selected
SCEL1_1_1_1_0_0_0/0     1
SCEL1_1_1_1_0_0_0/1     1
 ... 
````

To add a new configuration to your project that was not enumerated by casm, you can use `casm import`.  This will find the best way to map the POSCAR onto the reference crystal by considering all possible relative rotations and translations of the two crystals.
Ex: `casm import --pos path/to/POSCAR`
At the end, a report will be printed to the screen with relaxation stats and showing the name of the configuration corresponding to the imported POSCAR. You can then add this configuration to your selection and query its formation_energy as above.

If you have already tried these steps and run into other issues, please let us know what errors you are encountering so we can help you find a resolution.

**Comment by jjcordell** [comment]
Thanks, I have already tried `casm query -k "clex(formation_energy)"` but your comment tells me where to look. 
When I run `casm query -k "clex(formation_energy)"` I get the error:
`#Initialization error: Error loading ECI. eci.json does not exist.` which tells me that `casm-learn -s fit_1_ga.json --select 0` did not run correctly. Sure enough, when I run `casm-learn -s fit_1_ga.json --select 0`, I get
 `Loading Hall of Fame: fit_1_ga_halloffame.pkl`
`Traceback (most recent call last):`
`...`
  `File ".../CASMcode-0.2.X/python/casm/casm/project/io.py", line 40, in write_eci
    j["cluster_functions"][index]["eci"] = value`
`IndexError: list index out of range`

I  noticed io.py changes quite a bit for 0.3.X; is this something that is fixed in 0.3.X? Or are there other steps I may have missed for selecting a set of eci to write to eci.json?

I haven't tested `casm import` yet, but that looks to solve that portion of my question.

Thanks again

**Comment by bpuchala** [comment]
Just to check, you do have valid solutions in your halloffame? For instance, ```casm learn -s fit_1_ga.json --hall``` shows results but then it fails at ```casm learn -s fit_1_ga.json --select 0```?

**Comment by jjcordell** [comment]
Correct, I get a deprecation warning when I run `casm-learn -s fit_1_ga.json --hall` but the hall of fame 
 prints to screen

**Comment by bpuchala** [comment]
I was able to recreate this error when I fit eci, then reduce the basis set size (change the bspecs.json file and run "casm bset -uf"), then try to select eci fit from the previous, larger basis set. 

So it seems there is now a mismatch between the basis set you have generated and the one used to do the fitting.

**Comment by jjcordell** [comment]
Thanks, that makes sense. I reset bspecs.json to the fit I'm working with now and it generates the eci.json file. Thanks again
