### ISSUE TITLE
fine_grid Monte Carlo failed when come to submit_xi_up and submit_xi_down

### ISSUE THREAD

**Issue by shaliu19900911** [prisms-center/CASMcode#140]
**Dear developer,
I already finished the LTE MC, and now come to fine grid MC of free energy. The MC with T_up and T_down run well, but when come to submit_xi_up or submit_xi_down, I faced an error as below:**

Traceback (most recent call last):
  File "re_run.py", line 192, in <module>
    submit_xi_up(T_grid, xi_grid)
  File "re_run.py", line 149, in submit_xi_up
    json.dump(tinput, f)
  File "/home/shaliu/anaconda3/envs/casm/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/shaliu/anaconda3/envs/casm/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/shaliu/anaconda3/envs/casm/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/home/shaliu/anaconda3/envs/casm/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/home/shaliu/anaconda3/envs/casm/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/home/shaliu/anaconda3/envs/casm/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/home/shaliu/anaconda3/envs/casm/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'int64' is not JSON serializable
### 

**The submit python script is as beblow. Anything I can fix this?**

import subprocess
import json
import os
import numpy as np
import copy
from casm.project import Project
#import pbs

# Grid space to run Monte Carlo calculations (min, max, delta)
T_grid = (200, 1000, 10)
xi_grid = (-2.2, -1.6, 0.01)

d = {
  "mode" : "incremental",
  "dependent_runs" : True, 
  "motif" : {
    "configname" : "restricted_auto",
  },
  "initial_conditions" : {
    "param_chem_pot" : {
      "a" : -3.00
    },
    "temperature" : 1000.0,
    "tolerance" : 0.001
  },
  "final_conditions" : {
    "param_chem_pot" : {
      "a" : -3.00
    },
    "temperature" : 200.0,
    "tolerance" : 0.001
  },
  "incremental_conditions" : {
    "param_chem_pot" : {
      "a" : 0.0
    },
    "temperature" : -100.0,
    "tolerance" : 0.001
  }
}

proj = None

# For submission on personal computer...
def monte_cmd(input):
  global proj
  if proj is None:
    proj = Project()
# stdout, stderr, returncode = proj.command('monte -s input.json')
  proj.command('monte -s input.json')
 # print(stdout)

# `For submission on PRISMS cluster...
#
#def monte_cmd(input):
#  jobname = os.path.basename(os.getcwd())
#  
#  cmd = """
#source ~/privatemodules/casm
#casm monte -s input.json
#"""
#  
#  job = pbs.PrismsDebugJob(name = jobname,
#                           nodes = "1",
#                           ppn = "1",
#                           walltime = "6:00:00",
#                           pmem = "3800mb",
#                           exetime = None,
#                           message = "a",
#                           email = None,
#                           command = cmd,
#                           auto = False).submit()
   
  
def submit_T_up(T_grid, xi_grid):
  index = 0
  for xi in np.arange(*xi_grid):
    path = "T_up." + str(index)
    
    tinput = copy.deepcopy(input)
    tinput['driver'] = d
    tinput['driver']['initial_conditions']['temperature'] = T_grid[0]
    tinput['driver']['final_conditions']['temperature'] = T_grid[1]
    tinput['driver']['incremental_conditions']['temperature'] = T_grid[2]
    
    tinput['driver']['initial_conditions']['param_chem_pot']['a'] = xi
    tinput['driver']['final_conditions']['param_chem_pot']['a'] = xi
    tinput['driver']['incremental_conditions']['param_chem_pot']['a'] = 0.0
    
    cwd = os.getcwd()
    os.mkdir(path)
    os.chdir(path)
    
    with open('input.json','w') as f:
      json.dump(tinput, f)
    
    monte_cmd(tinput)
    
    os.chdir(cwd)
    index += 1

def submit_T_down(T_grid, xi_grid):
  index = 0
  for xi in np.arange(*xi_grid):
    path = "T_down." + str(index)
    
    tinput = copy.deepcopy(input)
    tinput['driver'] = d
    tinput['driver']['initial_conditions']['temperature'] = T_grid[1]
    tinput['driver']['final_conditions']['temperature'] = T_grid[0]
    tinput['driver']['incremental_conditions']['temperature'] = -T_grid[2]
    
    tinput['driver']['initial_conditions']['param_chem_pot']['a'] = xi
    tinput['driver']['final_conditions']['param_chem_pot']['a'] = xi
    tinput['driver']['incremental_conditions']['param_chem_pot']['a'] = 0.0
    
    cwd = os.getcwd()
    os.mkdir(path)
    os.chdir(path)
    
    with open('input.json','w') as f:
      json.dump(tinput, f)
    
    monte_cmd(tinput)
    
    os.chdir(cwd)
    index += 1

def submit_xi_up(T_grid, xi_grid):
  index = 0
  for T in np.arange(*T_grid):
    path = "xi_up." + str(index)
    
    tinput = copy.deepcopy(input)
    tinput['driver'] = d
    tinput['driver']['initial_conditions']['temperature'] = T
    tinput['driver']['final_conditions']['temperature'] = T
    tinput['driver']['incremental_conditions']['temperature'] = 0.0
    
    tinput['driver']['initial_conditions']['param_chem_pot']['a'] = xi_grid[0]
    tinput['driver']['final_conditions']['param_chem_pot']['a'] = xi_grid[1]
    tinput['driver']['incremental_conditions']['param_chem_pot']['a'] = xi_grid[2]
    
    cwd = os.getcwd()
    os.mkdir(path)
    os.chdir(path)
    
    with open('input.json','w') as f:
      json.dump(tinput, f)
    
    monte_cmd(tinput)
    
    os.chdir(cwd)
    index += 1

def submit_xi_down(T_grid, xi_grid):
  index = 0
  for T in np.arange(*T_grid):
    path = "xi_down." + str(index)
    
    tinput = copy.deepcopy(input)
    tinput['driver'] = d
    tinput['driver']['initial_conditions']['temperature'] = T
    tinput['driver']['final_conditions']['temperature'] = T
    tinput['driver']['incremental_conditions']['temperature'] = 0.0
    
    tinput['driver']['initial_conditions']['param_chem_pot']['a'] = xi_grid[1]
    tinput['driver']['final_conditions']['param_chem_pot']['a'] = xi_grid[0]
    tinput['driver']['incremental_conditions']['param_chem_pot']['a'] = -xi_grid[2]
    
    cwd = os.getcwd()
    os.mkdir(path)
    os.chdir(path)
    
    with open('input.json','w') as f:
      json.dump(tinput, f)
    
    monte_cmd(tinput)
    
    os.chdir(cwd)
    index += 1

####  

with open('metropolis_grand_canonical.json','r') as f:
  input = json.load(f)

submit_T_up(T_grid, xi_grid)
submit_T_down(T_grid, xi_grid)
submit_xi_up(T_grid, xi_grid)
submit_xi_down(T_grid, xi_grid)

**Comment by bpuchala** [comment]
Thanks for raising this.

Try changing ```T``` to ```int(T)```, for instance on lines like:
```
tinput['driver']['initial_conditions']['temperature'] = T
```
change to
```
tinput['driver']['initial_conditions']['temperature'] = int(T)
```

**Comment by shaliu19900911** [comment]
Thanks Brian! It is solved!
