### ISSUE TITLE
Is it possible to install CASM in window?

### ISSUE THREAD

**Issue by jungsdao** [prisms-center/CASMcode#142]
Dear developers..

I've installed casm in linux and it works well, but when I tried to install it in window error has been occurred.
After Anaconda, I entered following installation command in anaconda prompt window and I got this:

COMMAND:
conda create -n casm --override-channels -c bpuchala/label/dev -c prisms-center -c defaults -c conda-forge casm

ERROR MESSAGE:
 PackagesNotFoundError: The following packages are not available from current channels:
-casm

does that mean CASM cannot be installed in windows system?
Though it may seem a silly question, please help. 

Regards,

**Comment by bpuchala** [comment]
Yes, you are correct, CASM is not available on Windows.
