### ISSUE TITLE
MC not reach the final xi

### ISSUE THREAD

**Issue by shaliu19900911** [prisms-center/CASMcode#143]
Dear developer,

I faced a problem during integration phi. I set the T_grid = (200, 1000, 100) and xi_grid = (-2.2, -0.1, 0.1) at the MC running. But, when everything finished, the T_up and T_down only expand from -0.1999999999999984 to -2.2, while the xi values in xi_up and xi_down are complete. This brought some difficulty to integrate phi because the T-xi space is not complete and the minimum xi value is missing during integrating xi. I want to know why this happen and how to solve it?

**Comment by shaliu19900911** [comment]
I have solved this problem by replace lines such as "xi in np.arange(*xi_grid):" with "for xi in np.linspace(-2.2, -0.1, 8, endpoint = True):". By this way the last values of T_grid and xi_grid are included.

**Comment by bpuchala** [comment]
Looks like a floating point precision issue. Try something like xi_grid = (-2.2, -0.1 + 0.01, 0.1).
