### ISSUE TITLE
error in job submission in slurm

### ISSUE THREAD

**Issue by jungsdao** [prisms-center/CASMcode#144]
PBS system : SLURM
While using command "casm-calc --submit", I'm encountering error as follows.
Another programs and libraries are controlled by conda.
It's too difficult to recognize this error message what program is printed "name 'prisms_jobs' is not defined" where SLURM or PRISM job module or CASM module.
It would be helpful if you could give me some information. 

Regards, 

-------------
[jungsdao2@HAN-HPC j_casm3]$ casm-calc --submit
-- Construct: CASM Project --
from: "/home/jungsdao2/j_casm3"

-- Load project data --
read: "/home/jungsdao2/j_casm3/.casm/composition_axes.json"
read: "/home/jungsdao2/j_casm3/training_data/SCEL"
read: "/home/jungsdao2/j_casm3/.casm/config_list.json"

  Reading relax.json settings file
Using /home/jungsdao2/j_casm3/training_data/settings/calctype.default/relax.json as settings...
Relevant software is: vasp
Construct a casm.vaspwrapper.Relax instance:
  Input directory: /home/jungsdao2/j_casm3/training_data/SCEL1_1_1_1_0_0_0/0
  Configuration: SCEL1_1_1_1_0_0_0/0
  Reading CASM settings
  Calculations directory: /home/jungsdao2/j_casm3/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default
  Reading relax.json settings file
  Read settings from: /home/jungsdao2/j_casm3/training_data/settings/calctype.default/relax.json
  DONE

Submitting...
Configuration: SCEL1_1_1_1_0_0_0/0
Calculation directory: /home/jungsdao2/j_casm3/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default
JobID: []
Constructing a VASP Relax object
  Relax directory: /home/jungsdao2/j_casm3/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default
VASP Relax object constructed

Preparing to submit a VASP relaxation job
Counting atoms in the POSCAR
Constructing a job
Submitting
name 'prisms_jobs' is not defined

**Comment by bpuchala** [comment]
This is a bug in prisms_jobs. I've pushed some changes to the 4.X branch that I believe fix the issue, and also added a "constraint" option that is recognized for SLURM. I will update the pip and conda packages as soon as I get some tests run. 

A short term fix is to comment out the lines:
```
if write_submit_script is None:
        write_submit_script = prisms_jobs.config['write_submit_script']
```
in `prisms_jobs/interface/slurm.py` and `prisms_jobs/interface/torque.py`
