### ISSUE TITLE
Issue with --checkhull

### ISSUE THREAD

**Issue by rashidrafeek** [prisms-center/CASMcode#146]
I am new to CASM and had the following error while running casm-learn --checkhull.

*************************************************************************************************
Error in casm.query
  proj: /home/guest/Rashid/casm/Cmcm_t
  Attempted to execute: 'query -k 'clex_hull_dist(ALL,atom_frac) clex(formation_energy) clex_hull_dist(/home/guest/Rashid/casm/Cmcm_t/.casm/tmp/ALL_dft_hull,atom_frac) ' -c ALL -v -o STDOUT'
---- stdout: ---------------------
#
---- stderr: ---------------------
Print:
   - clex_hull_dist(ALL,atom_frac) clex(formation_energy) clex_hull_dist(/home/guest/Rashid/casm/Cmcm_t/.casm/tmp/ALL_dft_hull,atom_frac) 
to "STDOUT"

Initialization error: QH6214 qhull input error: not enough points(2) to construct initial simplex (need 3)

While executing:  | qhull 
Options selected for Qhull 2015.0.6.r 2015/10/20:
  run-id 290444180  _pre-merge  _zero-centrum
***************************************************************************************************

The Complete output I got is given below:

**************************************************************************************************
Loading fit_1_ga.json
Loading Hall of Fame: fit_1_ga_halloffame.pkl
Get problem data...
Reading existing problem specs from: fit_1_ga_specs.pkl
 DONE

-- Construct: CASM Project -- 
from: "/home/guest/Rashid/casm/Cmcm_t"

-- Load project data -- 
read: "/home/guest/Rashid/casm/Cmcm_t/.casm/composition_axes.json"
read: "/home/guest/Rashid/casm/Cmcm_t/training_data/settings/calctype.default/ref.default/chemical_reference.json"
read: "/home/guest/Rashid/casm/Cmcm_t/training_data/SCEL"
read: "/home/guest/Rashid/casm/Cmcm_t/.casm/config_list.json"

check: individual 0  
index: Selected       #Selected    CV           RMS          wRMS         Estimator                FeatureSelection         Note
---------------------------------------------------------------------------------------------------------------------------------------
    0: 01100101001000 5            0.084054785  0.071043132  0.071043132  LinearRegression         GeneticAlgorithm         

Writing: /home/guest/Rashid/casm/Cmcm_t/cluster_expansions/clex.formation_energy/calctype.default/ref.default/bset.default/eci.__tmp/eci.json 

-- Load project data -- 
refresh cluster expansions

Error in casm.query
  proj: /home/guest/Rashid/casm/Cmcm_t
  Attempted to execute: 'query -k 'clex_hull_dist(ALL,atom_frac) clex(formation_energy) clex_hull_dist(/home/guest/Rashid/casm/Cmcm_t/.casm/tmp/ALL_dft_hull,atom_frac) ' -c ALL -v -o STDOUT'
---- stdout: ---------------------
#
---- stderr: ---------------------
Print:
   - clex_hull_dist(ALL,atom_frac) clex(formation_energy) clex_hull_dist(/home/guest/Rashid/casm/Cmcm_t/.casm/tmp/ALL_dft_hull,atom_frac) 
to "STDOUT"

Initialization error: QH6214 qhull input error: not enough points(2) to construct initial simplex (need 3)

While executing:  | qhull 
Options selected for Qhull 2015.0.6.r 2015/10/20:
  run-id 290444180  _pre-merge  _zero-centrum

----------------------------------
Traceback (most recent call last):
  File "/home/guest/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 2510, in _infer_columns
    line = self._buffered_line()
  File "/home/guest/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 2689, in _buffered_line
    return self._next_line()
  File "/home/guest/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 2794, in _next_line
    orig_line = self._next_iter_line(row_num=self.pos + 1)
  File "/home/guest/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 2854, in _next_iter_line
    return next(self.data)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guest/anaconda3/bin/casm-learn", line 12, in <module>
    sys.exit(main())
  File "/home/guest/anaconda3/lib/python3.6/site-packages/casm/scripts/casm_learn.py", line 91, in main
    casm.learn.fit.checkhull(input, existing_hall, indices=args.indiv, verbose=args.verbose)
  File "/home/guest/anaconda3/lib/python3.6/site-packages/casm/learn/fit.py", line 2075, in checkhull
    sel.query([clex_hull_dist_long, clex_Eform, clex_dft_hull_dist_long], force=True)
  File "/home/guest/anaconda3/lib/python3.6/site-packages/casm/project/selection.py", line 234, in query
    df = query(self.proj, _col, self, all=self.all)
  File "/home/guest/anaconda3/lib/python3.6/site-packages/casm/project/query.py", line 38, in query
    return pandas.read_csv(sout, sep=compat.str(' +'), engine='python')
  File "/home/guest/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/guest/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/guest/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/guest/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1132, in _make_engine
    self._engine = klass(self.f, **self.options)
  File "/home/guest/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 2238, in __init__
    self.unnamed_cols) = self._infer_columns()
  File "/home/guest/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 2532, in _infer_columns
    "No columns to parse from file")
pandas.errors.EmptyDataError: No columns to parse from file
**************************************************************************************************

Any help regarding this is appreaciated.
Thank you.

**Comment by jcthomas** [comment]
It appears that casm is detecting a 2-dimensional composition space (e.g., an alloy with two composition variables, like Cu(x)Au(y)Pt(1-x-y) ), while your dataset only spans a one-dimensional composition space.  In general, casm will detect such a situation and behave appropriately. This behavior is determined by the `"dim_tol"` parameter, within the `"checkhull"` entry of your casm-learn settings file (which appears to be `fit_1_ga.json`).

You can try to edit the `"checkhull"` setting within `fit_1_ga.json`. The default settings are
````
    "checkhull" : {                                                                                                                                                                
      "selection": "ALL",                                                                                                                                                          
      "write_results": true,                                                                                                                                                       
      "primitive_only": true,                                                                                                                                                      
      "uncalculated_range": 1e-8,                                                                                                                                                  
      "ranged_rms": [0.001, 0.005, 0.01, 0.05, 0.1, 0.5],                                                                                                                          
      "composition": "atom_frac",                                                                                                                                                  
      "hull_tol": 1e-8,                                                                                                                                                            
      "dim_tol": 1e-8,                                                                                                                                                             
      "bottom_tol": 1e-8                                                                                                                                                           
    }
````
The parameter `"dim_tol"` can be increased up to 1e-3 in most cases without any ill effects. I would recommend first trying a value around 1e-5 and seeing if this resolves the issue.

It's uncommon that the results of `casm-learn --checkhull` would be sensitive to tolerance issues.  If you could share a bit more about your project, that would be helpful.  In particular, the `prim.json` file, and the output of `casm query -k comp atom_frac formation_energy -c CALCULATED` would help me determine if something more serious is going on.

**Comment by rashidrafeek** [comment]
Thanks for the reply.
I edited the settings file as you said without any change in the output. 

The system I am working on is MgV2O5. I have attached the files you requested.
prim.json:
[prim.json.txt](https://github.com/prisms-center/CASMcode/files/2987036/prim.json.txt)
Output of `casm query -k comp atom_frac formation_energy -c CALCULATED`
[output.txt](https://github.com/prisms-center/CASMcode/files/2987039/output.txt)

**Comment by jcthomas** [comment]
It appears that all of the formation energies are above the common tangent formed by the composition endpoints (MgV2O5 and V2O5). This suggests the system exhibits a miscibility gap.

During the course of the checkhull procedure, casm (i) identifies the DFT groundstates (i.e., MgV2O5 and V2O5 in this case) and then (ii) finds the convex hull of these points in terms of the CE-predicted energies.

Once this convex hull is found, casm determines whether the CE-predicted hull of these points is (a) actually convex and (b) is lower in energy than the CE-predicted energies of all other configurations in your project.  

The failure is happening at step (ii) above, where Qhull (via casm) attempts to find a convex hull of two points in two dimensions. By Qhull's criteria, there is no valid convex hull in this situation (a line segment in 2D is not strictly convex), and so it fails. 

I will push a fix that bypasses Qhull if this type of scenario is encountered and note it here once it's ready. In the meantime, you can run without the `--checkhull` option in this project. Because the system exhibits a miscibility gap, you can simply check whether any configurations have `clex(formation_energy)` less than zero to determine if new groundstates are predicted.

**Comment by rashidrafeek** [comment]
Really thankful for the detailed explanation. It helped me understand a lot. I will continue my work without the `--checkhull` option.
