### ISSUE TITLE
supercell enumeration error

### ISSUE THREAD

**Issue by shaliu19900911** [prisms-center/CASMcode#148]
Dear developer,

I use the following prim.json file to enumerate supercells and configurations.

   {
  "basis" : [
    {
      "coordinate" : [ 0.658980114000, 0.500000004000, 0.182039872000 ],
      "occupant_dof" : [ "Al" ]
    },
    {
      "coordinate" : [ 0.158980117000, 0.182039840000, 0.500000002000 ],
      "occupant_dof" : [ "Al" ]
    },
    {
      "coordinate" : [ 0.841019883000, 0.817960160000, 0.499999998000 ],
      "occupant_dof" : [ "Al" ]
    },
    {
      "coordinate" : [ 0.341019886000, 0.499999996000, 0.817960128000 ],
      "occupant_dof" : [ "Al" ]
    },
    {
      "coordinate" : [ 0.250000024000, -0.000000070000, 0.000000042000 ],
      "occupant_dof" : [ "Va", "Cu" ]
    },
    {
      "coordinate" : [ 0.749999976000, 0.000000070000, -0.000000042000 ],
      "occupant_dof" : [ "Va", "Cu" ]
    }
  ],
  "coordinate_mode" : "Fractional",
  "description" : "equilibrium theta",
  "lattice_vectors" : [
    [ 2.351281455149, 4.195505447026, -0.000000034926 ],
    [ 1.175640715403, 2.097752700494, 4.243512524782 ],
    [ 4.877454239630, 0.023149962543, -0.000000016934 ]
  ],
  "title" : "theta"
}

**When the max size of supercell is 3, everything is OK. But when I set the max size as 4, the following error happened. Could you please tell me what's wrong with my project? Because of this error, I can not enumerate configurations.** 

-- Construct: CASM Project -- 
from: "/home/shaliu/Downloads/CASM_WORK/theta4"

-- Load project data -- 
read: "/home/shaliu/Downloads/CASM_WORK/theta4/.casm/composition_axes.json"
read: "/home/shaliu/Downloads/CASM_WORK/theta4/training_data/settings/calctype.default/ref.default/chemical_reference.json"

-- Begin: ScelEnum -- 
  Generated: SCEL1_1_1_1_0_0_0
  Generated: SCEL2_2_1_1_0_0_0
  Generated: SCEL2_1_2_1_0_0_0
  Generated: SCEL2_1_2_1_1_0_0
  Generated: SCEL3_3_1_1_0_0_0
  Generated: SCEL3_3_1_1_0_2_1
  Generated: SCEL3_3_1_1_0_1_1
  Generated: SCEL3_1_3_1_0_0_0
  Generated: SCEL3_1_3_1_2_0_0
  Generated: SCEL4_4_1_1_0_3_3
  Generated: SCEL4_4_1_1_0_2_0
  Generated: SCEL4_4_1_1_0_1_1
  Generated: SCEL4_2_2_1_0_0_0
  Generated: SCEL4_2_2_1_0_0_1
  Generated: SCEL4_2_2_1_1_1_0
  Generated: SCEL4_2_2_1_1_0_1
  Generated: SCEL4_2_2_1_1_1_1
ERROR in PrimClex::add_canonical_supercell().
  Passed a Supercell Lattice that is not a superlattice of PRIM lattice

**Comment by jcthomas** [comment]
I believe this is a tolerance issue. The D4h point-group symmetry of the crystal determined by casm is only respected to within about 5e-6 Angstr, which is just below the default tolerance of 1e-5. Because supercells are formed from integer multiples of the primitive lattice vectors, any numerical noise in the primitive cell lattice vectors is inflated for the supercell lattice vectors.

I would suggest trying again with these lattice vectors for prim.json:
````
[
    [ 2.371168258975154,   4.184298211765166,                   0.0],
    [1.185584129487576,   2.092149105882580,   4.243512612803903],
    [4.877509293108925,                   0.0                   0.0]
]
````

You may also consider cleaning up the basis atom positions for values that are close to simple integer ratios (e.g., 0.4999999 to 0.5, 0.749999979 to 0.75)
