### ISSUE TITLE
Error: Calculating low temperature expansion

### ISSUE THREAD

**Issue by shaliu19900911** [prisms-center/CASMcode#149]
Dear developer,

I enumerate about 600 configurations. After I finished about 200 DFT calculations, I fit a cluster expansion. The CV score is about 5% and the ground state configurations are there correctly. I use the CE to run LTE-MC, and the result is as follow. It seems the LTE formation energy is correct. 
![gs_formation_energy](https://user-images.githubusercontent.com/46279371/56494162-aa62ac00-64f1-11e9-8142-8a4025494afe.png)

Then I finished all of the 600 configurations and I fit a cluster expansion with CV score about 3.4%. The fitting is much better than before. It is shown as below:

![convex_hull](https://user-images.githubusercontent.com/46279371/56494367-4a203a00-64f2-11e9-84ac-43228b88c795.png)
But when I use this CE to run LTE-MC, it said"
-- Error: Calculating low temperature expansion -- 
  Defect lowered the potential energy. Your motif configuration is not the 0K ground state.

ERROR calculating single spin flip LTE grand canonical potential.

Error calculating low temperature expansion. Not in the ground state." when chemical potential reaches -0.71. The result is as follow. I want to know why the other ground state structures are missing? Is my CE over fitting?
![gs_formation_energy](https://user-images.githubusercontent.com/46279371/56494345-34127980-64f2-11e9-9bb8-d8fe45392181.png)
Regards

**Comment by bpuchala** [comment]
This is indicating that the cluster expansion is predicting low energy structures that are not among the configurations you have already enumerated. It would be useful to enumerate additional configurations and check the predicted hull with them included. It will then likely be desirable to calculate at least those additional configurations that are predicted to be ground states. 

Another strategy is to perform Monte Carlo calculations with your imperfect cluster expansion in a simulated annealing mode (start at high temperature, end at low temperature, repeat over the range of chemical potentials of interest) to identify predicted ground states that should be included in the fit. CASM can optionally save configurations encountered during Monte Carlo in your configuration database (see the "casm format --monte" input file help for the "enumeration" setting).

**Comment by shaliu19900911** [comment]
Yes, I tried this way. I used two kinds of CE fitted from 200 configuration and from 600 configurations. The annealing simulations are similar, at each condition higher than 200K, a lot of new configurations are enumerated and saved in the config.json file. But at 200K, there is no new configurations. Did I do that correctly?  

-- Write: Enumerated configurations to master config list -- 
configuration enumeration check: eq(1,1)
configuration enumeration metric: clex_hull_dist(ALL)
#                  configname    is_primitive    is_new          score           comp(a)    potential_energy
    SCEL1000_10_10_10_0_0_0/0               1         1    -0.00274865        0.55100000         -0.09930695
    SCEL1000_10_10_10_0_0_0/1               1         1    -0.00270553        0.55250000         -0.09850234
    SCEL1000_10_10_10_0_0_0/2               1         1    -0.00270526        0.55050000         -0.09939599
    SCEL1000_10_10_10_0_0_0/3               1         1    -0.00267891        0.55200000         -0.09864332
    SCEL1000_10_10_10_0_0_0/4               1         1    -0.00264139        0.55300000         -0.09807951
    SCEL1000_10_10_10_0_0_0/5               1         1    -0.00263522        0.55400000         -0.09761295
    SCEL1000_10_10_10_0_0_0/6               1         1    -0.00262644        0.55600000         -0.09669090
    SCEL1000_10_10_10_0_0_0/7               1         1    -0.00262136        0.55000000         -0.09935952
    SCEL1000_10_10_10_0_0_0/8               1         1    -0.00259820        0.54750000         -0.10040632
    SCEL1000_10_10_10_0_0_0/9               1         1    -0.00259470        0.55400000         -0.09748702
    SCEL1000_10_10_10_0_0_0/10              1         1    -0.00256893        0.55100000         -0.09874947
    SCEL1000_10_10_10_0_0_0/11              1         1    -0.00255439        0.54800000         -0.10004698
    SCEL1000_10_10_10_0_0_0/12              1         1    -0.00254556        0.55350000         -0.09755809
    SCEL1000_10_10_10_0_0_0/13              1         1    -0.00253670        0.55050000         -0.09887326
    SCEL1000_10_10_10_0_0_0/14              1         1    -0.00253110        0.55000000         -0.09907970
    SCEL1000_10_10_10_0_0_0/15              1         1    -0.00252698        0.55150000         -0.09839554
    SCEL1000_10_10_10_0_0_0/16              1         1    -0.00251333        0.54550000         -0.10103890
    SCEL1000_10_10_10_0_0_0/17              1         1    -0.00247552        0.54550000         -0.10092202
    SCEL1000_10_10_10_0_0_0/18              1         1    -0.00247294        0.54500000         -0.10113790
    SCEL1000_10_10_10_0_0_0/19              1         1    -0.00246467        0.54950000         -0.09909762
    SCEL1000_10_10_10_0_0_0/20              1         1    -0.00245913        0.54950000         -0.09908047
    SCEL1000_10_10_10_0_0_0/21              1         1    -0.00245848        0.55100000         -0.09840685
    SCEL1000_10_10_10_0_0_0/22              1         1    -0.00245710        0.56000000         -0.09437297
    SCEL1000_10_10_10_0_0_0/23              1         1    -0.00245671        0.55050000         -0.09862522
    SCEL1000_10_10_10_0_0_0/24              1         1    -0.00245528        0.55350000         -0.09727758
    SCEL1000_10_10_10_0_0_0/25              1         1    -0.00244256        0.55150000         -0.09813359
    SCEL1000_10_10_10_0_0_0/26              1         1    -0.00243486        0.55000000         -0.09878136
    SCEL1000_10_10_10_0_0_0/27              1         1    -0.00243109        0.54850000         -0.09944136
    SCEL1000_10_10_10_0_0_0/28              1         1    -0.00242641        0.55300000         -0.09741178
    SCEL1000_10_10_10_0_0_0/29              1         1    -0.00242316        0.55050000         -0.09852118
    SCEL1000_10_10_10_0_0_0/30              1         1    -0.00242138        0.54900000         -0.09918737
    SCEL1000_10_10_10_0_0_0/31              1         1    -0.00241572        0.55300000         -0.09737859
    SCEL1000_10_10_10_0_0_0/32              1         1    -0.00241552        0.55100000         -0.09827357
    SCEL1000_10_10_10_0_0_0/33              1         1    -0.00241483        0.54900000         -0.09916708
    SCEL1000_10_10_10_0_0_0/34              1         1    -0.00240635        0.55500000         -0.09645381
    SCEL1000_10_10_10_0_0_0/35              1         1    -0.00240359        0.54550000         -0.10069969
    SCEL1000_10_10_10_0_0_0/36              1         1    -0.00240325        0.54550000         -0.10069865
    SCEL1000_10_10_10_0_0_0/37              1         1    -0.00240313        0.55000000         -0.09868300
    SCEL1000_10_10_10_0_0_0/38              1         1    -0.00240296        0.54550000         -0.10069776
    SCEL1000_10_10_10_0_0_0/39              1         1    -0.00239930        0.54800000         -0.09956680
    SCEL1000_10_10_10_0_0_0/40              1         1    -0.00239791        0.54750000         -0.09978643
    SCEL1000_10_10_10_0_0_0/41              1         1    -0.00239290        0.54600000         -0.10044272
    SCEL1000_10_10_10_0_0_0/42              1         1    -0.00239007        0.55450000         -0.09662711
    SCEL1000_10_10_10_0_0_0/43              1         1    -0.00238986        0.55050000         -0.09841791
    SCEL1000_10_10_10_0_0_0/44              1         1    -0.00238824        0.55250000         -0.09751714
    SCEL1000_10_10_10_0_0_0/45              1         1    -0.00237768        0.55150000         -0.09793226
    SCEL1000_10_10_10_0_0_0/46              1         1    -0.00237643        0.55350000         -0.09703258
    SCEL1000_10_10_10_0_0_0/47              1         1    -0.00237479        0.55300000         -0.09725144
    SCEL1000_10_10_10_0_0_0/48              1         1    -0.00237432        0.55000000         -0.09859369
    SCEL1000_10_10_10_0_0_0/49              1         1    -0.00237286        0.54550000         -0.10060472
    SCEL1000_10_10_10_0_0_0/50              1         1    -0.00237231        0.54800000         -0.09948325
    SCEL1000_10_10_10_0_0_0/51              1         1    -0.00236937        0.54950000         -0.09880228
    SCEL1000_10_10_10_0_0_0/52              1         1    -0.00236328        0.55050000         -0.09833550
    SCEL1000_10_10_10_0_0_0/53              1         1    -0.00236071        0.54750000         -0.09967130
    SCEL1000_10_10_10_0_0_0/54              1         1    -0.00235811        0.54950000         -0.09876741
    SCEL1000_10_10_10_0_0_0/55              1         1    -0.00235726        0.55100000         -0.09809285
    SCEL1000_10_10_10_0_0_0/56              1         1    -0.00235548        0.54550000         -0.10055098
    SCEL1000_10_10_10_0_0_0/57              1         1    -0.00235300        0.54700000         -0.09987142
    SCEL1000_10_10_10_0_0_0/58              1         1    -0.00234852        0.54700000         -0.09985755
    SCEL1000_10_10_10_0_0_0/59              1         1    -0.00234603        0.54700000         -0.09984985
    SCEL1000_10_10_10_0_0_0/60              1         1    -0.00234206        0.54750000         -0.09961359
    SCEL1000_10_10_10_0_0_0/61              1         1    -0.00233884        0.55050000         -0.09825970
    SCEL1000_10_10_10_0_0_0/62              1         1    -0.00233853        0.55650000         -0.09557093
    SCEL1000_10_10_10_0_0_0/63              1         1    -0.00233804        0.55300000         -0.09713731
    SCEL1000_10_10_10_0_0_0/64              1         1    -0.00233792        0.55150000         -0.09780889
    SCEL1000_10_10_10_0_0_0/65              1         1    -0.00233559        0.55550000         -0.09600975
    SCEL1000_10_10_10_0_0_0/66              1         1    -0.00233521        0.54700000         -0.09981639
    SCEL1000_10_10_10_0_0_0/67              1         1    -0.00233255        0.54850000         -0.09913616
    SCEL1000_10_10_10_0_0_0/68              1         1    -0.00232786        0.54800000         -0.09934564
    SCEL1000_10_10_10_0_0_0/69              1         1    -0.00232367        0.54550000         -0.10045266
    SCEL1000_10_10_10_0_0_0/70              1         1    -0.00231902        0.55400000         -0.09663022
    SCEL1000_10_10_10_0_0_0/71              1         1    -0.00231633        0.54400000         -0.10110200
    SCEL1000_10_10_10_0_0_0/72              1         1    -0.00231477        0.55150000         -0.09773705
    SCEL1000_10_10_10_0_0_0/73              1         1    -0.00231245        0.55000000         -0.09840188
    SCEL1000_10_10_10_0_0_0/74              1         1    -0.00230892        0.54750000         -0.09951102
    SCEL1000_10_10_10_0_0_0/75              1         1    -0.00230825        0.54700000         -0.09973296
    SCEL1000_10_10_10_0_0_0/76              1         1    -0.00230776        0.55400000         -0.09659522
    SCEL1000_10_10_10_0_0_0/77              1         1    -0.00230774        0.54900000         -0.09883531
    SCEL1000_10_10_10_0_0_0/78              1         1    -0.00230605        0.55050000         -0.09815802
    SCEL1000_10_10_10_0_0_0/79              1         1    -0.00230028        0.55250000         -0.09724405
    SCEL1000_10_10_10_0_0_0/80              1         1    -0.00229843        0.54700000         -0.09970257
    SCEL1000_10_10_10_0_0_0/81              1         1    -0.00229836        0.54750000         -0.09947832
    SCEL1000_10_10_10_0_0_0/82              1         1    -0.00229604        0.54900000         -0.09879908
    SCEL1000_10_10_10_0_0_0/83              1         1    -0.00229437        0.54700000         -0.09969001
    SCEL1000_10_10_10_0_0_0/84              1         1    -0.00229403        0.55400000         -0.09655254
    SCEL1000_10_10_10_0_0_0/85              1         1    -0.00229365        0.55300000         -0.09699942
    SCEL1000_10_10_10_0_0_0/86              1         1    -0.00229197        0.55050000         -0.09811437
    SCEL1000_10_10_10_0_0_0/87              1         1    -0.00228953        0.54850000         -0.09900292
    SCEL1000_10_10_10_0_0_0/88              1         1    -0.00228947        0.54950000         -0.09855469
    SCEL1000_10_10_10_0_0_0/89              1         1    -0.00228646        0.54650000         -0.09988957
    SCEL1000_10_10_10_0_0_0/90              1         1    -0.00228635        0.55250000         -0.09720078
    SCEL1000_10_10_10_0_0_0/91              1         1    -0.00228079        0.54900000         -0.09875182
    SCEL1000_10_10_10_0_0_0/92              1         1    -0.00228074        0.54800000         -0.09919974
    SCEL1000_10_10_10_0_0_0/93              1         1    -0.00227398        0.54750000         -0.09940288
    SCEL1000_10_10_10_0_0_0/94              1         1    -0.00227231        0.55050000         -0.09805338
    SCEL1000_10_10_10_0_0_0/95              1         1    -0.00227118        0.54750000         -0.09939420
    SCEL1000_10_10_10_0_0_0/96              1         1    -0.00227044        0.54800000         -0.09916787
    SCEL1000_10_10_10_0_0_0/97              1         1    -0.00226904        0.54650000         -0.09983570
    SCEL1000_10_10_10_0_0_0/98              1         1    -0.00226648        0.55250000         -0.09713911
    SCEL1000_10_10_10_0_0_0/99              1         1    -0.00226598        0.55600000         -0.09556914

**Comment by bpuchala** [comment]
The idea is you want to try to find the configurations, and particularly the small supercell configurations, that are predicted by the cluster expansion to be lower than the convex hull generated from the configurations you have already enumerated. Once you find them, either by direct enumeration and checking (via casm query for clex_hull_dist, or casm learn --checkhull), or via enumeration with monte carlo, you can:
- inspect them (for instance with "casm view" or "casm query --write-pos" to see the POSCAR) and try to understand the ordering that is predicted to be low energy
- calculate DFT energies to check if they actually are ground states
- fit a new cluster expansion including the new calculations and does not have include spurious ground state predictions

These results show you did monte carlo and encountered configurations that were predicted to be below the convex hull generated from the configurations previously in your config list (because "score=clex_hull_dist(ALL) is negative), but the problem is they are in pretty large supercells so they will be slow to calculate. Still, you can inspect them to see what kind of ordering or defects are being predicted to be lower energy than what you had previously enumerated.

**Comment by shaliu19900911** [comment]
Thanks, I finally know now. It seems the new large configurations are too many that my VESTA can not open the config.json file. I will try to enlarge the increment to make the number of  new configurations less.
