### ISSUE TITLE
Error generating sublat index

### ISSUE THREAD

**Issue by vishnusudarsanv** [prisms-center/CASMcode#154]
Dear Developers,
When I am doing "casm bset -u", I am getting this error.

write: "/home/vishnu/Documents/nms/casm/basis_sets/bset.default/clust.json"
write: "/home/vishnu/Documents/nms/casm/basis_sets/bset.default/basis.json"
Error generating sublat index
  Did not find sublat: 7 in the nlist sublattice indices: [ ]

I am attaching my prim.json and bspecs.json files for your inspection.
Thanks in advance.

[prim.json.txt](https://github.com/prisms-center/CASMcode/files/3258361/prim.json.txt)
[bspecs.json.txt](https://github.com/prisms-center/CASMcode/files/3258365/bspecs.json.txt)

**Comment by bpuchala** [comment]
I couldn't reproduce this error starting from a new project.

One possible cause of a problem is if there was an existing ```.casm``` directory or contents from a different prim that is conflicting and causing a problem. Try starting a new project in a new directory and see if it works.  If it doesn't, please write out the steps you perform exactly for a new project and which version of CASM you are using.

One other thing to note is that CASM generates cluster in each branch (points, pairs, triplets, etc.) using the results of the previous branch and then adding single new sites. In your bspecs.json you have a smaller cutoff for triplets than quadruplets, which means you will not be generating all possible quadruplets with the cutoff size you set.

**Comment by jcthomas** [comment]
I couldn't reproduce the issue either. 

This error also may have occurred if you edited prim.json after initializing the project (e.g., by changing "Na" sites to "Na"/"Va" sites). Once a project is initialized, prim.json should not be altered.

**Comment by vishnusudarsanv** [comment]
Yes, Starting a new project worked. I think the problem arose when I copied a project started using an older version of casm and continued in a newer version of casm. 
I made changes in bspecs.json as you suggested.

Thank you very much for helping me.
