### ISSUE TITLE
[] added to RWIGS flag in INCAR creating error

### ISSUE THREAD

**Issue by jjcordell** [prisms-center/CASMcode#155]
When using `casm-calc --setup`, the INCAR file from `.../training_data/settings/calctype.default/` is copied to the respective training SCELs identically except in the case of the `RWIGS` flag which gets additional brackets (i.e. `RWIGS = 1.0 1.0 1.0 1.0` becomes `RWIGS = [1.0 1.0 1.0 1.0]` which is not readable by VASP). This creates a VASP error crashing the calculation. This was not an issue in CASM 0.2.X. A temporary solution is to comment out the flag if unnecessary or delete the brackets manually, but this is not ideal.

Thanks for the help and putting this software together!

**Comment by bpuchala** [comment]
Thanks for raising the issue. I believe this is addressed by #153, which has been merged into 0.3.X. A travis change has broken our testing & conda packaging, so a new conda package with the fix hasn't been pushed out yet. I'm working on a fix for that.

**Comment by jjcordell** [comment]
Didn't realize the issue was known, thanks!
