### ISSUE TITLE
LTE ignore some ground state structure

### ISSUE THREAD

**Issue by shaliu19900911** [prisms-center/CASMcode#156]
With my fitted cluster expansion, as below, I should get gs_structures at comp(a)=0, 0.25, 0.33, 0.5, 0.66 and 1. But during LTE, it always transforms from comp(a)=0 to comp(a)=0.5 directly. And then to comp(a)=0.75. I don't know why. I even enumerated more configurations, as the second picture, and they are above the convex hull. But the transition is still from comp(a)=0 to comp(a)=0.5 directly.

![convex_hull](https://user-images.githubusercontent.com/46279371/59769679-ed998b00-92a6-11e9-9774-aa1582acbac2.png)
![sss](https://user-images.githubusercontent.com/46279371/59769809-29345500-92a7-11e9-9cbd-b0851c9dddfc.png)

**Comment by shaliu19900911** [comment]
I think this problem is the '"supercell" parameter in monte carlo input file. I changed it and get different ground state structures.

**Comment by bpuchala** [comment]
If you want to use a single supercell to calculate the reference energy for every hull configuration, then you need a supercell which is a supercell of all the hull configurations. We have taken to calling this supercell the "super duper" cell. The `casm super` command with the  `--duper` option can take a list of supercells and configurations and determine the minimum volume supercell which is a "super duper" cell of all the input supercells and configurations.

**Comment by bpuchala** [comment]
I should note that the `casm super` command has a number of other options to control the output, and in particular the following might be useful for you:

- the `--min-volume` option can be used to ensure the output supercell is also at least some user-specified volume
- the `--fixed-shape` option can be used to enforce increasing the volume of a supercell without changing it's shape
