### ISSUE TITLE
Configuration enumeration error

### ISSUE THREAD

**Issue by zhdeng94** [prisms-center/CASMcode#157]
Hi, I was trying to follow the ZrO tutorial, and I found that casm didn't write each configuration that has been enumerated into the supercell directory. For example, I get the following message after doing the enumeration. However, when I looked at the SCEL1_1_1_1_0_0_0 directory, only LAT file existed. I encounter this error both in my local computer and the supercomputer. I wonder if you could let me know what the issue is. Thanks!

======================= Error message

(casm) Karpathos:test zhdeng$ casm enum --method ConfigEnumAllOccupations --all
-- Construct: CASM Project -- 
from: "/Users/zhdeng/Desktop/CASMcode_v0.2.1_demo/test"

-- Load project data -- 
read: "/Users/zhdeng/Desktop/CASMcode_v0.2.1_demo/test/.casm/composition_axes.json"
read: "/Users/zhdeng/Desktop/CASMcode_v0.2.1_demo/test/training_data/SCEL"
read: "/Users/zhdeng/Desktop/CASMcode_v0.2.1_demo/test/.casm/config_list.json"

configurations in this project: 0

-- Begin: ConfigEnumAllOccupations -- 
Enumerate configurations for SCEL1_1_1_1_0_0_0 ...  3 configs.
Enumerate configurations for SCEL2_1_2_1_0_0_0 ...  4 configs.
Enumerate configurations for SCEL2_1_2_1_1_0_0 ...  3 configs.
Enumerate configurations for SCEL2_1_1_2_0_0_0 ...  3 configs.
Enumerate configurations for SCEL3_3_1_1_0_0_1 ...  10 configs.
Enumerate configurations for SCEL3_3_1_1_0_0_2 ...  10 configs.
Enumerate configurations for SCEL3_1_3_1_2_0_0 ...  16 configs.
Enumerate configurations for SCEL3_3_1_1_0_2_2 ...  10 configs.
Enumerate configurations for SCEL3_1_1_3_0_0_0 ...  10 configs.
Enumerate configurations for SCEL4_1_4_1_0_0_0 ...  27 configs.
Enumerate configurations for SCEL4_2_2_1_0_0_1 ...  27 configs.
Enumerate configurations for SCEL4_1_4_1_1_0_0 ...  42 configs.
Enumerate configurations for SCEL4_4_1_1_0_3_2 ...  24 configs.
Enumerate configurations for SCEL4_1_4_1_2_0_0 ...  24 configs.
Enumerate configurations for SCEL4_2_2_1_0_1_1 ...  21 configs.
Enumerate configurations for SCEL4_2_2_1_0_0_0 ...  15 configs.
Enumerate configurations for SCEL4_2_2_1_0_1_0 ...  18 configs.
Enumerate configurations for SCEL4_1_2_2_0_0_0 ...  21 configs.
Enumerate configurations for SCEL4_1_2_2_1_0_0 ...  24 configs.
Enumerate configurations for SCEL4_1_1_4_0_0_0 ...  24 configs.
  DONE.

new configurations: 336
configurations in this project: 336

Write SCEL...
  DONE

Writing config_list...
  DONE

**Comment by Yangxinsix** [comment]
You should setup the INPUT files for DFT calculations first.

**Comment by bpuchala** [comment]
The configurations are initially stored in a `config_list.json` file inside the `.casm` directory and not written to the `training_data` directory. You can get information about the ones you have enumerated via `casm query`. One option is `casm query --write-pos` which will write the configuration as a POSCAR-like file in the appropriate `training_data` directory.
