### ISSUE TITLE
How to set a chemical reference for a convex hull with unequal formation energies of extreme stoichiometries?

### ISSUE THREAD

**Issue by Yangxinsix** [prisms-center/CASMcode#158]
Dear developers, thanks for your code and kindly help.

I'm on my way to construct a formation energy convex hull for a given compound Na(2-2x)Li(2x)W4O13. I want to see at which composition the insertion of Li is energetically favorable so I need the convex hull with the formation energy of  extreme stoichiometries unequal to zero. Is there any direct way in the code for me to construct a convex hull like below?

![image](https://user-images.githubusercontent.com/29850829/60148877-4f0cad00-9805-11e9-9f9e-7270b0fa988a.png)

Appreciate for your attention.

**Comment by deRheart** [comment]
you can set the chemical reference  by the file 'chemical_reference.json'.  The json file  
is in the  'Pro.path/training_data/settings/calctype.default/ref.default/' folder.   You can get more information use the command 'casm ref --desc'.

**Comment by bpuchala** [comment]
The chemical reference is set in the `chemical_reference.json` file as noted by @deRheart. It should be possible to set it as you wish using the options in `casm ref` instead of editing the file directly. There are options to set the reference by choosing a set of configurations you wish to use as the reference or by setting the energy values explicitly.

**Comment by jcthomas** [comment]
An easier and safer way to set the reference is via the `casm ref` command. For example
````
casm ref --set '[{"Na": 0, "Li": 2, "W": 4, "O": 13, "energy_per_species": -5.809},
                 {"Na": 2, "Li": 0, "W": 4, "O": 13, "energy_per_species": -4.203}]'
````
Each item in the list corresponds to a single reference compound.
