### ISSUE TITLE
casm-learn usage for "pop_begin_filename" tag

### ISSUE THREAD

**Issue by sriharsha09** [prisms-center/CASMcode#16]
I assume we can use  "pop_begin_filename" tag to give a starting guess for genetic algorithm. Presently it takes only pickle files. How to make a pickle file of a bit string of my initial guess? Also what is the population being written to "fileprefix_population_end.pkl"? If I want a certain hall of fame candidate as starting guess for the genetic algo, what is the way to do that?

**Comment by bpuchala** [comment]
The casm-learn GeneticAlgorithm implements eaSimple from deap. Take a look at the documentation [here](http://deap.readthedocs.io/en/master/api/algo.html) for more understanding of how that algorithm goes. The GeneticAlgorithm runs for "n_generation" generations and then writes  "fileprefix_population_end.pkl" with the final population. This is repeated "n_repitition" times. The interface is currently intended to enable restarts. So you can `cp fileprefix_population_end.pkl fileprefix_population_begin.pkl` and then execute `casm-learn` again to restart the genetic algorithm using that population.

There is currently not an interface through `casm-learn` to specify a custom population, but you can do it using the `casm.learn` Python module, specifically the `make_population` and `save_population` functions.

Here is an example Python script to create a population file:
```
import casm.learn
from casm.learn.fit import make_fitting_data
from casm.learn.direct_selection import make_population
from casm.learn.evolve import save_population

input = casm.learn.open_input("fileprefix.json")
fdata = make_fitting_data(input)

# specify options for how to construct the population
# this is the same as the options for DirectSelection
# which you can see from casm-learn --settings-format
pop_options = [
  {"bitstring":"11100010"},
  {"indices":[0,1,2,6]},
  {"from_halloffame": "fileprefix_halloffame.pkl", "individuals":[0,1,2]}
]
pop = make_population(fdata.n_features, pop_options)
save_population(pop, "fileprefix_population_begin.pkl")
```

I seem to be having some issue that prevents using "pop_begin_filename" in the `casm-learn` input file to specify a custom population filename. I'm looking into it, but using "fileprefix_population_begin.pkl" is working.

**Comment by sriharsha09** [comment]
Thank Brain. I will give it a try tomorrow. regarding the issue with issue the pop_begin_filename. I lloked into it and it seems the code is adding the file_prefix when it searches for the file.
changing **line 367 in evolve .py** fixed it.

old:    self.pop_begin_filename = filename_prefix + pop_begin_filename
fix :    self.pop_begin_filename = pop_begin_filename

**Comment by bpuchala** [comment]
Ah, right. So without a change you should be able to do
```
save_population(pop,"fileprefex_custom_population.pkl")
```
and then in the input file set
```
"pop_begin_filename": "custom_population.pkl"
```

Not sure that's the best way, but it's consistent with how all the other files are named.
