### ISSUE TITLE
fail to queue jobs after "casm-calc --submit"

### ISSUE THREAD

**Issue by Lucien1234** [prisms-center/CASMcode#163]
Dear developers,
Thanks for your powerful codes but I meet a problem when I followed instructions shown by "casm status -n" step by step. Now I come to the state that I selected some configurations and executed "casm-calc --setup". The response information showed no error (except some strings like "vasp is not named") but when I checked the input files in xxx/training_data/SCEL#_#_#_#_#_#_#/#, there's only POS there, without any other files. And when I execute "casm-calc --submit", the repeated Errors occur:

**Configuration: SCEL3_3_1_1_0_0_0/7
Calculation directory: /short/qf9/ylu565/TestCASM/training_data/SCEL3_3_1_1_0_0_0/7/calctype.default
JobID: []
Constructing a VASP Relax object
  Relax directory: /short/qf9/ylu565/TestCASM/training_data/SCEL3_3_1_1_0_0_0/7/calctype.default
VASP Relax object constructed

Preparing to submit a VASP relaxation job
Counting atoms in the POSCAR
Constructing a job
Submitting
_qsub: Error: The system doesn't support the use of "-l nodes". Please use "-l ncpus" instead._
Wrote /short/qf9/ylu565/TestCASM/training_data/SCEL3_3_1_1_0_0_0/7/calctype.default/status.json
CASM VASPWrapper relaxation job submission complete

Construct a casm.vaspwrapper.Relax instance:
  Input directory: /short/qf9/ylu565/TestCASM/training_data/SCEL3_3_1_1_0_0_0/8
  Configuration: SCEL3_3_1_1_0_0_0/8
  Reading CASM settings
  Calculations directory: /short/qf9/ylu565/TestCASM/training_data/SCEL3_3_1_1_0_0_0/8/calctype.default
  Reading relax.json settings file
  Read settings from: /short/qf9/ylu565/TestCASM/training_data/settings/calctype.default/relax.json
  DONE

Submitting...**

Now I have calctype.default/status.json in my selected configuration directories and it shows "submitted", but when I check queue state by "qstat -u ylu565", No job is queueing.
Can you help me to check what's the problem?
Thank you very much!

**Comment by bpuchala** [comment]
Hi, It looks like there may be a couple issues. It is probably best to start by getting the `casm calc --setup` command to work correctly. After doing that command you should have all the necessary input files for running a calculation generated in `TestCASM/training_data/SCEL3_3_1_1_0_0_0/7/calctype.default`. If that is not working correctly, then `casm calc --submit` will not work either.

An example of settings files for VASP with PBS/Torque for our demonstration project is here: `https://github.com/prisms-center/CASMcode_demo/tree/master/TMS_ICME_PRISMS_workshop_May_2017/CASMcode_v0.2.1_demo/ZrO/training_data/settings/calctype.default`

Check the printed messages after trying `casm calc --submit` and adjust the settings files if possible. If you are still having trouble, please send us your settings files, the printed messages, and which calculation and job management software you are using, and we may be able to assist you in troubleshooting.

**Comment by Lucien1234** [comment]
Dear Puchala,
Thank you very much!
I tried the example and the problem solved. However, I also found where the problem is: the example includes a reference POSCAR and a corresponding KPOINTS. When I use a KPOINTS file with the third line start with "A" (automatically generate k-point mesh):
**Automatic mesh
0              # number of k-points = 0 ->automatic
Auto           # fully automatic
  64           # length (l)**

Execute "casm calc --setup", and the problem occurs:
**-- Construct: CASM Project --
from: "/short/qf9/ylu565/TestCASM"

-- Load project data --
read: "/short/qf9/ylu565/TestCASM/.casm/composition_axes.json"
read: "/short/qf9/ylu565/TestCASM/training_data/SCEL"
read: "/short/qf9/ylu565/TestCASM/.casm/config_list.json"

  Reading relax.json settings file
Using /short/qf9/ylu565/TestCASM/training_data/settings/calctype.default/relax.json as settings...
Relevant software is: vasp
Construct a casm.vaspwrapper.Relax instance:
  Input directory: /short/qf9/ylu565/TestCASM/training_data/SCEL1_1_1_1_0_0_0/0
  Configuration: SCEL1_1_1_1_0_0_0/0
  Reading CASM settings
  Calculations directory: /short/qf9/ylu565/TestCASM/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default
  Reading relax.json settings file
  Read settings from: /short/qf9/ylu565/TestCASM/training_data/settings/calctype.default/relax.json
  DONE

name 'vasp' is not defined**

When I design a reference POSCAR and a KPOINTS the problem solved again. That is, for some reason there will be error when using a single automatic KPOINT without POSCAR in calctype.default, even this KPOINTS is allowed according to "casm format --vasp". However, the example of an automatic KPOINTS is not given in "casm format --vasp", thus some misunderstanding may arise.
Hope this will be helpful for anyone who may interest.
Thank you for your help!
