### ISSUE TITLE
Final static calculation not considered converged

### ISSUE THREAD

**Issue by DS-Wen** [prisms-center/CASMcode#164]
Dear developers,

I found some strange things for final static runs. Some of my calculations were not considered converged even with the final INCAR setup. 

The ionic relaxations were converged within run.3 or run.5, then the final INCAR was used in the next run, say run.6. But after this static run, it couldn't stop and continued with the final INCAR setting to run.7, run.8... until runtime limit. One thing to know is that I was using a specified INCAR.final for this final run by specifying the path in the relax.json. This is because I wanted more outputs (LORBIT, etc) from my final run. 

Please let me know what could cause this problem and how to fix it. 

And if I don't want to rerun the calculations, say I can change run.7 into run.final. How can I let CASM know this is a finished run and extract the data? 

Thank you very much,
Dongsheng

**Comment by bpuchala** [comment]
Hi, I haven't run into the INCAR.final issue you describe before. Is it possible for you to send an archive example with the input files and calculations where this occurred so we can help determine why it is not finding that the calculations have converged?

The `casm calc --report` command will parse `run.final` directories to create `properties.calc.json` files without checking whether the calculations are converged or not. After that the `casm update` command can be used as usual to collect the calculation data into the project.

**Comment by DS-Wen** [comment]
Thank you,

I put the example in a git repo: https://github.com/DS-Wen/casm_project_archived_bugs.git 
You can find the input files (INCAR.base, INCAR.final etc) in the folder 'SCEL2_1_1_2_0_0_0/9398' or subdirectories. The error and output log files are also in that folder. 
I only put four run folders because the rest of the run folders are pretty much like run.3. 
I didn't upload the whole vasprun.xml file because it is too big. 

Please let me know if you need anything else.

Dongsheng

**Comment by bpuchala** [comment]
Sorry it took a bit for me to figure this out.

It looks like the problem is that CASM is not detecting the tag "System" in your `INCAR.final` as the same as "SYSTEM". We should fix CASM so that it does not see a difference between the two, but I believe that if you change "System" to "SYSTEM" it should stop appropriately.
