### ISSUE TITLE
continuing existing MC runs

### ISSUE THREAD

**Issue by jjcordell** [prisms-center/CASMcode#165]
I would like to continue running canonical monte carlo runs from existing runs at a single temperature ie start from POSCAR.final and continue adding new passes, ideally updating observations.json at the end to include the initial run as well as passes added later. I have tried a few different settings to do this but always end up overwriting the old trajectory rather than simply adding to it. Is there any way in CASM currently to carry out what I have described above? monte carlo input file attached as .txt (GitHub doesn't support uploading as .json?). 
[metropolis_canonical.txt](https://github.com/prisms-center/CASMcode/files/3602174/metropolis_canonical.txt)

Thanks for all the work put in to developing CASM and thanks in advance for your response.

**Comment by bpuchala** [comment]
We haven't added support for that use case at this time. If this would be commonly useful we can consider supporting it, so anyone else that would like this please chime in. 

There is a bit of a workaround that might work depending on what you are looking for. The `"driver"/"motif"/"configdof"` setting can be set to a "final_state.json" file.  You could use this to start a new run at the end state of a previous run, but it will not combine the observations or average for you.

**Comment by jjcordell** [comment]
Thanks, I'll use the workaround for the time being and see if I can splice the observations together.
