### ISSUE TITLE
Random occupation structure enumeration 

### ISSUE THREAD

**Issue by fermionian** [prisms-center/CASMcode#167]
Hi CASM developers.

I am new to CASM. Thanks for the great code!
I have a quick (maybe trivial...) question. I am doing enumeration for a structure with very large configuration number, so following previous issue #95, I used 
`casm enum -m ConfigEnumRandomOccupations`
But I noticed in 'casm enum --desc ConfigEnumRandomOccupations'

>   n_config: integer (optional, default=100) 
>     How many random configurations to generate. Includes duplicate and pre-
>     existing configurations.   

Can I somehow avoid/filter the duplicate structures, as I don't want duplicate structures during the following DFT calculations?

Thanks!

**Comment by bpuchala** [comment]
While it is possible that duplicate structures are enumerated, only unique structures are saved to the configuration database.

**Comment by fermionian** [comment]
Thanks @bpuchala so much for the quick reply.
Just to make sure I understand correctly. 

The configuration database essentially refers to the `.casm/config_list.json` file. While the "Number of configurations generated:" showed in `casm status -d` does not count any duplicate structures?

**Comment by fermionian** [comment]
Thanks @bpuchala so much for the quick reply.
Just to make sure I understand correctly.

The configuration database essentially refers to the .casm/config_list.json file. While the "Number of configurations generated:" shown in casm status -d does not count any duplicate structures?

**Comment by jcthomas** [comment]
Yes, the configuration database resides in `.casm/config_list.json`. The `casm enum` methods will only insert a new configuration into the database if it is symmetrically unique. Even if you insert configurations into the database from an external dataset, using `casm import`, only symmetry-distinct configurations will be added.

`casm status -d` counts all structures in the database, but the database only contains symmetry-distinct structures.
