### ISSUE TITLE
select certain scel_name

### ISSUE THREAD

**Issue by biswasrijal** [prisms-center/CASMcode#172]
Hi,
I would like to select using scel_name criteria? Can we do that using casm-select --set. How to give the criteria for scel_name?

Biswas.

**Comment by biswasrijal** [comment]
I used both commands and they don't work. I m using v0.3.dev-269-gd07b42 version.
casm select --set "re(configname, 'SCEL2_2_1_1_0_1_1/1')"
casm select --set "re(configname, 'SCEL2_2_1_1_0_1_1/[0-9]')"

**Comment by jcthomas** [comment]
Those commands work for me on the most recent commit. Do you have enumerated configurations for SCEL2_2_1_1_0_1_1, as indicated by `casm status -d`? If not, you'll need to enumerate configurations with `casm enum -m ConfigEnumAllOccupations`.

You can also try the following:
`casm select --set "re(scelname, 'SCEL2_2_1_1_0_1_1')"`
or
`casm select --set "rs(configname, 'SCEL2_2_1_1_0_1_1')"`
either of which should have the effect of selecting all configurations in SCEL2_2_1_1_0_1_1

**Comment by biswasrijal** [comment]
I get the following error. I noticed that the flag is in lower case, is that normal?

$casm select --set "re(scelname,'SCEL4_4_1_1_0_3_3')"
-- set: re(scelname,SCEL4_4_1_1_0_3_3) --
ERROR: Failure to select using criteria "re(scelname,SCEL4_4_1_1_0_3_3)" for configuration SCEL1_1_1_1_0_0_0/0
    Reason:  CRITICAL ERROR: Invalid format flag "scel4_4_1_1_0_3_3" specified.
                Did you mean "scel_size"?

$casm select --set "rs(configname,'SCEL4_4_1_1_0_3_3')"
-- set: rs(configname,SCEL4_4_1_1_0_3_3) --
ERROR: Failure to select using criteria "rs(configname,SCEL4_4_1_1_0_3_3)" for configuration SCEL1_1_1_1_0_0_0/0
    Reason:  CRITICAL ERROR: Invalid format flag "scel4_4_1_1_0_3_3" specified.
                Did you mean "scel_size"?

**Comment by jcthomas** [comment]
It seems that for some reason the inner single quotes are getting stripped from your query before it is passed to the `casm` executable. The single-quote symbols in the argument `'SCEL4_4_1_1_0_3_3'` designate it as a string literal. If I remove the single-quotes I can reproduce the same error you are seeing.

I am not familiar with this type of behavior. What shell are you using (i.e., what is the output of `echo $SHELL`)? Or, have you set up your environment in some way that would cause this type of behavior?

There are two possible things you can try. In bash, the precedence of single-quotes vs double-quotes depends on which comes first, and this is also the convention followed by CASM. This means that another valid way to structure the command is:
`casm select --set 'rs(configname,"SCEL4_4_1_1_0_3_3")'`
(note that the single-quotes enclose the double-quotes).

Alternatively, you can use *only* double-quotes, but escape the quotes that are intended to be passed to CASM:
`casm select --set "rs(configname,\"SCEL4_4_1_1_0_3_3\")"`
 I expect that this is probably the most general way to structure the command, but it is also quite awkward.

Any info about your setup and which resolution works for you would be helpful.

**Comment by biswasrijal** [comment]
I use bash shell. /bin/bash 

I do not remember setting up anything like that in my environment. I have created a separate environment just for running casm. 

This worked for me. 
casm select --set 'rs(configname,"SCEL4_4_1_1_0_3_3")'

Thank you Thomas for such quick response.

Biswas.
