### ISSUE TITLE
Monte Carlo and LTE

### ISSUE THREAD

**Issue by biswasrijal** [prisms-center/CASMcode#173]
Hi,
why do I keep getting the following error while running LTE calculations. What is a motif configuration in this case?

-- Error: Calculating low temperature expansion --
  _Defect lowered the potential energy. Your motif configuration is not the 0K ground state._

_ERROR calculating single spin flip LTE grand canonical potential._

_Error calculating low temperature expansion. Not in the ground state._

Thank you.
Biswas.

**Comment by jcthomas** [comment]
This indicates that there is a groundstate of your cluster expansion that is not among your database of enumerated configurations. 'motif configuration' refers to the known configuration from your database that is used to initialize the Monte Carlo. There are a number of strategies you can pursue to enumerate new groundstates of your cluster expansion using CASM. You can find additional information in the discussion of issues #149 and #156
