### ISSUE TITLE
How to deal with partial occupancy?

### ISSUE THREAD

**Issue by haesunpark87** [prisms-center/CASMcode#174]
HI, 

I want to run cluster expansion calculations on a layered material, and I want to know whether it is possible to deal with the partial occupancy. I want to construct a convex hull as a function of the concentration of A in AMO2 layered compound. There are 4 sites for atom A, but only two out of 4 sites are occupied and each site is distinctive. Is there a way to describe such partial occupancy in CASM code?

**Comment by Gustautas** [comment]
Yes. In prim.json (or PRIM) file mark partially occupied sites as ["A", "Va"]. Run `casm format --prim` for an example.

**Comment by jcthomas** [comment]
@haesunpark87 sorry for not getting to this sooner. `casm format --prim` is a good place to get started, as well as the demo project located here: https://github.com/prisms-center/CASMcode_demo/tree/master/TMS_ICME_PRISMS_workshop_May_2017

Without knowing more about your particular problem, I can't be certain what you want to do. If you are only interested in configurations of the compound in a particular composition range, CASM provides functionality to restrict the composition space of your dataset. You can find some more information regarding how to do that in the discussion of Issue #150

**Comment by haesunpark87** [comment]
Thank you for your response. 
I was able to constrain a composition range that I'm interested in, but encounter another issue. In the attached figure, there are four possible sites that are either occupied or empty and only 2 out of 4 are occupied. However, it is unphysical that, for example, occupying site 2 and 3 or site 3 and 4. It causes relaxed structure is largely deviated from the initial structure, which make the fitting difficult. Also, in some cases structure relaxed into totally different structure. So, I'm wondering whether there is an away to rule out such unphysical vacancy distributions within CASM code.  
![Untitled](https://user-images.githubusercontent.com/43765756/72109993-c6ff7800-32fc-11ea-80ef-22a91de5e4ff.png)

**Comment by bpuchala** [comment]
It is not currently possible to force rules like that.

**Comment by jcthomas** [comment]
It is not possible to run through the entire project workflow imposing such a constraint, but you can enumerate and analyze structures that satisfy this constraint, and fit a rudimentary cluster expansion. It is not currently possible to perform Monte Carlo simulations satisfying such a constraint.

You can create selections and perform filtered enumeration using any property listed in `casm query -h properties`. In your case, you can restrict the pair correlations between sites, which is measured by the 'corr' property. You will first need to generate correlation basis functions by running `casm bset -u`. This step requires the input file bspecs.json, which is described by `casm format --bspecs`. 

The [CASM tutorial slides](https://github.com/prisms-center/CASMcode_demo/tree/master/TMS_ICME_PRISMS_workshop_May_2017) describe how basis functions are defined in some detail. In your case it is probably easiest to use the "occupation" convention, where a "Va" species (vacancy) takes a value of 0 and an "O" species takes a value of 1. `corr(0)` is the constant function, and always has the value 1. `corr(1)` through `corr(4)` correspond to the average occupation of each of the four sublattice "O"/"Va" sublattices. `corr(5)` is the pair correlation for the nearest-neighbor pair. You can print out definitions of the individual basis functions using `casm bset --functions`.

To ensure a pair of sites is never "O":"O", you can impose that its corresponding correlation is zero. For example, to enumerate configurations having 1/2 oxygen composition and no "O":"O" pairs at the first- and second- nearest neighbor, you can run
````
casm enum -m ConfigEnumAllOccupations --all --filter "and(eq(comp(a),0.5),eq(corr(5),0), eq(corr(6),0))"
````
Note that the `and` operator can join any number of boolean arguments, and the `eq` operator performs floating-point comparisons with a tolerance of 1e-5.
