### ISSUE TITLE
Extracting entropy from MC calculations

### ISSUE THREAD

**Issue by Gustautas** [prisms-center/CASMcode#175]
Hello, and Happy New Year!

I believe it should be possible to extract configurational entropy from canonical Metropolis Monte Carlo runs. Is there a way to do it in CASM?

Thanks in advance.

**Comment by Gustautas** [comment]
Ok, so the best way is probably to do thermodynamic integration using heat capacities at different temperatures. However, results.json file reports negative heat capacities. If heat capacity is calculated according to https://prisms-center.github.io/CASMcode_docs/assets/definitions/CASM_param_comp.pdf eq. 67, it should always be positive due to Cauchy-Schwarz Inequality. I am missing something?

**Comment by jcthomas** [comment]
Yes, to obtain the free energy and entropy from Monte Carlo simulations it is necessary to do thermodynamic integration, which is described in some detail in Sec. 1.5 of the document you linked to. 

The best results are typically obtained by integrating the differential of Φ/(k*T) to obtain the free energy (i.e., 'characteristic potential' in the linked document). Note that the integral gives only the free-energy difference between two points in parameter space, so to find the free energy value, you need to begin the integration from a point where the total free energy is already known (such as at an extreme of the composition or at zero temperature, where entropy is zero).

Once the free energy is known, you can find the entropy via the difference 
T*S = Ω - Φ 
where Ω is the 'semi-grand-canonical potential energy'

As you note, the heat capacity should not be negative. Can you share an example output file that shows this behavior?  @bpuchala Have you seen this behavior or know why it might occur?

**Comment by bpuchala** [comment]
This is probably a numerical method problem like noted here (https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Covariance), which we should fix. That said, perhaps it is only occurring at very low temperatures and can be avoided by using the low temperature expansion reference above the temperature it is occurring at?

**Comment by Gustautas** [comment]
Thanks, indeed, it occurs only at low temperatures (below ~150K). I will try LTE and let you know how it goes.
Regarding my original question:
I am afraid that I'm bound to canonical ensembles for my case since the composition space is highly restricted physically (only A<sub>x</sub>B<sub>2+x</sub>C<sub>4-x</sub>D makes sense), and I'm not able to obtain required compositions controlling only the chemical potential (not sure if it's even practically possible).
So I guess I will have to stick to integrating heat capacities over the range of temperatures.
Just to be sure: heat capacities are reported in eV/(K*Unit_cell)?

**Comment by bpuchala** [comment]
Yes on the units.

**Comment by Gustautas** [comment]
Ok, so I can not use low-temperature expansion because I am stuck with canonical ensembles. However, I get much better results when setting  "dependent_runs" to true while gradually decreasing the temperature from 2000K (getting small negative heat capacities at ~60K and bellow).
