### ISSUE TITLE
vasp.relax.report

### ISSUE THREAD

**Issue by StevenAlice93** [prisms-center/CASMcode#176]
Hello, I have met a problem when I use the function vasp.relax.report, it gives the next issue:

Begin vasp.relax.report
Traceback (most recent call last):
  File "/root/anaconda2/envs/casm/bin/vasp.relax.report", line 12, in <module>
    sys.exit(main())
  File "/root/anaconda2/envs/casm/lib/python3.6/site-packages/casm/scripts/vasp_relax_report.py", line 25, in main
    compat.dump(json, output, 'properties.calc.json', 'w', cls=noindent.NoIndentEncoder,
AttributeError: module 'casm.misc.compat' has no attribute 'dump'

I installed the software by:
(1). install anaconda2
(2). conda create -n casm --override-channels -c bpuchala/label/dev -c prisms-center -c defaults -c conda-forge casm
 
Please give me a help!
 Thank you all.

**Comment by jcthomas** [comment]
I believe that `vasp.relax.report` is deprecated in favor of `casm calc --report`. You can find documentation by running `casm calc --desc`.

**Comment by StevenAlice93** [comment]
hello, I still met the next problem:

Unable to report properties for directory /root/casm_old/********.
Please verify that it contains a completed calculation.
