### ISSUE TITLE
Insufficient DFT Hull States

### ISSUE THREAD

**Issue by darnoceloc** [prisms-center/CASMcode#181]
Writing: /ufrc/hahn/conrad.r.cole/casm_CeO2/cluster_expansions/clex.formation_energy/calctype.default/ref.default/bset.default/eci.__tmp/eci.json

-- Load project data --
refresh cluster expansions

Error in casm.query
  proj: /ufrc/hahn/conrad.r.cole/casm_CeO2
  Attempted to execute: 'query -k 'clex_hull_dist(ALL,atom_frac) clex(formation_energy) clex_hull_dist(/ufrc/hahn/conrad.r.cole/casm_CeO2/.casm/tmp/ALL_dft_hull,atom_frac) ' -c ALL -v -o STDOUT'
---- stdout: ---------------------
#
---- stderr: ---------------------
Print:
   - clex_hull_dist(ALL,atom_frac) clex(formation_energy) clex_hull_dist(/ufrc/hahn/conrad.r.cole/casm_CeO2/.casm/tmp/ALL_dft_hull,atom_frac)
to "STDOUT"

Initialization error: QH6214 qhull input error: not enough points(2) to construct initial simplex (need 3)

While executing:  | qhull
Options selected for Qhull 2015.0.6.r 2015/10/20:
  run-id 1956078928  _pre-merge  _zero-centrum

Is there a general protocol for breaking the DFT hull?
I have increased the number of configurations, composition range and modified the cluster sizes.
Are there any other approaches apart from modifying the level of theory, utilizing more stringent convergence criteria, and fitting to some subset of the calculated structures?

**Comment by jcthomas** [comment]
Is this output from casm-learn? As noted in #146, this can happen in a few cases; particularly when you have no DFT groundstates at intermediate compositions. It is safe to turn off the `"checkhull"` option in `casm-learn`, and you can just examine the cluster-expanded energies after fitting with `casm query`.

Regarding your question of 'breaking the DFT hull' could you clarify a bit?  Do any of the DFT data have negative formation energies relative to the end-states? Do your cluster expansion fits generally reproduce the features of your DFT data? 

If the DFT data are not representative of experimental phase stability, there is possibly some consideration that is not accounted for by your DFT calculations, such as charge localization, entropic effects, or an unsuitable choice of functional for the chemistry.

**Comment by darnoceloc** [comment]
This output is from casm learn -s fit_1_ga.json --checkhull --indiv 0 and python plot_hull.py.

I do not believe any of the DFT data have negative formation energies relative to the end-states, all the clex_hull_dist values are non-negative.

I utilized SCAN for these calculations but PBE+U, HSE and other higher levels of theory have proven to more accurately reproduce electronic structure properties.

The chemistry does comprise multiple charge states (due to polaron formation/charge localization) which require different pseudopoential files to obtain electronic convergence.

**Comment by darnoceloc** [comment]
Many configurations have clex(formation_energy) values less than zero. There were no "checkhull" settings specified within my fit.json files at any point, I assume this would result in the default settings being utilized?

**Comment by jcthomas** [comment]
The checkhull option doesn't enforce any criteria on the fits, it just
performs additional criteria for each fit, which makes it a bit easier to
select a suitable individual fit from the hall of fame. Assuming you have
more than one fit in your hall-of-fame, you can try the second-best fit,
third-best fit, etc. To select the second-best fit run `casm-learn -s
<setting-file> --select 1` for third-best, run `casm-learn -s
<setting-file> --select 2`, etc.

**Comment by darnoceloc** [comment]
Why would one utilize the second or third best fit instead of the best fit?

**Comment by bpuchala** [comment]
There are different ways to determine which is the best fit and best CV score is not necessarily always the best. For instance it is possible that the fit with the best CV score doesn't reproduce the hull states correctly, or just more generally some important configurations are fit better with a worse CV score. Another consideration is that you might want a fit that is less precise but has fewer terms and is therefore faster to evaluate. Also, it may just be useful to see the other fits and understand which basis functions are on and what effect they have on the overall fit or Monte Carlo results. Usually there are ways to adjust the problem setup (configuration selection, weighting, etc.) so that the best scoring fit is the one you want, but we do not want to force users to do that.

**Comment by darnoceloc** [comment]
I understand these are VASP errors not CASM errors, but, I am repeatedly getting these messages for failed jobs. Does it make sense to modify initial settings and resubmit or just assume configurations that yield these errors should be neglected from the training set?

**hard stop encountered!  aborting job ...
 ERROR FEXCF: supplied exchange-correlation table
    is too small, maximal index :        5543
 ERROR FEXCF: supplied exchange-correlation table
    is too small, maximal index :        5543
 ERROR FEXCF: supplied exchange-correlation table
    is too small, maximal index :        5543
 ERROR FEXCF: supplied exchange-correlation table
    is too small, maximal index :        5543**

**BRMIX: very serious problems  the old and the new charge density differ**

**Comment by bpuchala** [comment]
I mostly see this error reported for unreasonable geometries. So if that is the case, you need to figure out if it is an unreasonable starting "ideal" configuration in CASM (perhaps your prim.json is unreasonable, or perhaps there are some neighboring basis sites are too close when both occupied in some configurations) or something that happens during relaxation due to INCAR settings.

**Comment by darnoceloc** [comment]
What is the ideal approach for manually setting project chemical reference states?
I'm getting this message when using --set-auto.

**Error in ChemicalReference::hyperplane 
Input space does not span the composition space of your prim.**

And getting this message when manually setting from the file below via --set chemical_reference.json.

Error reading chemical reference state: {
  "Ce3" : 0.000000000000,
  "Ce4" : 1.000000000000,
  "O" : 2.000000000000,
  "Va" : 0.000000000000,
  "energy_per_species" : -8.110718683333
}
Error reading chemical reference states from /ref.default/chemical_reference.json
```
{
  "chemical_reference" : {
    "global" : [
      {
       	"Ce4" : 1.00,
        "Ce3" : 0.0,
        "O" : 2.0000,
        "Va" : 0.0,
        "energy_per_species" : -8.11071868333333
      },
      {
       	"Ce4" : 0.5,
        "Ce3" : 0.5,
        "O" : 1.75,
        "Va" : 0.25,
        "energy_per_species" : -7.3821855825
      }
    ],
    "species_order" : [ "Ce4", "Ce3", "O", "Va" ]
  }
}

```

**Comment by bpuchala** [comment]
The `casm ref --desc` gives several examples of setting the reference states via the CLI program. Editing the chemical_reference.json file directly is fine too.

Including `"Va":0.0` in the compositions is not necessary for "chemical_reference.json" and will cause an error.  

If you have two independent composition axes you will need three non-colinear reference states for reference energies across the whole composition space.

**Comment by darnoceloc** [comment]
But can I manually create the chemical_reference.json file if one does not already exist? 
I want to use the configuration corresponding to the composition axis origin as a reference.
I'm not sure what other structures correspond to ground states at this point.

My custom composition axis required a negative value for the occupation of one of the species for the axis maximum point. I think this may be causing issues when setting the chemical reference. Correct me if I'm wrong.

**Comment by bpuchala** [comment]
You can always edit or create the CASM files manually. CASM won't know the difference.

There should not be a need to have a negative composition. I've not tested whether it would actually cause an issue or not.

**Comment by darnoceloc** [comment]
Still have not been able to set the chemical reference or enumerate new structures beyond the prior maximum voume.

**Comment by bpuchala** [comment]
If you share your prim here or to "casm-developers@lists.engr.ucsb.edu" I can give you example commands to set it or a an example composition_axes file.

**Comment by darnoceloc** [comment]
Shouldn't the prim and composition_axes be constant throughout a given project?

**Comment by bpuchala** [comment]
Sorry, I meant chemical_reference file
