### ISSUE TITLE
jobs.db vasp input settings

### ISSUE THREAD

**Issue by darnoceloc** [prisms-center/CASMcode#182]
I removed the jobs.db file in order to perform calculations (resubmit SCEL_XXXX jobs) at different levels of theory and modify input settings, however, when I make modifications, they are not accounted for in the new run.x directories and the settings automatically revert to the initial conditions that were generated from casm-calc --setup.
How should the .prisms_jobs file or other relevant files be modified/configured to rectify this issue?
Is it possible to perform vasp relaxations with CASM at the LSDA+U or HSE06 levels of theory?

**Comment by darnoceloc** [comment]
No comment?

**Comment by bpuchala** [comment]
Sorry for the delayed response. The standard way to run calculations of the same configuration with different calculation parameters is to use `casm settings --new-calctype <calctypename>` to create a parallel set of directories where the calculations are performed. Then you shouldn't have issues with jobs showing up as complete when they aren't or using the wrong inputs, etc.

**Comment by darnoceloc** [comment]
Is there documentation that enumerates and describes all these additional features which may not necessarily be part of any given project workflow (excluding the help command)?

**Comment by darnoceloc** [comment]
Getting the error below when submitting PBE+U jobs, how can this be rectified?  

**raise IncarError("Could not convert '" + tag + "' : '" + self.tags[tag] + "' to int list")
casm.vasp.io.incar.IncarError: Could not convert 'LDAUL' : '[3, -1]' to int list**

**Comment by bpuchala** [comment]
The documentation we currently have is the `casm format`, `casm status`, `--help` and `--desc` messages, and the tutorial slides.

The message is getting printed by this code which tries to standardize the format of input:

```
temp = []
for value in self.tags[tag].split():
    try:
        temp.append(int(value))
    except ValueError:
        raise IncarError("Could not convert '" + tag + "' : '" + self.tags[tag] + "' to int list")
self.tags[tag] = temp
```

It is expecting input in the format:
```
"LDAUL": "3 -1"
```

**Comment by darnoceloc** [comment]
Is there documentation of the format expected for all the INCAR tags?

**Comment by skk74** [comment]
In general per atom tags such as LDAUL and LDAUJ should be specified in the SPECIES file. If there is an INCAR tag that is unrecognized by CASM, CASM will still forward whatever is in the example INCAR file you have in your project settings directory.

**Comment by darnoceloc** [comment]
In the species file? In what format? Which tags apart from these(LSDA+U), MAGMOM  and SAXIS qualify as per atom?

**Comment by skk74** [comment]
The SPECIES file is to be created by the user in a CASM project settings directory in order to tell CASM's vaspwrapper or qewrapper what pseudopotentials to use as well as the tags you have mentioned. Off the top of my head I can't think of any other per atom tags that might be relevant. To learn the format of the SPECIES file please look at the output of ```casm format --vasp```

**Comment by darnoceloc** [comment]
Is casm designed to handle calculations at levels of theory beyond standard LDA, GGA and METAGGA?
All the PBE+U and HSE calculations I have attempted so far have failed.
Can you provide an example of formatting required for PBE+U and HSE06 calculations?
If I am using multiple calctypes within the same project should I have a SPECIES file within the main training_data/settings/ directory or just within the individual training_data_settings/calctypename/ directories?
Should the format below be compatible for PBE+U?

`SPECIES    ALIAS    POTCAR  POTCAR_location  LDAUL  LDAUU`
`Ce               Ce          1               /Ce                          3           5.0`
`Ce_3	    Ce           0              /Ce_3                       3           5.0`
`O                 O            1              /O                            -1          0`

**Comment by bpuchala** [comment]
Yes, we've done PBE+U and HSE calculations with CASM. The CASM / dft interfaces are definitely due for some improvements and better examples and tutorials. 

I think your SPECIES file example looks OK.

To give a little more detail on how it works for VASP, the code ([here](https://github.com/prisms-center/CASMcode/blob/0.3.X/python/casm/casm/vasp/io/incar.py)) largely controls how CASM takes the example INCAR file parameters and SPECIES file parameters (for species specific parameters) and uses them to create an INCAR file for a particular CASM configuration. Which of these lists, located at the top of the linked file, a parameter is in controls how it behaves (does it get written once or for every atom, what type is it formatted to be, etc.):
```
# List of tags in VASP sorted by the data type associated with it
VASP_TAG_INT_LIST = ['ialgo','ibrion','icharg','images','ismear','ispin',\
                     'istart','isym','lorbit','nbands','ndav','ngx','ngxf',\
                     'ngy','ngyf','ngz','ngzf','npar','ncore','spind','nsw',\
                     'isif', 'kpar', 'voskown', 'nsim', 'nedos', 'lmaxfock',\
                     'lmaxmix', 'nkred','ivdw','nelmin', 'nelm', 'nelmdl',\
                     'ldautype','ldauprint', 'ldauprint']
VASP_TAG_FLOAT_LIST = ['ediff','ediffg','emax','emin','encut','potim','sigma',\
                     'enmax','symprec', 'time', 'hfscreen','amix','bmix',\
                     'amix_mag', 'bmix_mag']
VASP_TAG_BOOL_LIST = ['lcharg','lsorbit','lwave','lscalapack', 'lscalu',\
                     'lplane', 'lhfcalc', 'shiftred', 'evenonly', 'oddonly',\
                     'addgrid', 'ldau', 'lasph']
# Site-wise list of arrays of FLOAT
VASP_TAG_SITEF_LIST = ['magmom','rwigs']
# Species-wise list of arrays of FLOAT
VASP_TAG_SPECF_LIST = ['ldauu', 'ldauj']
# Site-wise list of arrays of INT
VASP_TAG_SPECI_LIST = ['ldaul']
VASP_TAG_STRING_LIST = ['algo','prec','system', 'precfock','lreal']
```

If there is a tag that is missing (I know `METAGGA` is missing and needs to be added) you can simply add it to the correct list in your distribution.

**Comment by darnoceloc** [comment]
I'm getting this message for quite a few successfully completed relaxed configurations that are not being included in the project's list of fully calculated structures. What exactly is the cause of this and how can these configurations be properly accounted for without performing the calculations again? 

**job = db.select_job(jobid)  #pylint: disable=unused-variable
self.curs.execute("SELECT * FROM jobs WHERE jobid=?", (jobid,))
sqlite3.DatabaseError: database disk image is malformed**

**Comment by bpuchala** [comment]
I haven't seen this before, but it seems your sqlite jobs database file is corrupted. That could be caused by anything that would cause a file write to fail (out of disk space, program interruption, bug, etc.). I think your best bet might be to just delete the database file (`~/.prisms_jobs/jobs.db`). You would lose tracking of current job status, but you wouldn't lose any actual calculation data. So then you can run `casm calc --report` for all your configurations and `casm update` to collect results. 

If the problem persists, and it's not something obvious that caused the corruption like you are out of disk space, we'll have to dig deeper.

**Comment by darnoceloc** [comment]
I'm getting this error (another which I've never seen before) when running `casm update` after deleting `~/.prisms_jobs/jobs.db` and running `casm calc --report`.
Which does not make sense since this structure is the 0 end of my composition axes and should be the least disordered and most similar to PRIM. Never encountered this error when this structure was initially calculated and accounted for 

**Error: Unable to map relaxed structure data contained in "/*/training_data/SCEL1_1_1_1_0_0_0/0/*/properties.calc.json" onto PRIM.
       Structure is incompatible with PRIM.**

**Comment by darnoceloc** [comment]
**calculated lattice vectors for that structure**
[0.0, 2.74450623, 2.74450623],
    [2.74450623, 0.0, 2.74450623],
    [2.74450623, 2.74450623, 0.0]

**prim.json lattice vectors**
  [ 0.000000000000, 2.713725000000, 2.71372500000 ],
    [ 2.713725000000, 0.000000000000, 2.713725000000 ],
    [ 2.713725000000, 2.713725000000, 0.000000000000 ]

**Comment by bpuchala** [comment]
Some ways to check the configuration mapping results in general:
- check the calculated structure's lattice deformation
- check the calculated structure's basis deformation
- consider varying the `casm update --cost-weight` to vary lattice vs basis mapping score weights
- if there are vacancies, consider using `casm update` options for allowed vacancy concentration and volume relaxation
- make sure the `prim.json` hasn't been overwritten with something different
- try saving the current `properties.calc.json` and using a dummy one with everything set to be as identical as possible to the ideal configuration. then vary the structure to see when it fails to map.
- try copying prim.json and properties.calc.json into a new project and checking there with `casm update` or `casm import`

**Comment by darnoceloc** [comment]
That structure is alreday in config_list.json with 0.000 lattice and basis deformations.

**Comment by bpuchala** [comment]
Maybe I'm misunderstanding something, but I believe you are saying that `casm update` mapped and imported `properties.calc.json` for that configuration into `config_list.json` successfully before, but now something has changed and it is failing. If that is correct, then there are a number of ways, listed in my previous comment, to check why.

**Comment by jcthomas** [comment]
The "Structure is incompatible with PRIM" error should only occur if the
number of different species in the relaxed cannot be realized in any
supercell of prim.json. Examples of this would be if your prim describes an
A/B alloy on a crystal with two basis sites, and your relaxed structure has
three atoms (e.g., 2 A species and 1 B species), or it has an atom of the
wrong species altogether (e.g., a C species, when there are only A and B in
prim.json).

Species names are case-sensitive and must match exactly. If you edit the
species names in prim.json, you generally will also need to search and
replace the species names in your `properties.calc.json` files as well.
Project-wide find-and-replace can be accomplished using a utility such as
`sed`, although doing such project-wide changes can also cause their own
problems.

**Comment by darnoceloc** [comment]
Thanks for the clarification, the issue was mismatch between species names in `properties.calc.json` and `prim.json`.
How can I ensure that these automatically match without having to manually modify? I have two different species on one basis site and species/Vac on another; however my properties.calc.json was using the same alias for both species on the first basis site.

**Comment by bpuchala** [comment]
It's controlled by the SPECIES file. The same POTCAR is used for each CASM species with matching ALIAS. In your previous comment you have different POTCAR for Ce and Ce_3, but the same ALIAS. This might be the issue. If they are using different POTCAR, then you want to use Ce and Ce_3 for the ALIAS also.
