### ISSUE TITLE
casm-calc --setup does NOT setup the quantum espresoo input files

### ISSUE THREAD

**Issue by ajaberi1** [prisms-center/CASMcode#186]
Hello,

I have a problem with setting up the Quantum Espresso (QE) input files. After I copy the 'Relax.json', 'SPECIES', and 'filename.in' files (attached) to the $ROOT/training_data/settings/calctype.default directory and then type casm-calc --setup, I get no QE input file in the $ROOT/training_data/SCEL_XXXX/X/calctype.default directory. Can you please fix this!?

This is the message I get after casm-calc --setup:

--------------------------------
-- Construct: CASM Project -- 
from: "/Users/alijaberi/Software/CASM/ZrO"

-- Load project data -- 
read: "/Users/alijaberi/Software/CASM/ZrO/.casm/composition_axes.json"
read: "/Users/alijaberi/Software/CASM/ZrO/training_data/SCEL"
read: "/Users/alijaberi/Software/CASM/ZrO/.casm/config_list.json"

  Reading relax.json settings file
Using /Users/alijaberi/Software/CASM/ZrO/training_data/settings/calctype.default/relax.json as settings...
Relevant software is: quantumespresso
Working on directory /Users/alijaberi/Software/CASM/ZrO/training_data/SCEL1_1_1_1_0_0_0/0
  Configuration: SCEL1_1_1_1_0_0_0/0
Reading CASM settings
Constructing a CASM QEWrapper Relax object
  Setting up directories
  Reading relax.json settings file
Using /Users/alijaberi/Software/CASM/ZrO/training_data/settings/calctype.default/relax.json as settings...
Quantum Espresso Relax object constructed

Setting up Quantum Espresso input files: /Users/alijaberi/Software/CASM/ZrO/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default
  Reading Infile: //ZrO/training_data/settings/calctype.default/ZrO.in
  Reading SPECIES: /Users/alijaberi/Software/CASM/ZrO/training_data/settings/calctype.default/SPECIES
  Reading K_POINTS from: /Users/alijaberi/Software/CASM/ZrO/training_data/settings/calctype.default/ZrO.in
'K_POINTS'
---------------------------------

Thank you,
Ali

[files.zip](https://github.com/prisms-center/CASMcode/files/4945045/files.zip)

**Comment by bpuchala** [comment]
It's not reading the K_POINTS section of your infile correctly. Please try adding an additional empty line to the end of the ZrO.in file.

**Comment by ajaberi1** [comment]
Thank you so much! Now it works!
