### ISSUE TITLE
Local (site-centric) correlation functions.

### ISSUE THREAD

**Issue by Gustautas** [prisms-center/CASMcode#188]
Hi,
This article https://www.nature.com/articles/s41524-018-0110-y states that CASM was used to obtain local correlation functions.
However, unlike with getting "normal" cluster-based correlations, I have not managed to find any straightforward way to do so. 
@jcthomas and @anirudhrn You both used this concept. Could You please guide me a bit on this?

**Comment by anirudhrn** [comment]
Yes, `casm` can be used to calculate site-centric correlation functions. These values cannot be accessed from the command line interface. If you are interested in calculating local correlations for your application, please do reach out to me at `anirudh@ucsb.edu`.

**Comment by q654262498** [comment]
Hello，I have the same question as you,can I have your email adress and to dicuss with you together?

**Comment by q654262498** [comment]
@Gustautas Have your question solved?May I have your email address to discuss about this?

**Comment by anirudhrn** [comment]
Site-centric correlation functions can be calculated with the code that is found in [this](https://github.com/anirudhrn/site-descriptors) repository

**Comment by q654262498** [comment]
> Site-centric correlation functions can be calculated with the code that is found in [this](https://github.com/anirudhrn/site-descriptors) repository

How can we find those code in this repository,and where is this repository?Is there any operation demo that we can learn to calculate the site-centric correlation functions,thank you for the answer.
