### ISSUE TITLE
issue with using 'basis_deformation' with casm select

### ISSUE THREAD

**Issue by julijavin** [prisms-center/CASMcode#19]
On casm version 0.2.0, if I try to run something like:
casm select --set-off "gt(basis_deformation,0.004)"

I get an error:
terminate called after throwing an instance of 'std::runtime_error'
what(): Const operator[] access, but basis_deformation does not exist
Aborted

I get no error and correct behavior if I do:
casm query -k "gt(basis_deformation,0.004)"

It appears that while casm is able to calculate the basis_deformation (and I believe it is calculating it correctly), the criterion cannot be used for selection.

EDIT: This also appears to be a problem for some other selection criteria like formation_energy and formation_energy_per_atom as well as anything that uses those values (e.g. hull_dist).

**Comment by bpuchala** [comment]
I believe this was fixed by #20
