### ISSUE TITLE
Vasp freeze error for HSE06

### ISSUE THREAD

**Issue by zccaayo** [prisms-center/CASMcode#190]
The vasp freeze error kicks in for loop times over 5 minutes. This is realistic for GGA optimizations but not for hybrid DFT. Could you condition this vasp freeze criterion on LHFCALC=.False.?

**Comment by bpuchala** [comment]
It looks like this is currently hard coded. You could edit the class `FreezeError` in the file `python/casm/casm/vasp/error.py`

**Comment by zccaayo** [comment]
Thanks that's what I did much appreciated!
