### ISSUE TITLE
CVS problem

### ISSUE THREAD

**Issue by blueflame97** [prisms-center/CASMcode#192]
Now I'm doing Uranium dioxide's cluster expansion via CASM, and I have a CVS problem. Other papers said that when ECI fitting, CVS might be typically less than 0.025 eV. However, in my project, the smallest value is 0.041 eV. I used the GeneticAlgorithm method and selected 15 configurations. (The number of all configurations is 69.) 
I wonder
1. My system's energies are almost over then 600eV. Is that affect the CVS?
2. UO2 has antiferromagnetism. Is that affect the CVS?
3. Like this project, In large-scale projects,  0.041 eV CVS is reasonable and suit for the Monte Carlo simulations?
4. Are there any other tips for lower the CVS?
I have really enjoyed the software and appreciate the effort. Thank you.

**Comment by bpuchala** [comment]
> My system's energies are almost over then 600eV. Is that affect the CVS?

No, the magnitude does not affect the CV score

> UO2 has antiferromagnetism. Is that affect the CVS?

More complicated physics can make it tougher to fit coefficients.

> In large-scale projects, 0.041 eV CVS is reasonable and suit for the Monte Carlo simulations?

That is always up to the individual researcher to demonstrate. Generally we do like to see less than 10 meV per atom though.

> Are there any other tips for lower the CVS?

15/69 selected/total calculations is definitely on the small side. We would expect to see at least 10 calculations per non-zero coefficient fitted and often more.

> I have really enjoyed the software and appreciate the effort

Thanks!
