### ISSUE TITLE
How to relate integral coordinates to Cartesian coordinates

### ISSUE THREAD

**Issue by xig126** [prisms-center/CASMcode#196]
Hello,

In basis.json file, the sites are described by the "Integral coordinates". How can we relate these coordinates to Cartesian coordinates ? Thanks for your help.
For example,

{
      "linear_function_index" : 224,
      "mult" : 24,
      "orbit" : [ 4, 49, 2 ],
      "prototype" : {
        "max_length" : 3.546374028497,
        "min_length" : 2.895602268959,
        "sites" : [
          [ 3, 0, 0, 0 ],
          [ 0, 1, 0, -1 ],
          [ 0, 0, 1, -1 ],
          [ 2, 0, 0, 0 ]
        ]
      }

**Comment by bpuchala** [comment]
"Integral coordinates" are listed as `(b, i, j, k)`, where `b` indicates basis site index into the `prim.json` file, and `i, j, k` are multiples of the `prim.json` lattice vectors. So as pseudo-code: `cart_coord = prim.basis(b).cart_coord + prim.lattice.vectors(0)*i + prim.lattice.vectors(1)*j + prim.lattice.vectors(2)*k`.

**Comment by jcthomas** [comment]
Adding to what Brian said, `casm bset` provides the options `--functions`,
`--orbits`, and `--clusters`, which will print cluster and basis function
information to the screen in Cartesian coordinates.

**Comment by xig126** [comment]
@bpuchala @jcthomas Thanks !
