### ISSUE TITLE
can't filter config enumeration with correlations

### ISSUE THREAD

**Issue by max-radin** [prisms-center/CASMcode#2]
casm 0.2.0 crashes when I try to use correlations to filter configuration enumeration, such as 

`casm enum -c --all --filter 'eq(corr(1),0.5)'`

The error message is:
```
Cannot filter configurations using the expression provided: 
basic_string::_M_construct null not valid
Exiting...
```

**Comment by max-radin** [comment]
It looks like it works when I use `corr(1:1)` instead of `corr(1)`. Is this the intended behavior?

**Comment by bpuchala** [comment]
When we added the ability to plot `corr` for different basis sets via `corr(cluster_expansion_name)` or `corr(cluster_expansion_name,i:j)`, or use the current default basis set via `corr(i:j)`, it began detecting `corr(cluster_expansion_name)` vs `corr(i:j)` by checking for a `:` and I forgot to add a check for lone integer index. I need to add the check back in. In the meantime, as you noted, `corr(i:i)` works.
