### ISSUE TITLE
Questions on restricting certain types of swaps in MC simulation

### ISSUE THREAD

**Issue by txy159** [prisms-center/CASMcode#205]
Dear developers,

Thank you for your powerful software!

I'm currently studying the intercalation of Li into LixMO2 system (M=transition metal). In my case, there's Li/M + Li/Va mixing  and I have constructed a cluster expansion Hamiltonian based on different configurations of Li/M + Li/Va mixing. I tried to perform a MC simulation to study its thermodynamic properties upon lithium intercalation. In experiment, there should be no diffusion on M sites, but in MC simulation the swap between Li, Va and M is allowed. Can I run a MC simulation with all M atoms being fixed at its initial states ?

I've got another problem when calculating the voltage profile of Li intercalate into LixMO2. It seems that the voltage can be derived from the change of the chemical potential of Li (mu_Li), but I got confused because mu_Li is actually the variable for grand canonical monte carlo simulation. Could you pls give me an example and show how you guys usually calculate the voltage profile? Can I do that in a canonical monte carlo simulation ?

Thanks in advance.

**Comment by bpuchala** [comment]
> Can I run a MC simulation with all M atoms being fixed at its initial states ?

We don't currently support this.

> Could you pls give me an example and show how you guys usually calculate the voltage profile? Can I do that in a canonical monte carlo simulation ?

One of our papers that writes it out more explicitly is Journal of Power Sources 242 (2013) 400e404. doi: [10.1016/j.jpowsour.2013.05.074](http://dx.doi.org/10.1016/j.jpowsour.2013.05.074). For grand canonical Monte Carlo calculations, temperature and chemical potential are input conditions and mean composition is an output. From a reference state and number of those calculations you can do free energy integration to calculate the free energy as a function of chemical potential / composition.
