### ISSUE TITLE
How to deal with configurations that has large hull_dist in mc calculation ?

### ISSUE THREAD

**Issue by txy159** [prisms-center/CASMcode#212]
Dear developers,

I have fitted a set of ECIs with data weighted by exp(-hull_dist/kT) and the fitted cluster expansion is able to describe the DFT ground states accurately. I then performed MC calculation at 0K using LTE method. 

My problem is that I found the ground states predicted by LTE and DFT are different. This is because some configurations with large hull_dist are considered by LTE. For example, LiCoMnO2 configuration has a DFT_hull_dist of 0.5 eV/unit cell and the weight of this data is ~4e-9. The error between DFT and predicted energy of this configuration is larger than 10 eV/unit cell.

Should I exclude configurations with large hull_dist from LTE calculation ? If so, how to modify the mc.json file ?

Thanks.

**Comment by bpuchala** [comment]
Try a smaller weight difference between hull configurations and the far from the hull configurations... you can't just fit the hull states. You probably do not want the weight of the hull configurations to be more than 10 or so times the weight given to the lowest weighted configuration, and all things equal less is better.
