### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by MarisaYu** [prisms-center/CASMcode#217]
When I run "bash build.sh", it  have some errors like:

./.libs/libcasm.so: undefined reference to `CASM::jsonParser& CASM::write_clust<__gnu_cxx::__normal_iterator<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> > const*, std::vector<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> >, std::allocator<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> > > > >, CASM::ProtoFuncsPrinter>(__gnu_cxx::__normal_iterator<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> > const*, std::vector<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> >, std::allocator<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> > > > >, __gnu_cxx::__normal_iterator<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> > const*, std::vector<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> >, std::allocator<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> > > > >, CASM::jsonParser&, CASM::ProtoFuncsPrinter)'
/home/software/CASM-install/boost//lib/libboost_regex.so: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
./.libs/libcasm.so: undefined reference to `CASM::jsonParser& CASM::write_clust<__gnu_cxx::__normal_iterator<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> > const*, std::vector<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> >, std::allocator<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> > > > >, CASM::ProtoFuncsPrinter>(__gnu_cxx::__normal_iterator<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> > const*, std::vector<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> >, std::allocator<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> > > > >, __gnu_cxx::__normal_iterator<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> > const*, std::vector<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> >, std::allocator<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> > > > >, CASM::jsonParser&, CASM::ProtoFuncsPrinter)'
./.libs/libcasm.so: undefined reference to `std::__throw_bad_array_new_length()'
collect2: error: ld returned 1 exit status
make[1]: *** [ccasm] Error 1
make[1]: *** Waiting for unfinished jobs....
./.libs/libcasm.so: undefined reference to `CASM::jsonParser& CASM::write_clust<__gnu_cxx::__normal_iterator<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> > const*, std::vector<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> >, std::allocator<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> > > > >, CASM::ProtoFuncsPrinter>(__gnu_cxx::__normal_iterator<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> > const*, std::vector<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> >, std::allocator<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> > > > >, __gnu_cxx::__normal_iterator<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> > const*, std::vector<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> >, std::allocator<CASM::Orbit<CASM::AperiodicSymCompare<CASM::IntegralCluster, void> > > > >, CASM::jsonParser&, CASM::ProtoFuncsPrinter)'
/home/software/CASM-install/boost//lib/libboost_regex.so: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
./.libs/libcasm.so: undefined reference to `CASM::jsonParser& CASM::write_clust<__gnu_cxx::__normal_iterator<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> > const*, std::vector<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> >, std::allocator<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> > > > >, CASM::ProtoFuncsPrinter>(__gnu_cxx::__normal_iterator<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> > const*, std::vector<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> >, std::allocator<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> > > > >, __gnu_cxx::__normal_iterator<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> > const*, std::vector<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> >, std::allocator<CASM::Orbit<CASM::PrimPeriodicSymCompare<CASM::IntegralCluster, void> > > > >, CASM::jsonParser&, CASM::ProtoFuncsPrinter)'
./.libs/libcasm.so: undefined reference to `std::__throw_bad_array_new_length()'
collect2: error: ld returned 1 exit status
make[1]: *** [casm-complete] Error 1
make[1]: Leaving directory `/home/software/CASM-install/CASMcode-1.2.0'
make: *** [all] Error 2
'make  -j 20' failed

**Comment by bpuchala** [comment]
The build method we test with involves installing a conda environment as described in INSTALL.md, and building from within that environment using a pre-compiled boost libraries available as a conda package. Our test build doesn't currently have this error, but if anyone else sees this and wants to add a solution, please do.
