### ISSUE TITLE
How do I pick configurations in a particular atomic fraction range

### ISSUE THREAD

**Issue by q654262498** [prisms-center/CASMcode#221]
I use the following two commands to filter configurations for a specificatomic atomic fraction range 
casm query --alias is_O_dilute = 'lt(atom_frac(O),0.10)'
casm enum --method ConfigEnumAllOccupations --all --filter "is_O_dilute"
but it can only chose atomic fraction less than 0.1,what command should I use to select the atomic fraction range that I need?

**Comment by bpuchala** [comment]
You can do a range with something like ` 'and(gt(atom_frac(O),0.05),lt(atom_frac(O),0.10)' `.

You can also use the query directly with `--filter` without make an alias first:
```
casm enum --method ConfigEnumAllOccupations --all --filter 'lt(atom_frac(O),0.10)'
```

**Comment by q654262498** [comment]
Thank you very much for your answer
