### ISSUE TITLE
key errors in calc-setup

### ISSUE THREAD

**Issue by NotThatGreatAtLife** [prisms-center/CASMcode#222]
Hello,
I thought this might be relevant:

When trying to run casm-calc --setup, I got key errors for 'lattice_vectors' and 'coordinate_mode' in the poscar.py file. It looks like all the SCEL structure.json files had the keys 'lattice' and 'coord_mode', so I changed the poscar.py to work with these keys, and the casm-calc --setup command worked well for me after that. It looks like maybe there is an inconsistency in which keys you are using?

**Comment by bpuchala** [comment]
See #226
