### ISSUE TITLE
casm-calc --submit gives FileNotFoundError: [Errno 2] No such file or directory: 'mpirun'

### ISSUE THREAD

**Issue by NotThatGreatAtLife** [prisms-center/CASMcode#223]
Hi, 
I am trying to run my first casm project, I have been consistently getting this error. I've tried to modify my calc.json file a number of ways, including:
-not using the 'vasp_cmd' tag
-using "vasp_cmd":"mpirun /home/USER/bin/vasp.5.4.4.std" 
-using "vasp_cmd":"mpirun -np $SLURM_NTASKS  /home/USER/bin/vasp.5.4.4.std"

All of which give me this error. Sorry if this is a basic problem!

**Comment by rpaudel2021** [comment]
Hello, 
I have also encountered the same error. If you have resolved it, please let me know.

**Comment by NotThatGreatAtLife** [comment]
> 

Hi, 
Yes, sorry this was a while ago, but I think some of my problems stemmed from not adding the right libraries to my .bashrc 

after that, I used these for my calc.json file:

For SLURM, I used:
"vasp_cmd":"mpirun -np {NCPUS} /path/to/vasp/"

and for PBS, I used:
"vasp_cmd”:”/path/to/mpirun -np {NCPUS} -machinefile $PBS_NODEFILE /path/to/vasp”

Hope this is helpful!

**Comment by rpaudel2021** [comment]
Thank you for your response. I would like to chat with you via email (ramesh.pdl56@gmail.com).
