### ISSUE TITLE
Key error when reading properties.calc.json for casm update

### ISSUE THREAD

**Issue by NotThatGreatAtLife** [prisms-center/CASMcode#226]
Hi, when I try to run casm update, I get an error because properties.calc.json doesn't have the key "coord_mode", only "coordinate_mode". 

I think that the error is due to the file casm/crystallography/io/jsonStruc.hh on line 86. I was hoping you could change that to "coordinate_mode"? 

This also happens with the key "lattice" when properties.calc.json has "lattice_vectors"

These are the errors:
`(casm) -bash-4.1$ ccasm update
-- Read: Settings -- 
{
  "force" : false,
  "mapping" : {
    "cost_tol" : 0.000010000000,
    "fix_lattice" : false,
    "fix_volume" : false,
    "ideal" : false,
    "k_best" : 1,
    "lattice_weight" : 0.500000000000,
    "max_va_frac" : 0.500000000000,
    "max_vol_change" : 0.300000000000,
    "min_va_frac" : 0.000000000000,
    "primitive_only" : true,
    "robust" : false,
    "strict" : false
  }
}

Updating data records for SCEL1_1_1_1_0_0_0/0
ERROR: Error parsing SimpleStructure from JSON object. One or more tags were improperly specified:
JSON const operator[] access, but coord_mode does not exist
`

**Comment by bpuchala** [comment]
Hi, thank you for the report. I have not been able to reproduce this issue with the latest version of CASM installed, though this or something similar have been reported by multiple people. There may be an issue with the installation that multiple versions installed are conflicting? Or perhaps the C++ components of CASM and the casm-python components are mismatched? The jsonStruc.hh file is deprecated and will be removed in an upcoming update.

**Comment by bpuchala** [comment]
It seems that the conda installation command that was originally included in the installation instructions does not always give the latest version of CASM. I believe the version mismatch between the casm-cpp and casm-python caused this issue.  I've updated the instructions on the [installation page](https://prisms-center.github.io/CASMcode_docs/pages/installation/), to include the latest casm-cpp version number. This should ensure that the latest version is included.

**Comment by NotThatGreatAtLife** [comment]
Hi, thank you for including this! However, when I try to update casm-cpp to 1.2.0 using the command 'conda install casm-cpp=1.2.0', I get the error:
`(casm) -bash-4.1$ conda install casm-cpp=1.2.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - casm-cpp=1.2.0

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


`
Is the newest version of casm-cpp available to download using conda?

**Comment by bpuchala** [comment]
`casm-cpp` is available for conda on mac and linux. It, and some dependencies, are available from the `prisms-center` channel. The remaining dependencies are available on the `conda-forge` channel. 

In the conda installation instructions [here](https://prisms-center.github.io/CASMcode_docs/pages/installation/#install-using-conda), I suggest specifying the channels and casm-cpp version explicitly:

```
conda create -n casm --override-channels -c prisms-center -c conda-forge casm-cpp=1.2.0 python=3
```

Additionally, from the active conda environment, updating to the latest version can be done with:
```
conda update --override-channels -c prisms-center -c conda-forge casm-cpp
```

**Comment by NotThatGreatAtLife** [comment]
Thank you so much! It works well now!
