### ISSUE TITLE
casm continuation calculation

### ISSUE THREAD

**Issue by cdc221144** [prisms-center/CASMcode#227]
Excuse me, do structural optimization with casm, and how to continue the calculation of the task to achieve walltime?

**Comment by bpuchala** [comment]
It depends on how you submitted the job. 

If you are using `casm calc --submit` command, then they are submitted using the [prisms-jobs package](https://github.com/prisms-center/prisms_jobs). This keeps a small database of submitted jobs which the `pstat` command gives access to. The `pstat --continue` command can re-submit jobs that hit the walltime. The README page for the prisms-jobs and the `pstat -h` command can provide some help for options to track and manage the jobs submitted in this way. 

You can also always re-submit jobs manually however you would normally run jobs on your system.

**Comment by cdc221144** [comment]
OK，thank you very much！
