### ISSUE TITLE
charge neutrality issue 

### ISSUE THREAD

**Issue by sjtuzhanglei** [prisms-center/CASMcode#242]
For oxides, we typically need to consider charge neutrality along the composition axes. E.g, YSZ, Y(x)Zr(1-x)O(2-0.5x). Although it is a ternary system, it is indeed a pseudo-binary system, where composition axes along the cation and the anion sublattice composition is coupled, in order to maintain charge neutrality.

How to specify that in CASM, and during which stage of the workflow? 

Can we customize the composition_axes.json to set the linear dependency between the two axes? And how to set the end member as ZrO2 and Y2O3?

**Comment by sjtuzhanglei** [comment]
No comments on this?

**Comment by sjtuzhanglei** [comment]
casm status -n

#################################

CASM status:

Error in ChemicalReference::hyperplane 
Input space does not span the composition space of your prim.
Input space (column vectors in atom_frac space):
 0.0222222
      -0.2
  0.222222
         0
-0.0444444
End members:
1 1 1 1
1 1 0 0
0 0 1 1
3 0 3 0
0 3 0 3
Prim space (column vectors in atom_frac space):
 0.408248 -0.123091
 0.408248  0.615457
        0 -0.738549
        0         0
-0.816497  0.246183
Rows correspond to: [ "Ba", "Zr", "Y", "Va", "O" ]
X, prim_space = input_space*X: 
-0.395079  -3.27582
input_space*X: 
-0.00877953   -0.072796
  0.0790158    0.655164
 -0.0877953    -0.72796
          0           0
  0.0175591    0.145592
relative_error: 0.707107
tol: 1e-10
Error reading chemical reference states from "/global/cscratch1/sd/voz5005/proton_conductor/bazro3/bzy/training_data/settings/calctype.default/ref.default/chemical_reference.json"
-- Error: reading chemical_reference.json -- 
file: "/global/cscratch1/sd/voz5005/proton_conductor/bazro3/bzy/training_data/settings/calctype.default/ref.default/chemical_reference.json"

CASM: Uncaught exception: 
std::exception

{
  "chemical_reference" : {
    "global" : [
      { 
        "Ba" : 0.200000000000,
        "Zr" : 0.200000000000,
        "Y"  : 0.000000000000,
        "O"  : 0.600000000000,
        "energy_per_species" : -8.724187600000
      },
      {
        "Ba" : 0.222222222222,
        "Zr" : 0.000000000000,
        "Y"  : 0.222222222222,
        "O"  : 0.555555555556,
        "energy_per_species" : -7.992908333333
      }
    ],
    "species_order" : [ "Ba", "Zr", "Y", "Va", "O" ]
  }
}

**Comment by bpuchala** [comment]
The composition_axes.json file is documented [here](https://prisms-center.github.io/CASMcode_docs/formats/casm/clex/CompositionAxes/). You can set custom composition axes, including restriction to a subspace, by specifying a custom "origin" and end members ("a", "b", etc.). The values should be set to the composition as number per unit cell for the points defining the axes. 

You can copy existing axes, give them a new number in the "possible_axes" object, and then `casm composition --display` to check them, and `casm compsition --select <number>` to select them, which will also generate formulas based on the origin and end members.

After that, you can use the axes with the `comp` measure via the enumeration "filter" option to only add configurations that within a subspace into your configuration list. Or alternatively, you could still enumerate all compositions and then use `casm select` with `comp` to choose the ones that lie in the subspace of interest.

The composition axes do not currently restrict the grand canonical Monte Carlo calculations to a particular subspace.

**Comment by sjtuzhanglei** [comment]
I set a 'dummy' ref for a charged composition, and it works through, is this OK?

Besides, can casm search and find the ground state of the end member?

{
  "chemical_reference" : {
    "global" : [
      { 
        "Ba" : 1.000000000000,
        "Zr" : 1.000000000000,
        "Y"  : 0.000000000000,
        "O"  : 3.000000000000,
        "energy_per_species" : -8.724187600000
      },
      {
        "Ba" : 1.000000000000,
        "Zr" : 0.000000000000,
        "Y"  : 1.000000000000,
        "O"  : 2.500000000000,
        "energy_per_species" : -7.992908333333
      },
      {
        "Ba" : 1.000000000000,
        "Zr" : 0.000000000000,
        "Y"  : 1.000000000000,
        "O"  : 3.000000000000,
        "energy_per_species" : 0.0000000000000
      }
    ],
    "species_order" : [ "Ba", "Zr", "Y", "Va", "O" ]
  }
}

**Comment by sjtuzhanglei** [comment]
Would this restricted composition space also cause error in checkhull?

casm learn -s fit_1_ga.json --checkhull
Loading fit_1_ga.json
Loading Hall of Fame: fit_1_ga_halloffame.pkl
# Get problem data...
# Reading existing problem specs from: fit_1_ga_specs.pkl
#   DONE

-- Check: individual 0  --
Index: Selected                                    #Selected    CV           RMS          wRMS         Estimator                FeatureSelection         Note
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
    0: 1110000101011110011101111101000000110100... 81           0.043931541  0.035484619  0.035484619  LinearRegression         GeneticAlgorithm         

Writing: /global/cscratch1/sd/voz5005/proton_conductor/bazro3/bzy/cluster_expansions/clex.formation_energy/calctype.default/ref.default/bset.default/eci.__tmp/eci.json 

Error in casm.query
  proj: /global/cscratch1/sd/voz5005/proton_conductor/bazro3/bzy
  Attempted to execute: 'query -k 'clex_hull_dist(ALL,atom_frac) clex(formation_energy) clex_hull_dist(/global/cscratch1/sd/voz5005/proton_conductor/bazro3/bzy/.casm/tmp/ALL_dft_hull,atom_frac) ' -c ALL -t config -v -o STDOUT'
---- stdout: ---------------------
#
---- stderr: ---------------------
Print:
   - clex_hull_dist(ALL,atom_frac) clex(formation_energy) clex_hull_dist(/global/cscratch1/sd/voz5005/proton_conductor/bazro3/bzy/.casm/tmp/ALL_dft_hull,atom_frac) 
to "STDOUT"

****ERROR: QH6214 qhull input error: not enough points(2) to construct initial simplex (need 3)****

While executing:  | qhull 
Options selected for Qhull 2015.0.6.r 2015/10/20:
  run-id 352568251  _pre-merge  _zero-centrum

**Comment by bpuchala** [comment]
I believe CASM's hull calculation should be correctly adapting to the composition subspace spanned by the configurations selected by the "selection" option to checkhull ("ALL" is the default), but it may be failing if no configurations have a negative formation energy. Is it possible that is the cause?

The reference energies can span any composition space, including composition's not possible according to the composition axes or even the prim. This can be useful to set the same reference energy for multiple CASM projects even if they don't have the same composition space.

**Comment by sjtuzhanglei** [comment]
Yes, looks like I don't have a negative formation energy in between. 

Question: How to update the ref energy as the ground state energy of each end member, as calculations find lower state for the end member? casm ref --set-auto gave error because of the subspace dimension issue I mentioned above. Manually find the ground state is inefficient.

**Comment by bpuchala** [comment]
The simplest hack might be to add a configuration outside of your restricted subspace just for the purpose of avoiding these issues.

Otherwise you could write a script that queries the energy of configurations, filtering for the end member compositions, find the minimum for each end member, then sets the reference. I'm afraid we don't have that ready to go at the moment.
