### ISSUE TITLE
how to resubmit jobs for continuation with higher accuracy?

### ISSUE THREAD

**Issue by sjtuzhanglei** [prisms-center/CASMcode#245]
Is there a convenient way CASM can do to resubmit the calculated ('complete') jobs? I want to copy CONTCAR to POSCAR and continue the relaxation with a higher accurate settings.

However, since those jobs were finished with run.* folders, properties.json, status.json. CASM recognize those as complete jobs and won't submitting them....

Is there a way to automatically change those scel/configs status to resubmit?

Thanks,

**Comment by bpuchala** [comment]
There are a couple levels to address this. I'm assuming you are submitting jobs via `casm calc --submit`, so it's using [prisms_jobs](https://prisms-center.github.io/prisms_jobs_docs/scripts/pstat.html) to track jobs.

1) Jobs that have `run.final` directory with a finished OUTCAR will be found to be complete, so you'll have to go through and delete these

    I don't believe `status.json` is used authoritatively in checking for completeness when re-submitting, but you should delete that too. The command `ccasm run --exec <command>` may be useful for these types of things. It will, for each configuration selected, run the given command with the configuration's directory path as an argument. Try `ccasm select --set-on && ccasm run --exec "ls"` as an example.

2) Modify `calc.json` for those structures you want to continue

    You can change the convergence criteria, and / or add `"final": "/path/to/INCAR.final"` giving the path to a custom INCAR to use for a final constant volume calculation with different parameters than the default. If you only want the criteria to apply to particular configurations you can place a `settings/$CURR_CALCTYPE/calc.json` file in the configuration directory and it will take precedence over the project-wide one. 

3) You can use `pstat --reset` or `pstat --delete` to modify how jobs are marked in the jobs database

    These will remove the "complete" tag from jobs or delete them from the database entirely. You can specify which jobs to modify using the `--all` or `--range MINID MAXID`, or `--recent DD:HH:MM:SS` options. Or just delete the entire db file.

4) Either `pstat --continue` to continue "incomplete" jobs, or re-submit with `casm calc --submit` and CASM will check if calculations are complete based on the updated `calc.json` files.
