### ISSUE TITLE
Error in Hull(): Invalid composition or energy data.

### ISSUE THREAD

**Issue by sjtuzhanglei** [prisms-center/CASMcode#248]
Dear CASM developers,

It seems my customized composition axes still have problems. When I tried to plot hull_dist, it gave me error:

casm query -c CALCULATED -k 'comp formation_energy hull_dist'

Print:
   - comp formation_energy hull_dist

#Invalid data for hull construction:
#                configname    composition     energy
    SCEL10_10_1_1_0_1_6/200             OK    invalid
    SCEL10_10_1_1_0_1_6/201             OK    invalid
    SCEL10_10_1_1_0_1_6/202             OK    invalid
    SCEL10_10_1_1_0_1_6/203             OK    invalid
    SCEL10_10_1_1_0_1_6/204             OK    invalid
    SCEL10_10_1_1_0_1_9/200             OK    invalid
    SCEL10_10_1_1_0_1_9/201             OK    invalid
......

    SCEL9_9_1_1_0_8_8/214               OK    invalid
    SCEL9_9_1_1_0_8_8/215               OK    invalid
    SCEL9_9_1_1_0_8_8/216               OK    invalid

ERROR: Error in Hull(): Invalid composition or energy data. 
Make sure you have set composition axes, all selected configurations
have calculation results, and you have set your chemical reference.

casm composition -d

***************************

Possible composition axes:

       KEY     ORIGIN          a          b     GENERAL FORMULA
       ---        ---        ---        ---     ---
         0  BaZrVa(3)   BaYVa(3)   BaZrO(3)     Ba(1)Zr(1-a)Y(a)Va(3-3b)O(3b)
         1   BaZrO(3)    BaYO(3)  BaZrVa(3)     Ba(1)Zr(1-a)Y(a)Va(3b)O(3-3b)
         2   BaYVa(3)    BaYO(3)  BaZrVa(3)     Ba(1)Zr(b)Y(1-b)Va(3-3a)O(3a)
         3    BaYO(3)   BaYVa(3)   BaZrO(3)     Ba(1)Zr(b)Y(1-b)Va(3a)O(3-3a)
         4   BaZrO(3)    BaYO(3) BaZrVa(0.5)O(2.5)     Ba(1)Zr(1-a)Y(a)Va(0.5b)O(3-0.5b)
         5   BaZrO(3) BaYVa(0.5)O(2.5)     Ba(1)Zr(1-a)Y(a)Va(0.5a)O(3-0.5a)

Currently selected composition axes: 5

Parametric composition:
  comp(a) = -0.4*(comp_n(Zr) - 1)  + 0.4*comp_n(Y)  + 0.2*comp_n(Va)  - 0.2*(comp_n(O) - 3) 

Composition:
  comp_n(Ba) = 1
  comp_n(Zr) = 1 - 1*comp(a) 
  comp_n(Y) = 1*comp(a) 
  comp_n(Va) = 0.5*comp(a) 
  comp_n(O) = 3 - 0.5*comp(a) 

Parametric chemical potentials:
  param_chem_pot(a) = - chem_pot(Zr) + chem_pot(Y) -0.5*chem_pot(O) 

cat .casm/composition_axes.json 

......
    "4" : {
      "a" : [ 1.000000000000, 0.000000000000, 1.000000000000, 0.000000000000, 3.000000000000 ],
      "b" : [ 1.000000000000, 1.000000000000, 0.000000000000, 0.500000000000, 2.500000000000 ],
      "components" : [ "Ba", "Zr", "Y", "Va", "O" ],
      "independent_compositions" : 2,
      "mol_formula" : "Ba(1)Zr(1-a)Y(a)Va(0.5b)O(3-0.5b)",
      "origin" : [ 1.000000000000, 1.000000000000, 0.000000000000, 0.000000000000, 3.000000000000 ],
      "param_formula" : "a(0.5-0.5Zr+0.5Y)b(3+Va-O)"
    },
    "5" : {
      "a" : [ 1.000000000000, 0.000000000000, 1.000000000000, 0.500000000000, 2.500000000000 ],
      "components" : [ "Ba", "Zr", "Y", "Va", "O" ],
      "independent_compositions" : 1,
      "mol_formula" : "Ba(1)Zr(1-a)Y(a)Va(0.5a)O(3-0.5a)",
      "origin" : [ 1.000000000000, 1.000000000000, 0.000000000000, 0.000000000000, 3.000000000000 ],
      "param_formula" : "a(1-0.4Zr+0.4Y+0.2Va-0.2O)"
    }
  }
}

**Comment by bpuchala** [comment]
I think you need `hull_dist(CALCULATED,atom_frac)`, or to select just the calculated configurations in your MASTER selection. The input `-c $selection` is which confiurations you are getting the hull distance for, and the `$selection` of `hull_dist($selection,atom_frac)` is which configurations are being used to construct the hull, which are in general two different sets. By default `hull_dist(MASTER,atom_frac)` is used.
