### ISSUE TITLE
case-calc --submit is too slow

### ISSUE THREAD

**Issue by sjtuzhanglei** [prisms-center/CASMcode#249]
casm-calc --submit
Construct a casm.vaspwrapper.Relax instance:
queue software: slurm
Submitting...
Configuration: SCEL1_1_1_1_0_0_0/6
Calculation directory: /global/cscratch1/sd/voz5005/proton_conductor/bazro3/bzy/training_data/SCEL1_1_1_1_0_0_0/6/calctype.default
JobID: ['60542146', '60542241', '60542382', '60542494', '60542625', '60579938', '60580649', '60580986', '60581209', '60581291', '60581744', '60745800']
...

Wondering even in one compute node of NERSC, why case-calc --submit is too slow and stuck on the first enumeration...

**Comment by sjtuzhanglei** [comment]
Any suggestions to accelerate this?

**Comment by bpuchala** [comment]
It's not clear what the issue is. Most likely it is either some kind of issue with the jobs tracking database, or a some issue with the calculation files. So options to try to fix it would include clearing the jobs database, and inspecting the vasp input / output files associated with that configuration to either fix or remove them.

**Comment by sjtuzhanglei** [comment]
how to clear the jobs database?

**Comment by bpuchala** [comment]
`pstat -a --delete`

More docs [here](https://prisms-center.github.io/prisms_jobs_docs/scripts/pstat.html).

The database file is store at `$HOME/.prisms_jobs/jobs.db` by default, so you can also rm it directly.

**Comment by sjtuzhanglei** [comment]
This happens when I finished calculations, but enumerated more configs again and tried to submit.

The initial work flow of enumeration, set-up and submit goes well, but not for the second time.

What could be the problem?
