### ISSUE TITLE
ERROR running Canonical Monte Carlo. No valid option given. (LTE Run)

### ISSUE THREAD

**Issue by sjtuzhanglei** [prisms-center/CASMcode#255]
Dear CASM developers,

Wondering what lte is doing exactly? Does it predict low-temperature ground state? How it is different with simulated annealing MC?

casm monte -s lte-cano-1.json 
-- Read: Monte Carlo settings -- 
from: "/global/cscratch1/sd/voz5005/proton_conductor/bazro3/bzy/mc/lte/lte-cano-1.json"
ensemble: Canonical
method: LTE1

ERROR running Canonical Monte Carlo. No valid option given.

cat lte-cano-1.json
{
  "comment" : "This is a sample input file. Unrecognized attributes (like the ones prepended with '_') are ignored.",
  "debug" : false,
  "ensemble" : "canonical",
  "method" : "lte1",
  "model" : {
    "formation_energy" : "formation_energy"
  },
  "supercell" : [
    [2, 0, 0],
    [0, 2, 2],
    [0, -4, 4]
  ],
  "data" : {
    "storage" : {
      "write_observations" : true,
      "write_trajectory" : true,
      "output_format" : ["csv", "json"]
    }
  },
  "driver" : {
    "mode" : "incremental",
    "dependent_runs" : false,
    "motif" : {
      "_configname" : "default",
      "configname" : "SCEL1_1_1_1_0_0_0/6",
      "_configdof" : "path/to/final_state.json"
    },
    "initial_conditions" : {
        "comp_n" : {
          "Ba" : 1.000,
          "Zr" : 0.875,
          "Y"  : 0.125,
          "Va" : 0.0625,
          "O"  : 2.9375
        },
      "temperature" : 300.0,
      "tolerance" : 0.01
      },
    "final_conditions" : {
        "comp_n" : { 
          "Ba" : 1.000,
          "Zr" : 0.875,
          "Y"  : 0.125,
          "Va" : 0.0625,
          "O"  : 2.9375
        },  
      "temperature" : 500.0,
      "tolerance" : 0.01
      },
    "incremental_conditions" : { 
        "comp_n" : {
          "Ba" : 0.000,
          "Zr" : 0.000,
          "Y"  : 0.000,
          "Va" : 0.000,
          "O"  : 0.000
        },
      "temperature" : 10.0,
      "tolerance" : 0.01
      }
  }
}

**Comment by bpuchala** [comment]
The "lte1" method only works with the grand canonical ensemble. It is a single spin flip low temperature expansion, which means it calculates the grand canonical potential ("phi_LTE" in the results) by directly evaluating the partition function under the assumption that only single site defects relative to the ground state contribute significantly. If it finds that any single spin flip actually lowers the potential energy, and therefore the initial configuration is not a ground state, it gives an error.

**Comment by sjtuzhanglei** [comment]
Got it, thanks! So it looks like simulated annealing MC is the best shot I could go for to generate more configs in a large supercell for a better ECI fitting.
