### ISSUE TITLE
Monte Carlo shouldn't require jsonDB

### ISSUE THREAD

**Issue by deober** [prisms-center/CASMcode#277]
Hello, 

I am trying to run monte carlo through casm with bare bones projects (only a prim.json, basis.json and eci.json in an initialized casm project). 

It isn't obvious to me why the jsonDB should be necessary, because I shouldn't need to have any configurations enumerated to run monte carlo, but casm monte will fail without it.

**Comment by seshasaibehara** [comment]
Your `configname` is `auto` in MC settings. In that case, it searches in the configurations for lowest potential energy to be used as motif. Change it to `default`, then it will be determined from the PRIM and you won't need jsonDB.

**Comment by deober** [comment]
Okay, thank you!
