### ISSUE TITLE
VASP wrapper with MAGMOM in large systems

### ISSUE THREAD

**Issue by skk74** [prisms-center/CASMcode#28]
I believe there is a design flaw in the way the vasp wrapper writes the INCAR for per atom tags such as MAGMOM from the SPECIES file. It writes out the value of MAGMOM for each species in an array format. The problem with doing this is in large supercells the number of atoms gets quite large and the MAGMOM line in INCAR becomes very long. I believe there is some sort of VASP default that only reads a certain amount of characters per tag which seems to be roughly ~250 characters for MAGMOM. A better way to write the MAGMOM tag in the INCAR would be the following:
NUM_SPECIES1 * MAGMOM_SPECIES1 NUMSPECIES2  * MAGMOM_SPECIES2 .... 
because this uses much fewer characters and gets the same message across to VASP within its character limit.  

This can be fixed by making some changes to read() and update() in incar.py, but requires a sorted poscar. Working on a fix now.

**Comment by skk74** [comment]
Forgot to mention I had a fix for this and am using it currently. Not sure if anyone else may be interested though.

**Comment by bpuchala** [comment]
Yes, please submit a pull request
