### ISSUE TITLE
Failed to print POSCAR for each configuration

### ISSUE THREAD

**Issue by M9JS** [prisms-center/CASMcode#295]
I was trying to use command 
`$ ccasm query -a --write-pos`
To print all result of enumeration in form of POSCAR. But there is no response to that. I tried adding tags like"-n, -o <path>" but they did not work.
Could you tell me if I got something wrong? Thanks!

**Comment by seshasaibehara** [comment]
- `ccasm query --write-pos` should work for the configurations that are currently selected in the project.
- If you want POSCAR for all the configurations you can do `ccasm select --set-on` followed by `ccasm query --write-pos`.

**Comment by M9JS** [comment]
Thanks for informing me of the selection.
```
$ ccasm select -t scel --set-on
-- Input scel list: MASTER -- 
# scels in this project: 74
# scels included in this list: 74
# scels selected in this list: 74

-- set-on:  -- 
selection time: 2.5291e-05 (s)

-- Write: Selection -- 
write: "MASTER"

-- Output scel list: MASTER -- 
# scels in this project: 74
# scels included in this list: 74
# scels selected in this list: 74
```

I did  select all the supercell but still failed to print the POSCAR as I tried `ccasm query --write-pos` or `ccasm query -t scel --write-pos`.
No response to that, did I missed something?

**Comment by bpuchala** [comment]
For supercells (`-t scel`) a LAT is written instead of POSCAR. The `ccasm info -m SupercellInfo` method has a "default_poscar" option though.

**Comment by xivh** [comment]
Maybe you already figured it out, but the POSCAR for each selected configuration is written as 'POS' in the training data folder:

training_data/SCEL1_1_1_1_0_0_0/0/POS
training_data/SCEL1_1_1_1_0_0_0/1/POS

**Comment by bpuchala** [comment]
Yes, that is the name CASM has always given those files. It is also possible to get POSCAR strings using the `poscar` query.

**Comment by WalterWhite1611** [comment]
"ccasm info -m SupercellInfo default_poscar", is it the correct way to write? while I'm getting this error,
-- Error Summary -- 

-- Errors at location: /properties -- 
Error: missing required option 'properties'.


{
  "properties.ERROR" : [
    "Error: missing required option 'properties'."
  ]
}

ERROR: Error reading SupercellInfo input
