### ISSUE TITLE
Issues with INCAR tags for slab calculations

### ISSUE THREAD

**Issue by sjtuzhanglei** [prisms-center/CASMcode#324]
Dear CASM developers:

I got this error using casm-calc --setup

Warning: unknown INCAR tag 'LDIPOL' with value '.T.'
Warning: unknown INCAR tag 'IDIPOL' with value '3'
Warning: unknown INCAR tag 'LVHAR' with value '.T.'
...
raise IncarError("Could not find '" + tag + "' : '" +
casm.vasp.io.incar.IncarError: Could not find 'ADDGRID' : '.t.' in ['.true.','.false.']

Looks like some VASP INCAR tags are not supported?

Thanks,

**Comment by xivh** [comment]
Try `ADDGRID = .TRUE.` or `ADDGRID = .true.` and I think everything will work including the "unknown" INCAR tags (but double check).

**Comment by sjtuzhanglei** [comment]
Got it, thanks!
