### ISSUE TITLE
Segmentation fault while running canonical MC calculation

### ISSUE THREAD

**Issue by pandeydhanshree** [prisms-center/CASMcode#329]
Hello
I was trying to run canonical MC calculations with the following input file 

{
  "comment" : "This is a sample input file. Unrecognized attributes (like the ones prepended with '_') are ignored.",
  "debug" : true,
  "ensemble" : "canonical",
  "method" : "metropolis",
  "model" : {
    "formation_energy" : "formation_energy"
  },
  "supercell" : [
    [4, 0, 8],
    [0, 4, 8],
    [4, 4, 4]
  ],
  "data" : {
    "sample_by" : "pass",
    "sample_period" : 1,
    "_N_sample" : 1000,
    "_N_pass" : 1000,
    "_N_step" : 1000,
    "_max_pass" : 10000,
    "min_pass" : 1000,
    "_max_step" : 10000,
    "_max_sample" : 500,
    "_min_sample" : 100,
    "confidence" : 0.95,
    "measurements" : [
      {
        "quantity" : "formation_energy",
        "precision" : 1e-2
      },
      {
        "quantity" : "potential_energy"
      },
      {
        "quantity" : "atom_frac"
      },
      {
        "quantity" : "site_frac"
      },
      {
        "quantity" : "comp",
        "precision" : 1e-3
      },
      {
        "quantity" : "comp_n"
      }
    ],
    "storage" : {
      "write_observations" : true,
      "write_trajectory" : true,
      "output_format" : ["csv", "json"]
    }
  },
"driver" : {
    "mode" : "incremental",
    "dependent_runs" : false,
    "motif" : {
     "_configname" : "default",
     "configname" : "SCEL10_2_5_1_3_0_1/48",
     "_configdof" : "path/to/final_state.json"
    },
    "initial_conditions" : {
      "comp_n" : {
        "Ta" : 0.40,
        "W" : 0.50,
        "Va" : 0.10
},
      "temperature" : 600.0,
      "tolerance" : 0.001
    },
    "final_conditions" : {
     "comp_n" : {
        "Ta" : 0.40,
        "W" : 0.50,
        "Va" : 0.10
},
     "temperature" : 600.0,
      "tolerance" : 0.001
    },
    "incremental_conditions" : {
 "comp_n" : {
        "Ta" : 0.00,
        "W" : 0.00,
        "Va" : 0.00
},
      "temperature" : 0.0,
      "tolerance" : 0.001
    }
  }
}

Unfortunately, I am getting "segmentation fault" error. 
The output printed (before encountering the "Segmentation fault") is

-- Read: Monte Carlo settings -- 
from: "/marconi_work/ICT23_CMSP/Dpandey/CASM/WTaVac/metropolis.json"
ensemble: Canonical
method: Metropolis
debug: 1

-- Compiling: /marconi_work/ICT23_CMSP/Dpandey/CASM/WTaVac/basis_sets/bset.default/WTaVac_Clexulator.cc -- 
compile time depends on how many basis functions are included
compile time: 0.0118602 (s)

-- Construct: Canonical Monte Carlo -- 
project: "/marconi_work/ICT23_CMSP/Dpandey/CASM/WTaVac"
formation_energy cluster expansion: formation_energy
      property: formation_energy
      calctype: default
           ref: default
          bset: default
           eci: default
supercell: 
4 0 8
0 4 8
4 4 4

Sampling: 
                quantity     requested_precision
           atom_frac(Ta)                    none
           atom_frac(Va)                    none
            atom_frac(W)                    none
                 comp(a)                   0.001
                 comp(b)                   0.001
              comp_n(Ta)                    none
              comp_n(Va)                    none
               comp_n(W)                    none
        formation_energy                    0.01
        potential_energy                    none
           site_frac(Ta)                    none
           site_frac(Va)                    none
            site_frac(W)                    none

automatic convergence mode?: true

Unit cell for determining equivalent swaps: 
1 0 0
0 1 0
0 0 1

Asymmetric Unit: 
  0: W Ta Va 
    0, 0 0 0

Candidates: (Species, AsymUnit)
  (W, 0)
  (Ta, 0)
  (Va, 0)

Canonical swaps: 
  (W, 0) <-> (Ta, 0)
  (W, 0) <-> (Va, 0)
  (Ta, 0) <-> (Va, 0)

Grand canonical swaps: 
  (W, 0) -> (Ta, 0)
  (W, 0) -> (Va, 0)
  (Ta, 0) -> (W, 0)
  (Ta, 0) -> (Va, 0)
  (Va, 0) -> (W, 0)
  (Va, 0) -> (Ta, 0)

-- Check: For existing calculations -- 
did not find existing calculations

-- Set: Conditions -- 
T: 600
param_composition: [ 0.400000000000, 0.500000000000 ]
param_composition: [ 0.400000000000, 0.500000000000 ]

-- Set: DoF -- 
motif configname: default
using configuration with default occupation...

-- Set: DoF -- 
motif configname: SCEL10_2_5_1_3_0_1/48
using configation: SCEL10_2_5_1_3_0_1/48

Segmentation fault

I can see tag "debug=1" but cannot really point-out the source of error. Is something wrong in my input file or am I missing something? Looking forward for some suggestions.
Thank you and best regards
Dhanshree

**Comment by xivh** [comment]
Can you upload your project?

**Comment by pandeydhanshree** [comment]
Hello
I played around some of the tags in the input file and could resolve the issue. Thank you so much.
With regards
Dhanshree
