### ISSUE TITLE
Configurations that aren't groundstates are marked as being on the hull

### ISSUE THREAD

**Issue by goirijo** [prisms-center/CASMcode#33]
For a ternary system, I queried my energies for composition, hull distance, and whether the configuration is a groundstate or not. The result is several pairs of configurations that have the same composition marked as being on the hull. I suspect that the hull finding routines are not discarding the "top" of the convex hull, and are instead reporting all of the configurations that are part of the full convex hull. For a given pair of "on_hull" configurations with the same composition, the distance between their formation energies matches the reported distance from the hull for the one with higher energy.

For example:

    configname            selected  atom_frac(Cr)  atom_frac(Al)  atom_frac(Ni)  on_hull(MASTER,atom_frac)  hull_dist(MASTER,atom_frac)  formation_energy_per_atom
    SCEL3_3_1_1_0_1_2/1   1         0.66666667     0.33333333     0.00000000     1                          0.00000000                   -0.13121885
    SCEL6_1_6_1_1_0_0/2   1         0.66666667     0.33333333     0.00000000     1                          0.21266172                   0.08144287

**Comment by sriharsha09** [comment]
I think the behaviour is similar in binaries too not just on a ternary axis.

**Comment by bpuchala** [comment]
Yes, this is in need of an update.  See #3 and give your feedback on the best solution.
