### ISSUE TITLE
How to extract POSCAR data

### ISSUE THREAD

**Issue by WalterWhite1611** [prisms-center/CASMcode#347]
I want to extract poscar data from my enumeration calculation.  I selected supercells "ccasm select -t scel --set-on". 
"ccasm info -m SupercellInfo default_poscar",       is it the correct way to write? while I'm getting this error,
-- Error Summary --

-- Errors at location: /properties --
Error: missing required option 'properties'.

{
"properties.ERROR" : [
"Error: missing required option 'properties'."
]
}

ERROR: Error reading SupercellInfo input

**Comment by xivh** [comment]
`ccasm info -m SupercellInfo -i '{"properties": "default_poscar"}'`

But if you want to get the default POSCARs for all of your supercells, you can use `ccasm query -t scel -k default_poscar` after selecting them.

**Comment by RajQuantizedPy** [comment]
yes it works. Thank you so much.

**Comment by WalterWhite1611** [comment]
> `ccasm info -m SupercellInfo -i '{"properties": "default_poscar"}'`
> 
> But if you want to get the default POSCARs for all of your supercells, you can use `ccasm query -t scel -k default_poscar` after selecting them.

yes it works. Thank u so much.
