### ISSUE TITLE
How to enumerate with partial occupancy on atomic sites?

### ISSUE THREAD

**Issue by CrankyBot2001** [prisms-center/CASMcode#349]
Hi, everyone. Can someone guide me how to create input file for enumeration of a unit cell which contains partial occupancy on their atomic site? example for a vesta cif file,
A 0.5000 0.000000 0.000000 0.000000 Biso 1.000000 A
B 0.7500 0.333333 0.666667 0.000000 Biso 1.000000 B
C 1.0 0.333333 0.000000 0.250000 Biso 1.000000        C

**Comment by xivh** [comment]
You can create the prim from a POSCAR with `casm init --prim POSCAR --write-prim`, and then edit the occupants in the prim. See the first example [here](https://prisms-center.github.io/CASMcode_docs/pages/tutorials/Project_Initialization_bash/#occupation_clex).
