### ISSUE TITLE
Energy units in CASM

### ISSUE THREAD

**Issue by darjaved** [prisms-center/CASMcode#360]
Does CASM give the energies as eV/prim, prim can have any number of sites, is vacancy also considered during the formation energy calculation? 

sel.query([comp, Ef, clEf, hull_dist, cl_hull_dist])

above will give me all energies as eV/prim? so, i have to divide the energies by number of sites in prim to get in eV/atom.

**Comment by xivh** [comment]
When you query energy it gives energy per prim. If you want energy per atom, you can query energy_per_atom. If you have vacancies and want energy per site, then you can divide energy by scel_size * number of sites in the prim.
