### ISSUE TITLE
How to use "casm select" to choose a specific configuration 

### ISSUE THREAD

**Issue by kaijiz** [prisms-center/CASMcode#362]
![Screen Shot 2024-05-09 at 5 33 31 PM](https://github.com/prisms-center/CASMcode/assets/126427660/18c85d05-2bec-4abd-91de-f81dc33e581c)

Could you show the detailed commands?

**Comment by xivh** [comment]
`casm select --help`
`casm select --help properties`
`casm select --help operators`

The most basic command you can give it is `casm select --set-on` to select all configurations.
