### ISSUE TITLE
MAGMOM reconciliation leads to wrong results

### ISSUE THREAD

**Issue by tallakahath** [prisms-center/CASMcode#38]
I need to do my own digging to find out *why* this change has happened, but, in a nutshell:

- SPECIES has Mn_u and Mn_d, which share the same alias Mn, but have different MAGMOM +/- 6
- The INCAR (and INCAR.base) somehow end up with 2*-6 rather than 6 -6
- Old version of the code didn't do this

**Comment by tallakahath** [comment]
Or, is this not the spirit of 'alias'? I could solve this on my end by switching from:

```
 POTCAR_DIR_PATH = /home/liz/vasp_potentials/
 SPECIES  ALIAS  POTCAR  POTCAR_LOCATION   MAGMOM
 Mn_u     Mn     1       PAW_PBE/Mn_sv_GW  6
 Mn_d     Mn     1       PAW_PBE/Mn_sv_GW  -6
```

to

```
 POTCAR_DIR_PATH = /home/liz/vasp_potentials/
 SPECIES  ALIAS  POTCAR  POTCAR_LOCATION   MAGMOM
 Mn_u     Mn_u     1       PAW_PBE/Mn_sv_GW  6
 Mn_d     Mn_d     1       PAW_PBE/Mn_sv_GW  -6
```

But I'm not sure what the *intended* operation is.

**Comment by bpuchala** [comment]
This is probably related to #36, right, @skk74?  I think the intended behavior should be that the first option above (with ALIAS being the same) results in ```1*6 1*-6```.

**Comment by tallakahath** [comment]
This is related to the use of 'alias' to get the 'n' in 'n * magmom' part;
the old version used alias but still looped over each *entry* in the sites
related to that alias, which ended up grabbing the right MAGMOM from the
species. I think if we used the actual occupation, not the alias, things
would be fine again?

**Comment by skk74** [comment]
Yep that seems right. My fix was a rather naive one :( sorry if it caused you too many problems. This is related to #36

**Comment by skk74** [comment]
Made a pull request
