### ISSUE TITLE
Monte carlo sampling sometimes records "unknown" as value

### ISSUE THREAD

**Issue by goirijo** [prisms-center/CASMcode#42]
When running grand canonical Monte Carlo, sampling values sometimes get dropped when the cell is not equilibrated. The resulting csv file contains lines with "unknown" instead of numerical values for sampled properties (things like temperature or chemical potential are recorded properly):

    #    is_equilibrated N_equil_samples is_converged N_avg_samples T Beta <potential_energy>
    0  0  0  10000  3575.00000000  3.24601565  unknown

The resulting json file results in an empty dictionary ```{}``` entry instead of a value:

    {
        "<potential_energy>":[
        0.0,
        0.0,
        {
        },
        0.0
    }

For every case I've encountered so far, simply rerunning the simulation solves the issue, and the same conditions appear as converged without actually changing any of the settings. I think it makes more sense to have real value recorded than "unknown", even if the run isn't converged. The missing entries make it very difficult when dealing with multiple runs that need to have their data combined.

**Comment by bpuchala** [comment]
I think including the non-equilibrated average value in the same column has the potential to lead to a lot of people mistakenly using the results, plus the way the precision quantity is calculated becomes questionable. Can we figure out a different way? Here are a couple options:

In automatic convergence mode, if a calculation never equilibrates before reaching a cutoff:

1) leave as is, maybe printing something easier to parse like NaN.
2) don't output results from that calculation, just skip to the next one, but write the observations, even if not requested originally, so they can be inspected, and maybe some warning message or file to alert the user.
3) after getting aborted, increment the requested precision by a factor of X until the equilibration criteria can be satisified, then output the results

I think my preference is (2).
