### ISSUE TITLE
properties.calc.json unreadable if ISPIN = 2 and LORBIT = 0

### ISSUE THREAD

**Issue by max-radin** [prisms-center/CASMcode#45]
If ISPIN = 2 and LORBIT = 0, then casm cannot read the `properties.calc.json` files produced by the vaspwrapper because the elements of `relaxed_mag_basis` are all `null`.

**Comment by bpuchala** [comment]
@tallakahath Could you address this?

**Comment by tallakahath** [comment]
Looking into it now

**Comment by tallakahath** [comment]
OK, for now, I've changed it such that unless ispin and lorbit are set properly, relaxed_magmom and relaxed_mag_basis aren't included in properties.calc.json. If ispin==2 then a relaxed_magmom is captured, and if lorbit == 1, 2, 11, 12, then a relaxed_mag_basis is captured.

I'll be fixing issue #44 and then pushing an updated branch for immediate merging.
