### ISSUE TITLE
Monte Carlo simulation fails, if I want to start a run with an existing run.

### ISSUE THREAD

**Issue by mxgrabowski** [prisms-center/CASMcode#51]
My first run in the folder was at constant chemical potential and raising temperature from 10K to 1200K. Now, I want to continue this run up to 2000K. So I only changed the end temperature to 2000 in the input file. However, the run stops and I get a core dump. This is my error:

-- Check: For existing calculations -- 
update: "/home/users/grabomqf/DFT/vasp5.4/ClusterExpansion/Ni-Re/monte_T1200_CP-0.3/results.json"
found existing calculations
will begin with condition 60

-- Set: DoF -- 
Using: /home/users/grabomqf/DFT/vasp5.4/ClusterExpansion/Ni-Re/monte_T1200_CP-0.3/conditions.59/final_state.json

casm: include/casm/external/Eigen/src/Core/Dot.h:71: typename Eigen::internal::scalar_product_traits<typename Eigen::internal::traits<T>::Scalar, typename Eigen::internal::traits<OtherDerived>::Scalar>::ReturnType Eigen::MatrixBase<Derived>::dot(const Eigen::MatrixBase<OtherDerived>&) const [with OtherDerived = Eigen::Matrix<double, -1, 1>; Derived = Eigen::Matrix<double, -1, 1>; typename Eigen::internal::scalar_product_traits<typename Eigen::internal::traits<T>::Scalar, typename Eigen::internal::traits<OtherDerived>::Scalar>::ReturnType = double]: Assertion `size() == other.size()' failed.

I am using the version 0.2.0+b20bd4e.changes (master branch in september 16).

Best regards,
Maximilian

**Comment by bpuchala** [comment]
I am finding that it crashes when `"dependent_runs": true`, but not `"dependent_runs": false`. Can you confirm that is the case for you as well?

**Comment by mxgrabowski** [comment]
This is the case for me as well. I was able to start the runs. However, with this input CASM will rerun the temperatures I already calculated, right?

Thanks for the help!

**Comment by bpuchala** [comment]
I thought I was reproducing this issue, but it was actually only with the canonical Monte Carlo code I was testing at the time. I've pushed a PR (#53) to fix that issue, but I haven't been able to reproduce this issue using grand canonical Monte Carlo. Could you possibly send me an archive of your project, privately, that I could use to debug?

**Comment by mxgrabowski** [comment]
I can send an archive of my project. What are the things you need, so I may only pack the important things to keep everything small. How should I send you the archive?

**Comment by bpuchala** [comment]
You can email me at `bpuchala@umich.edu`. It should be enough for me to recreate your monte carlo run if you send me the output of
```
tar -czvf proj.tar.gz `casm files -o STDOUT`
```
plus your monte carlo input file and the casm version.
