### ISSUE TITLE
casm: error while loading shared libraries: libcasm.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mxgrabowski** [prisms-center/CASMcode#55]
So I have this issue a bit longer and I had it for the version 0.2.0+b20bd4e.changes and for 0.2.1+e413032.changes. I didn't post it as I had a solution, that worked for me, but might not be the best.

Before installing, I set the `$CASM_PREFIX` and `$CASM_BOOST_PREFIX` and the installation works out fine.However, when using `casm` or similar python commads, I get the error

casm: error while loading shared libraries: libcasm.so: cannot open shared object file: No such file or directory

The files `libcasm.so` and `libccasm.so` should be located in CASMcode/lib/. Both files are there in my case.
Some time ago, I figured out that I can solve this issue by slightly editing the `casm.py` file.

In line 53 of `casm.py`, it tries to load the `libccasm.so`. So before loading, I enter the directory, where the `libccasm.so` is located, load it and go back to the prior directory.

Some how this works and I won't get the error. Also, I'm not sure, while the error says it cannot load `libcasm.so` and I have to apply the fix for `libccasm.so`.

I don't know, if something may be wrong with my installation or with setting some variables. I will try to get you as much information as you need from my part.

**Comment by hegdevinayi** [comment]
@mxgrabowski Doesn't adding /path/to/CASMcode/lib to your $LD_LIBRARY_PATH (if you're on Linux) fix this problem?

**Comment by mxgrabowski** [comment]
Hey, 
this seems to have fixed it! Thanks!
