### ISSUE TITLE
Install CASM on supercomputer

### ISSUE THREAD

**Issue by bpuchala** [prisms-center/CASMcode#62]
From a user:

> I have installed the CASM code in my local machine. I could successfully  proceed till the third step (generating configuration). Since I dont have vasp in my local system (vasp is installed in supercomputer) I am unable to calculate configuration properties. Is there any other way to use CASM code from my local machine to run vasp calculations in super computer?

**Comment by bpuchala** [comment]
There are a couple options:

1) Ask the system administrator to install CASM in a standard location
-  Often they will be happy to do this, and then everyone else can use CASM on the system also.

2) Install CASM in your user space
- By setting your environment appropriately CASM can be installed and executed from your user directory
- Relevant environment variables are covered in 'INSTALL.md', but as a summary:
  - create a directory where you will install CASM and other software in your user directory, for instance `$HOME/software/casm_0.2.1`
  - Create a script to set your environment using the 'casmenv.sh' file found in the root of the github repository:
  - `cp casmenv.sh $HOME/software/casm_0.2.1/casmenv.sh`, then edit variables as necessary:
    - `CASM_PREFIX=$HOME/software` 
    - Set boost environment variables to locate boost
    - `casmenv.sh` should then be able set your `PATH` and `PYTHONPATH` and other commonly necessary variables so that the `casm` executable and `casm` Python modules can be found
  - Set your environment using `source $HOME/software/casm_0.2.1/casmenv.sh`
  - Check the configuration using `scons configure`
  - If everything is OK, install: `scons install -j <number of processors>`
  - Whenever you logout and log back in you will need to reset your environment using `source $HOME/software/casm_0.2.1/casmenv.sh`. To automate this, you could add it as a line in your `.bashrc` & `.bash_profile`.

3) Copy files back and forth
- `casm update` reads calculated properties from the `properties.calc.json` file located in a configuration directory (`training_data/<configname>/<calctype.name>/properties.calc.json`).  This file has the same format no matter how you did the calculations. To see the format look at `casm format --vasp`.  
- To use VASP to generate these files without installing CASM on a particular machine:
  - setup all the necessary settings files in `training_data/settings/<calctype.name>`
  - copy VASP POTCAR files to your location machine and set your `SPECIES` file to use this location
  - use `casm-calc --setup -c <selection>` to create the appropriate VASP input files for all the configurations in a CASM selection. (You can use `ALL` for all configurations, or `MASTER` for the currently selected configurations in your default master selection, or a custom selection output from `casm select` with the `-o` option).
  - use rsync to copy your `training_data` directory from your location machine to the supercomputer
  - submit jobs and complete VASP calculations however you normally would
  - use rsync to copy the results back to your local machine
  - use `casm-calc --report -c ALL` to create `properties.calc.json` files from the VASP output
  - use `casm update -c ALL` to read in the calculation results

**Comment by Anu-Maria** [comment]
I have started with the third method. When I run the command 'casm-calc --setup -c ALL' I am getting only the POSCAR files for all the configurations. May I know whether it will generate the other VASP input files (POTCAR, KPOINTS etc.). If it is created, where can I find it?.
I have copied the VASP POTCAR files and set the SPECIES file to use the POTCAR location

**Comment by bpuchala** [comment]
Please open a new issue for this and specify which version you are using and include any messages that are printed when you execute the command. It would also be useful to include the directory structure from for instance 'ls -R training_data'.

**Comment by yongwshin** [comment]
Hi CASM team. I have a similar issue when I followed method 3. I can initiate the project and can make VASP input files using 'casm-calc --setup -c ALL'. I calculated individual structures on the supercomputer and then copy to my local machine in; $project/tranining_data/<config>/calctype.default 

However, when I used command 'casm-calc --report -c ALL', casm complained the computation as; 'Please verify that it contains a completed calculation'. Would you let me know the instructions to create properties.calc.json?

**Comment by bpuchala** [comment]
The ```casm-calc --report ``` command will look for VASP output in ```run.final``` directories, i.e.: ```training_data/<configname>/<calctype.name>/run.final```. This seems to be lacking from the documentation and the previous description.

**Comment by DKasdorf** [comment]
Hello CASM-developers,
I have a similar problem: I could successfully install casm (via conda) in my user space on a supercomputer. Since i dont know how to write a proper relax.json file for our slurm job management, ive tried to manually start the jobs from the generated VASP input files.
Even though i ran the jobs in _training_data/<configname>/<calctype.name>/run.final_ the $_casm-calc --report_ command is failing:
It tries to write the properties.calc.json files for the configurations with a _run.final_ directory but then aborts with: "Unable to report properties for directory ...." and "Please verify that it contains a completed calculation".
casm version: v0.3.dev-258-g23069d
