### ISSUE TITLE
Generation of VASP inputs

### ISSUE THREAD

**Issue by Anu-Maria** [prisms-center/CASMcode#64]
**I am using the CASM code installed in the local machine as you have discussed in the third part of the issue # 62. When I run the command 'casm-calc --setup -c ALL' I am getting only the POSCAR files for all the configurations. May I know whether it will generate the other VASP input files (POTCAR, KPOINTS etc.). If it is created, where can I find it?.**

**I have copied the VASP POTCAR files and set the SPECIES file to use the POTCAR location**

**I am using CASM version: 0.2.1+e413032.changes
 g++ 4.8.5 and boost 1.55 (compiler with c++11)

When I run the command 'casm-calc --setup -c ALL' I am getting the result as follows:**
anu@anu-HP-Z640-Workstation:~/Desktop/newcasmtest/training_data/settings/calctype.default$ casm-calc --setup -c ALL
-- Construct: CASM Project -- 
from: "/home/anu/Desktop/newcasmtest"

-- Load project data -- 
read: "/home/anu/Desktop/newcasmtest/.casm/composition_axes.json"
read: "/home/anu/Desktop/newcasmtest/training_data/SCEL"
read: "/home/anu/Desktop/newcasmtest/.casm/config_list.json"

Construct a casm.vaspwrapper.Relax instance:
  Input directory: /home/anu/Desktop/newcasmtest/training_data/SCEL1_1_1_1_0_0_0/0
  Configuration: SCEL1_1_1_1_0_0_0/0
  Reading CASM settings
  Calculations directory: /home/anu/Desktop/newcasmtest/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default
  Reading relax.json settings file
  Read settings from: /home/anu/Desktop/newcasmtest/training_data/settings/calctype.default/relax.json
  DONE

Setting up VASP input files: /home/anu/Desktop/newcasmtest/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default
  Reading KPOINTS: /home/anu/Desktop/newcasmtest/training_data/settings/calctype.default/KPOINTS
  Reading KPOINTS reference POSCAR: /home/anu/Desktop/newcasmtest/training_data/settings/calctype.default/POSCAR
  Reading SPECIES: /home/anu/Desktop/newcasmtest/training_data/settings/calctype.default/SPECIES
Length of values != length of tags + 4.
values = ['Zr2', 'Zr', '0']
tags = []

**When I run the command 'ls -R training_data', I am getting this:**
anu@anu-HP-Z640-Workstation:~/Desktop/newcasmtest$ ls -R training_data
training_data:
SCEL               SCEL2_1_2_1_0_0_0  SCEL3_1_3_1_2_0_0  SCEL3_3_1_1_0_2_2  SCEL4_1_2_2_1_0_0  SCEL4_1_4_1_2_0_0  SCEL4_2_2_1_0_1_0  settings
SCEL1_1_1_1_0_0_0  SCEL2_1_2_1_1_0_0  SCEL3_3_1_1_0_0_1  SCEL4_1_1_4_0_0_0  SCEL4_1_4_1_0_0_0  SCEL4_2_2_1_0_0_0  SCEL4_2_2_1_0_1_1
SCEL2_1_1_2_0_0_0  SCEL3_1_1_3_0_0_0  SCEL3_3_1_1_0_0_2  SCEL4_1_2_2_0_0_0  SCEL4_1_4_1_1_0_0  SCEL4_2_2_1_0_0_1  SCEL4_4_1_1_0_3_2

training_data/SCEL1_1_1_1_0_0_0:
0  1  2  LAT

training_data/SCEL1_1_1_1_0_0_0/0:
calctype.default  POS

training_data/SCEL1_1_1_1_0_0_0/0/calctype.default:

training_data/SCEL1_1_1_1_0_0_0/1:
POS

training_data/SCEL1_1_1_1_0_0_0/2:
POS

training_data/SCEL2_1_1_2_0_0_0:
0  1  2  LAT

training_data/SCEL2_1_1_2_0_0_0/0:
POS

training_data/SCEL2_1_1_2_0_0_0/1:
POS

training_data/SCEL2_1_1_2_0_0_0/2:
POS

training_data/SCEL2_1_2_1_0_0_0:
0  1  2  3  LAT

training_data/SCEL2_1_2_1_0_0_0/0:
POS

training_data/SCEL2_1_2_1_0_0_0/1:
POS

training_data/SCEL2_1_2_1_0_0_0/2:
POS

training_data/SCEL2_1_2_1_0_0_0/3:
POS

training_data/SCEL2_1_2_1_1_0_0:
0  1  2  LAT

training_data/SCEL2_1_2_1_1_0_0/0:
POS

training_data/SCEL2_1_2_1_1_0_0/1:
POS

training_data/SCEL2_1_2_1_1_0_0/2:
POS

training_data/SCEL3_1_1_3_0_0_0:
0  1  2  3  4  5  6  7  8  9  LAT

training_data/SCEL3_1_1_3_0_0_0/0:
POS

training_data/SCEL3_1_1_3_0_0_0/1:
POS

training_data/SCEL3_1_1_3_0_0_0/2:
POS

training_data/SCEL3_1_1_3_0_0_0/3:
POS

training_data/SCEL3_1_1_3_0_0_0/4:
POS

training_data/SCEL3_1_1_3_0_0_0/5:
POS

training_data/SCEL3_1_1_3_0_0_0/6:
POS

training_data/SCEL3_1_1_3_0_0_0/7:
POS

training_data/SCEL3_1_1_3_0_0_0/8:
POS

training_data/SCEL3_1_1_3_0_0_0/9:
POS

training_data/SCEL3_1_3_1_2_0_0:
0  1  10  11  12  13  14  15  2  3  4  5  6  7  8  9  LAT

training_data/SCEL3_1_3_1_2_0_0/0:
POS

training_data/SCEL3_1_3_1_2_0_0/1:
POS

training_data/SCEL3_1_3_1_2_0_0/10:
POS

training_data/SCEL3_1_3_1_2_0_0/11:
POS

training_data/SCEL3_1_3_1_2_0_0/12:
POS

training_data/SCEL3_1_3_1_2_0_0/13:
POS

training_data/SCEL3_1_3_1_2_0_0/14:
POS

training_data/SCEL3_1_3_1_2_0_0/15:
POS

training_data/SCEL3_1_3_1_2_0_0/2:
POS

training_data/SCEL3_1_3_1_2_0_0/3:
POS

training_data/SCEL3_1_3_1_2_0_0/4:
POS

training_data/SCEL3_1_3_1_2_0_0/5:
POS

training_data/SCEL3_1_3_1_2_0_0/6:
POS

training_data/SCEL3_1_3_1_2_0_0/7:
POS

training_data/SCEL3_1_3_1_2_0_0/8:
POS

training_data/SCEL3_1_3_1_2_0_0/9:
POS

training_data/SCEL3_3_1_1_0_0_1:
0  1  2  3  4  5  6  7  8  9  LAT

training_data/SCEL3_3_1_1_0_0_1/0:
POS

training_data/SCEL3_3_1_1_0_0_1/1:
POS

training_data/SCEL3_3_1_1_0_0_1/2:
POS

training_data/SCEL3_3_1_1_0_0_1/3:
POS

training_data/SCEL3_3_1_1_0_0_1/4:
POS

training_data/SCEL3_3_1_1_0_0_1/5:
POS

training_data/SCEL3_3_1_1_0_0_1/6:
POS

training_data/SCEL3_3_1_1_0_0_1/7:
POS

training_data/SCEL3_3_1_1_0_0_1/8:
POS

training_data/SCEL3_3_1_1_0_0_1/9:
POS

training_data/SCEL3_3_1_1_0_0_2:
0  1  2  3  4  5  6  7  8  9  LAT

training_data/SCEL3_3_1_1_0_0_2/0:
POS

training_data/SCEL3_3_1_1_0_0_2/1:
POS

training_data/SCEL3_3_1_1_0_0_2/2:
POS

training_data/SCEL3_3_1_1_0_0_2/3:
POS

training_data/SCEL3_3_1_1_0_0_2/4:
POS

training_data/SCEL3_3_1_1_0_0_2/5:
POS

training_data/SCEL3_3_1_1_0_0_2/6:
POS

training_data/SCEL3_3_1_1_0_0_2/7:
POS

training_data/SCEL3_3_1_1_0_0_2/8:
POS

training_data/SCEL3_3_1_1_0_0_2/9:
POS

training_data/SCEL3_3_1_1_0_2_2:
0  1  2  3  4  5  6  7  8  9  LAT

training_data/SCEL3_3_1_1_0_2_2/0:
POS

training_data/SCEL3_3_1_1_0_2_2/1:
POS

training_data/SCEL3_3_1_1_0_2_2/2:
POS

training_data/SCEL3_3_1_1_0_2_2/3:
POS

training_data/SCEL3_3_1_1_0_2_2/4:
POS

training_data/SCEL3_3_1_1_0_2_2/5:
POS

training_data/SCEL3_3_1_1_0_2_2/6:
POS

training_data/SCEL3_3_1_1_0_2_2/7:
POS

training_data/SCEL3_3_1_1_0_2_2/8:
POS

training_data/SCEL3_3_1_1_0_2_2/9:
POS

training_data/SCEL4_1_1_4_0_0_0:
0  1  10  11  12  13  14  15  16  17  18  19  2  20  21  22  23  3  4  5  6  7  8  9  LAT

training_data/SCEL4_1_1_4_0_0_0/0:
POS

training_data/SCEL4_1_1_4_0_0_0/1:
POS

training_data/SCEL4_1_1_4_0_0_0/10:
POS

training_data/SCEL4_1_1_4_0_0_0/11:
POS

training_data/SCEL4_1_1_4_0_0_0/12:
POS

training_data/SCEL4_1_1_4_0_0_0/13:
POS

training_data/SCEL4_1_1_4_0_0_0/14:
POS

training_data/SCEL4_1_1_4_0_0_0/15:
POS

training_data/SCEL4_1_1_4_0_0_0/16:
POS

training_data/SCEL4_1_1_4_0_0_0/17:
POS

training_data/SCEL4_1_1_4_0_0_0/18:
POS

training_data/SCEL4_1_1_4_0_0_0/19:
POS

training_data/SCEL4_1_1_4_0_0_0/2:
POS

training_data/SCEL4_1_1_4_0_0_0/20:
POS

training_data/SCEL4_1_1_4_0_0_0/21:
POS

training_data/SCEL4_1_1_4_0_0_0/22:
POS

training_data/SCEL4_1_1_4_0_0_0/23:
POS

training_data/SCEL4_1_1_4_0_0_0/3:
POS

training_data/SCEL4_1_1_4_0_0_0/4:
POS

training_data/SCEL4_1_1_4_0_0_0/5:
POS

training_data/SCEL4_1_1_4_0_0_0/6:
POS

training_data/SCEL4_1_1_4_0_0_0/7:
POS

training_data/SCEL4_1_1_4_0_0_0/8:
POS

training_data/SCEL4_1_1_4_0_0_0/9:
POS

training_data/SCEL4_1_2_2_0_0_0:
0  1  10  11  12  13  14  15  16  17  18  19  2  20  3  4  5  6  7  8  9  LAT

training_data/SCEL4_1_2_2_0_0_0/0:
POS

training_data/SCEL4_1_2_2_0_0_0/1:
POS

training_data/SCEL4_1_2_2_0_0_0/10:
POS

training_data/SCEL4_1_2_2_0_0_0/11:
POS

training_data/SCEL4_1_2_2_0_0_0/12:
POS

training_data/SCEL4_1_2_2_0_0_0/13:
POS

training_data/SCEL4_1_2_2_0_0_0/14:
POS

training_data/SCEL4_1_2_2_0_0_0/15:
POS

training_data/SCEL4_1_2_2_0_0_0/16:
POS

training_data/SCEL4_1_2_2_0_0_0/17:
POS

training_data/SCEL4_1_2_2_0_0_0/18:
POS

training_data/SCEL4_1_2_2_0_0_0/19:
POS

training_data/SCEL4_1_2_2_0_0_0/2:
POS

training_data/SCEL4_1_2_2_0_0_0/20:
POS

training_data/SCEL4_1_2_2_0_0_0/3:
POS

training_data/SCEL4_1_2_2_0_0_0/4:
POS

training_data/SCEL4_1_2_2_0_0_0/5:
POS

training_data/SCEL4_1_2_2_0_0_0/6:
POS

training_data/SCEL4_1_2_2_0_0_0/7:
POS

training_data/SCEL4_1_2_2_0_0_0/8:
POS

training_data/SCEL4_1_2_2_0_0_0/9:
POS

training_data/SCEL4_1_2_2_1_0_0:
0  1  10  11  12  13  14  15  16  17  18  19  2  20  21  22  23  3  4  5  6  7  8  9  LAT

training_data/SCEL4_1_2_2_1_0_0/0:
POS

training_data/SCEL4_1_2_2_1_0_0/1:
POS

training_data/SCEL4_1_2_2_1_0_0/10:
POS

training_data/SCEL4_1_2_2_1_0_0/11:
POS

training_data/SCEL4_1_2_2_1_0_0/12:
POS

training_data/SCEL4_1_2_2_1_0_0/13:
POS

training_data/SCEL4_1_2_2_1_0_0/14:
POS

training_data/SCEL4_1_2_2_1_0_0/15:
POS

training_data/SCEL4_1_2_2_1_0_0/16:
POS

training_data/SCEL4_1_2_2_1_0_0/17:
POS

training_data/SCEL4_1_2_2_1_0_0/18:
POS

training_data/SCEL4_1_2_2_1_0_0/19:
POS

training_data/SCEL4_1_2_2_1_0_0/2:
POS

training_data/SCEL4_1_2_2_1_0_0/20:
POS

training_data/SCEL4_1_2_2_1_0_0/21:
POS

training_data/SCEL4_1_2_2_1_0_0/22:
POS

training_data/SCEL4_1_2_2_1_0_0/23:
POS

training_data/SCEL4_1_2_2_1_0_0/3:
POS

training_data/SCEL4_1_2_2_1_0_0/4:
POS

training_data/SCEL4_1_2_2_1_0_0/5:
POS

training_data/SCEL4_1_2_2_1_0_0/6:
POS

training_data/SCEL4_1_2_2_1_0_0/7:
POS

training_data/SCEL4_1_2_2_1_0_0/8:
POS

training_data/SCEL4_1_2_2_1_0_0/9:
POS

training_data/SCEL4_1_4_1_0_0_0:
0  1  10  11  12  13  14  15  16  17  18  19  2  20  21  22  23  24  25  26  3  4  5  6  7  8  9  LAT

training_data/SCEL4_1_4_1_0_0_0/0:
POS

training_data/SCEL4_1_4_1_0_0_0/1:
POS

training_data/SCEL4_1_4_1_0_0_0/10:
POS

training_data/SCEL4_1_4_1_0_0_0/11:
POS

training_data/SCEL4_1_4_1_0_0_0/12:
POS

training_data/SCEL4_1_4_1_0_0_0/13:
POS

training_data/SCEL4_1_4_1_0_0_0/14:
POS

training_data/SCEL4_1_4_1_0_0_0/15:
POS

training_data/SCEL4_1_4_1_0_0_0/16:
POS

training_data/SCEL4_1_4_1_0_0_0/17:
POS

training_data/SCEL4_1_4_1_0_0_0/18:
POS

training_data/SCEL4_1_4_1_0_0_0/19:
POS

training_data/SCEL4_1_4_1_0_0_0/2:
POS

training_data/SCEL4_1_4_1_0_0_0/20:
POS

training_data/SCEL4_1_4_1_0_0_0/21:
POS

training_data/SCEL4_1_4_1_0_0_0/22:
POS

training_data/SCEL4_1_4_1_0_0_0/23:
POS

training_data/SCEL4_1_4_1_0_0_0/24:
POS

training_data/SCEL4_1_4_1_0_0_0/25:
POS

training_data/SCEL4_1_4_1_0_0_0/26:
POS

training_data/SCEL4_1_4_1_0_0_0/3:
POS

training_data/SCEL4_1_4_1_0_0_0/4:
POS

training_data/SCEL4_1_4_1_0_0_0/5:
POS

training_data/SCEL4_1_4_1_0_0_0/6:
POS

training_data/SCEL4_1_4_1_0_0_0/7:
POS

training_data/SCEL4_1_4_1_0_0_0/8:
POS

training_data/SCEL4_1_4_1_0_0_0/9:
POS

training_data/SCEL4_1_4_1_1_0_0:
0  1  10  11  12  13  14  15  16  17  18  19  2  20  21  22  23  24  25  26  27  28  29  3  30  31  32  33  34  35  36  37  38  39  4  40  41  5  6  7  8  9  LAT

training_data/SCEL4_1_4_1_1_0_0/0:
POS

training_data/SCEL4_1_4_1_1_0_0/1:
POS

training_data/SCEL4_1_4_1_1_0_0/10:
POS

training_data/SCEL4_1_4_1_1_0_0/11:
POS

training_data/SCEL4_1_4_1_1_0_0/12:
POS

training_data/SCEL4_1_4_1_1_0_0/13:
POS

training_data/SCEL4_1_4_1_1_0_0/14:
POS

training_data/SCEL4_1_4_1_1_0_0/15:
POS

training_data/SCEL4_1_4_1_1_0_0/16:
POS

training_data/SCEL4_1_4_1_1_0_0/17:
POS

training_data/SCEL4_1_4_1_1_0_0/18:
POS

training_data/SCEL4_1_4_1_1_0_0/19:
POS

training_data/SCEL4_1_4_1_1_0_0/2:
POS

training_data/SCEL4_1_4_1_1_0_0/20:
POS

training_data/SCEL4_1_4_1_1_0_0/21:
POS

training_data/SCEL4_1_4_1_1_0_0/22:
POS

training_data/SCEL4_1_4_1_1_0_0/23:
POS

training_data/SCEL4_1_4_1_1_0_0/24:
POS

training_data/SCEL4_1_4_1_1_0_0/25:
POS

training_data/SCEL4_1_4_1_1_0_0/26:
POS

training_data/SCEL4_1_4_1_1_0_0/27:
POS

training_data/SCEL4_1_4_1_1_0_0/28:
POS

training_data/SCEL4_1_4_1_1_0_0/29:
POS

training_data/SCEL4_1_4_1_1_0_0/3:
POS

training_data/SCEL4_1_4_1_1_0_0/30:
POS

training_data/SCEL4_1_4_1_1_0_0/31:
POS

training_data/SCEL4_1_4_1_1_0_0/32:
POS

training_data/SCEL4_1_4_1_1_0_0/33:
POS

training_data/SCEL4_1_4_1_1_0_0/34:
POS

training_data/SCEL4_1_4_1_1_0_0/35:
POS

training_data/SCEL4_1_4_1_1_0_0/36:
POS

training_data/SCEL4_1_4_1_1_0_0/37:
POS

training_data/SCEL4_1_4_1_1_0_0/38:
POS

training_data/SCEL4_1_4_1_1_0_0/39:
POS

training_data/SCEL4_1_4_1_1_0_0/4:
POS

training_data/SCEL4_1_4_1_1_0_0/40:
POS

training_data/SCEL4_1_4_1_1_0_0/41:
POS

training_data/SCEL4_1_4_1_1_0_0/5:
POS

training_data/SCEL4_1_4_1_1_0_0/6:
POS

training_data/SCEL4_1_4_1_1_0_0/7:
POS

training_data/SCEL4_1_4_1_1_0_0/8:
POS

training_data/SCEL4_1_4_1_1_0_0/9:
POS

training_data/SCEL4_1_4_1_2_0_0:
0  1  10  11  12  13  14  15  16  17  18  19  2  20  21  22  23  3  4  5  6  7  8  9  LAT

training_data/SCEL4_1_4_1_2_0_0/0:
POS

training_data/SCEL4_1_4_1_2_0_0/1:
POS

training_data/SCEL4_1_4_1_2_0_0/10:
POS

training_data/SCEL4_1_4_1_2_0_0/11:
POS

training_data/SCEL4_1_4_1_2_0_0/12:
POS

training_data/SCEL4_1_4_1_2_0_0/13:
POS

training_data/SCEL4_1_4_1_2_0_0/14:
POS

training_data/SCEL4_1_4_1_2_0_0/15:
POS

training_data/SCEL4_1_4_1_2_0_0/16:
POS

training_data/SCEL4_1_4_1_2_0_0/17:
POS

training_data/SCEL4_1_4_1_2_0_0/18:
POS

training_data/SCEL4_1_4_1_2_0_0/19:
POS

training_data/SCEL4_1_4_1_2_0_0/2:
POS

training_data/SCEL4_1_4_1_2_0_0/20:
POS

training_data/SCEL4_1_4_1_2_0_0/21:
POS

training_data/SCEL4_1_4_1_2_0_0/22:
POS

training_data/SCEL4_1_4_1_2_0_0/23:
POS

training_data/SCEL4_1_4_1_2_0_0/3:
POS

training_data/SCEL4_1_4_1_2_0_0/4:
POS

training_data/SCEL4_1_4_1_2_0_0/5:
POS

training_data/SCEL4_1_4_1_2_0_0/6:
POS

training_data/SCEL4_1_4_1_2_0_0/7:
POS

training_data/SCEL4_1_4_1_2_0_0/8:
POS

training_data/SCEL4_1_4_1_2_0_0/9:
POS

training_data/SCEL4_2_2_1_0_0_0:
0  1  10  11  12  13  14  2  3  4  5  6  7  8  9  LAT

training_data/SCEL4_2_2_1_0_0_0/0:
POS

training_data/SCEL4_2_2_1_0_0_0/1:
POS

training_data/SCEL4_2_2_1_0_0_0/10:
POS

training_data/SCEL4_2_2_1_0_0_0/11:
POS

training_data/SCEL4_2_2_1_0_0_0/12:
POS

training_data/SCEL4_2_2_1_0_0_0/13:
POS

training_data/SCEL4_2_2_1_0_0_0/14:
POS

training_data/SCEL4_2_2_1_0_0_0/2:
POS

training_data/SCEL4_2_2_1_0_0_0/3:
POS

training_data/SCEL4_2_2_1_0_0_0/4:
POS

training_data/SCEL4_2_2_1_0_0_0/5:
POS

training_data/SCEL4_2_2_1_0_0_0/6:
POS

training_data/SCEL4_2_2_1_0_0_0/7:
POS

training_data/SCEL4_2_2_1_0_0_0/8:
POS

training_data/SCEL4_2_2_1_0_0_0/9:
POS

training_data/SCEL4_2_2_1_0_0_1:
0  1  10  11  12  13  14  15  16  17  18  19  2  20  21  22  23  24  25  26  3  4  5  6  7  8  9  LAT

training_data/SCEL4_2_2_1_0_0_1/0:
POS

training_data/SCEL4_2_2_1_0_0_1/1:
POS

training_data/SCEL4_2_2_1_0_0_1/10:
POS

training_data/SCEL4_2_2_1_0_0_1/11:
POS

training_data/SCEL4_2_2_1_0_0_1/12:
POS

training_data/SCEL4_2_2_1_0_0_1/13:
POS

training_data/SCEL4_2_2_1_0_0_1/14:
POS

training_data/SCEL4_2_2_1_0_0_1/15:
POS

training_data/SCEL4_2_2_1_0_0_1/16:
POS

training_data/SCEL4_2_2_1_0_0_1/17:
POS

training_data/SCEL4_2_2_1_0_0_1/18:
POS

training_data/SCEL4_2_2_1_0_0_1/19:
POS

training_data/SCEL4_2_2_1_0_0_1/2:
POS

training_data/SCEL4_2_2_1_0_0_1/20:
POS

training_data/SCEL4_2_2_1_0_0_1/21:
POS

training_data/SCEL4_2_2_1_0_0_1/22:
POS

training_data/SCEL4_2_2_1_0_0_1/23:
POS

training_data/SCEL4_2_2_1_0_0_1/24:
POS

training_data/SCEL4_2_2_1_0_0_1/25:
POS

training_data/SCEL4_2_2_1_0_0_1/26:
POS

training_data/SCEL4_2_2_1_0_0_1/3:
POS

training_data/SCEL4_2_2_1_0_0_1/4:
POS

training_data/SCEL4_2_2_1_0_0_1/5:
POS

training_data/SCEL4_2_2_1_0_0_1/6:
POS

training_data/SCEL4_2_2_1_0_0_1/7:
POS

training_data/SCEL4_2_2_1_0_0_1/8:
POS

training_data/SCEL4_2_2_1_0_0_1/9:
POS

training_data/SCEL4_2_2_1_0_1_0:
0  1  10  11  12  13  14  15  16  17  2  3  4  5  6  7  8  9  LAT

training_data/SCEL4_2_2_1_0_1_0/0:
POS

training_data/SCEL4_2_2_1_0_1_0/1:
POS

training_data/SCEL4_2_2_1_0_1_0/10:
POS

training_data/SCEL4_2_2_1_0_1_0/11:
POS

training_data/SCEL4_2_2_1_0_1_0/12:
POS

training_data/SCEL4_2_2_1_0_1_0/13:
POS

training_data/SCEL4_2_2_1_0_1_0/14:
POS

training_data/SCEL4_2_2_1_0_1_0/15:
POS

training_data/SCEL4_2_2_1_0_1_0/16:
POS

training_data/SCEL4_2_2_1_0_1_0/17:
POS

training_data/SCEL4_2_2_1_0_1_0/2:
POS

training_data/SCEL4_2_2_1_0_1_0/3:
POS

training_data/SCEL4_2_2_1_0_1_0/4:
POS

training_data/SCEL4_2_2_1_0_1_0/5:
POS

training_data/SCEL4_2_2_1_0_1_0/6:
POS

training_data/SCEL4_2_2_1_0_1_0/7:
POS

training_data/SCEL4_2_2_1_0_1_0/8:
POS

training_data/SCEL4_2_2_1_0_1_0/9:
POS

training_data/SCEL4_2_2_1_0_1_1:
0  1  10  11  12  13  14  15  16  17  18  19  2  20  3  4  5  6  7  8  9  LAT

training_data/SCEL4_2_2_1_0_1_1/0:
POS

training_data/SCEL4_2_2_1_0_1_1/1:
POS

training_data/SCEL4_2_2_1_0_1_1/10:
POS

training_data/SCEL4_2_2_1_0_1_1/11:
POS

training_data/SCEL4_2_2_1_0_1_1/12:
POS

training_data/SCEL4_2_2_1_0_1_1/13:
POS

training_data/SCEL4_2_2_1_0_1_1/14:
POS

training_data/SCEL4_2_2_1_0_1_1/15:
POS

training_data/SCEL4_2_2_1_0_1_1/16:
POS

training_data/SCEL4_2_2_1_0_1_1/17:
POS

training_data/SCEL4_2_2_1_0_1_1/18:
POS

training_data/SCEL4_2_2_1_0_1_1/19:
POS

training_data/SCEL4_2_2_1_0_1_1/2:
POS

training_data/SCEL4_2_2_1_0_1_1/20:
POS

training_data/SCEL4_2_2_1_0_1_1/3:
POS

training_data/SCEL4_2_2_1_0_1_1/4:
POS

training_data/SCEL4_2_2_1_0_1_1/5:
POS

training_data/SCEL4_2_2_1_0_1_1/6:
POS

training_data/SCEL4_2_2_1_0_1_1/7:
POS

training_data/SCEL4_2_2_1_0_1_1/8:
POS

training_data/SCEL4_2_2_1_0_1_1/9:
POS

training_data/SCEL4_4_1_1_0_3_2:
0  1  10  11  12  13  14  15  16  17  18  19  2  20  21  22  23  3  4  5  6  7  8  9  LAT

training_data/SCEL4_4_1_1_0_3_2/0:
POS

training_data/SCEL4_4_1_1_0_3_2/1:
POS

training_data/SCEL4_4_1_1_0_3_2/10:
POS

training_data/SCEL4_4_1_1_0_3_2/11:
POS

training_data/SCEL4_4_1_1_0_3_2/12:
POS

training_data/SCEL4_4_1_1_0_3_2/13:
POS

training_data/SCEL4_4_1_1_0_3_2/14:
POS

training_data/SCEL4_4_1_1_0_3_2/15:
POS

training_data/SCEL4_4_1_1_0_3_2/16:
POS

training_data/SCEL4_4_1_1_0_3_2/17:
POS

training_data/SCEL4_4_1_1_0_3_2/18:
POS

training_data/SCEL4_4_1_1_0_3_2/19:
POS

training_data/SCEL4_4_1_1_0_3_2/2:
POS

training_data/SCEL4_4_1_1_0_3_2/20:
POS

training_data/SCEL4_4_1_1_0_3_2/21:
POS

training_data/SCEL4_4_1_1_0_3_2/22:
POS

training_data/SCEL4_4_1_1_0_3_2/23:
POS

training_data/SCEL4_4_1_1_0_3_2/3:
POS

training_data/SCEL4_4_1_1_0_3_2/4:
POS

training_data/SCEL4_4_1_1_0_3_2/5:
POS

training_data/SCEL4_4_1_1_0_3_2/6:
POS

training_data/SCEL4_4_1_1_0_3_2/7:
POS

training_data/SCEL4_4_1_1_0_3_2/8:
POS

training_data/SCEL4_4_1_1_0_3_2/9:
POS

training_data/settings:
calctype.default  O  Zr

training_data/settings/calctype.default:
INCAR  KPOINTS  POSCAR  ref.default  relax.json  SPECIES

training_data/settings/calctype.default/ref.default:

training_data/settings/O:
POTCAR

training_data/settings/Zr:
POTCAR

**Comment by bpuchala** [comment]
This message indicates there is a problem with your SPECIES file:

> Reading SPECIES: /home/anu/Desktop/newcasmtest/training_data/settings/calctype.default/SPECIES
Length of values != length of tags + 4.
values = ['Zr2', 'Zr', '0']
tags = []
