### ISSUE TITLE
Many Monte Carlo runs will cripple a filesystem

### ISSUE THREAD

**Issue by tallakahath** [prisms-center/CASMcode#65]
This is more of a design issue rather than a coding issue.

The current setup of monte carlo involves writing one 'conditions.i' folder, with three .json files inside, for every... well, every condition. For my runs, I'm often doing large temperature spans (>1000 K), small temperature steps (~5K), at many many chemical potentials to capture compositions near a miscibility gap.

While I have the compute power to run, say, >300 runs, doing this will break any compute cluster filesystem (nfs/lustre/etc) I've encountered. This comes from 1. each CASM process creating/touching/manipulating a bunch of (tiny, regardless) files, and 2. creating so many directories/subdirectories that the FS starts to get upset. Operations on a head node even begin to slow down, and the CASM jobs start impacting each other (starting up a new MC run takes approx. forever, as doing disk operations to do things like read monte.json and stuff become O(infinity) in time). 

It seems that the files inside conditions.i are used only for certain post-processing invocations of "casm monte", and we could switch to either 1. having one big json (conditions.json, with an entry for each), or better, 2. some sort of large, compressed file/files or database, like a hdf5 or something. 

Could this be worth considering in future versions of CASM? Has anyone else had this problem? Should I just slow down on my MC runs?

**Comment by bpuchala** [comment]
What I often do is `tar.gz` each Monte Carlo path after it is complete, untar when necessary to read for analysis, and then re-tar / remove. This is manageable, but annoying. 

If you're doing too many in parallel this wouldn't help, but you could do shorter segments along the same path. If you are doing 'dependent_runs' you can still take the 'final_config.json' from one segment and make it the input to the next segment. 

For the next major release of CASM we're working on some database support for enumerated configurations and calculated properties. Not sure if Monte Carlo would be included at that point or a subsequent release, but it is planned also.
