### ISSUE TITLE
How do we get selected clusters? 

### ISSUE THREAD

**Issue by DaehyeonChoi** [prisms-center/CASMcode#66]
Result:
Index:  Selected         #Selected      CV       RMS          wRMS         Estimator              FeatureSelection     Note

0: 1111001000000000100001000000001000000000...  25   0.049666174  0.045981558  0.045981558 LinearRegression RFE

From my training data, I got about 100 clusters by bspecs.json file with 'casm bset -u'
and checked them with 'casm bset --orbits'

Then, I've fitted them for optimizing CVS and RMS and checked them with 'casm-learn -s fit_1_rfe.json --checkhull or --hall', described as above, and I can find 25 clusters are selected as denoted #Selected

but it's quite difficult for me to visualize selected ones, because I couldn't find their coordinate information like what we can see when we type 'casm bset --orbits or --functions'

Also, when writing eci.json file with 'casm-learn -s fit_1_rfe.json --select 0', it didn't work because of length of Index, printing like below

Traceback (most recent call last):
  File "/usr/local/bin/casm-learn", line 101, in <module>
    write_eci(proj, indiv.eci, casm.learn.to_json(index, indiv), verbose=args.verbose)
  File "/GRAPE/Apps/Python/2.7.12_intel_17.0.0/lib/python2.7/site-packages/casm/project/io.py", line 40, in write_eci
    j["cluster_functions"][index]["eci"] = value
IndexError: list index out of range

It will be grateful if anyone could give me some comments on this

Thanks

**Comment by bpuchala** [comment]
You can view more detailed information about a particular solution with one of:
```
casm-learn -s <inputfile> --hall --indiv 0 --format details
```
or
```
casm-learn -s <inputfile> --hall --indiv 0 --format json
```

This will print eci with basis function -> eci value pairs, where the basis function index is the same as printed using `casm bset --functions`.

Alternatively, after selecting a particular solution with `casm-learn -s <inputfile> --select <index>`, an `eci.json` file will be printed that has a list of basis functions with eci.  This also includes a prototype cluster associated with each basis function, using integral indices `[b, i, j, k]`; `b` being the sublattice and `i,j,k` being the unit cell.

The `eci.json` file is just a copy of the `basis_sets/bset.name/basis.json` file generated with `bset -u` with ECI values added.

I'm unclear exactly what is causing the error printing the `eci.json` file, but you will need to make sure that your fit and your current `bset` are consistent. Perhaps you need to re-generate your basis functions with `bset -u -f`. Then use `casm settings -l` to check that you still have the same `bset` and other settings selected as was used to do the fit, or re-do it if necessary (which should be fast and deterministic with `RFE`).

**Comment by DaehyeonChoi** [comment]
Thanks for your kind and clear answer!

It really helps me to identify cluster set
