### ISSUE TITLE
Generation of basis functions

### ISSUE THREAD

**Issue by HojeChun** [prisms-center/CASMcode#68]
**I am using CASM code firstly to verify with simple Pt(111)/O system.
I have generated "bspecs.json" as**
{
  "basis_functions" : {
    "site_basis_functions" : "occupation"
  },
  "orbit_branch_specs" : {
    "2" : {"max_length" : 7.5},
    "3" : {"max_length" : 6.05},
    "4" : {"max_length" : 4.05}
  }
}
. 
**However, with this I've gotten several same clusters as basis shown in the result with this command "casm bset --orbits"**
** Branch 0 ** 
      ** 0 of 27 Orbits **  Orbit: 0 0  Points: 0  Mult: 1  MinLength: 0.00000  MaxLength: 0.00000
            Prototype of 1 Equivalent Clusters in Orbit 0

** Branch 1 ** 
      ** 1 of 27 Orbits **  Orbit: 1 0  Points: 1  Mult: 1  MinLength: 0.00000  MaxLength: 0.00000
            Prototype of 1 Equivalent Clusters in Orbit 1
                                 0.3383469    0.6616530    0.4929045 Va O

** Branch 2 ** 
      ** 2 of 27 Orbits **  Orbit: 2 0  Points: 2  Mult: 1  MinLength: 2.7700000  MaxLength: 2.7700000
            Prototype of 1 Equivalent Clusters in Orbit 2
                                 0.3383469    0.6616530    0.4929045 Va O
                                -0.6616531   -0.3383470    0.4929045 Va O

      ** 3 of 27 Orbits **  Orbit: 2 1  Points: 2  Mult: 2  MinLength: 2.7700000  MaxLength: 2.7700000
            Prototype of 2 Equivalent Clusters in Orbit 3
                                 0.3383469    0.6616530    0.4929045 Va O
                                 0.3383469   -0.3383470    0.4929045 Va O

      ** 4 of 27 Orbits **  Orbit: 2 2  Points: 2  Mult: 1  MinLength: 4.7977807  MaxLength: 4.7977807
            Prototype of 1 Equivalent Clusters in Orbit 4
                                 0.3383469    0.6616530    0.4929045 Va O
                                 1.3383469   -0.3383470    0.4929045 Va O

      ** 5 of 27 Orbits **  Orbit: 2 3  Points: 2  Mult: 2  MinLength: 4.7977807  MaxLength: 4.7977807
            Prototype of 2 Equivalent Clusters in Orbit 5
                                 0.3383469    0.6616530    0.4929045 Va O
                                -0.6616531   -1.3383470    0.4929045 Va O

      ** 6 of 27 Orbits **  Orbit: 2 4  Points: 2  Mult: 1  MinLength: 5.5400000  MaxLength: 5.5400000
            Prototype of 1 Equivalent Clusters in Orbit 6
                                 0.3383469    0.6616530    0.4929045 Va O
                                -1.6616531   -1.3383470    0.4929045 Va O

      ** 7 of 27 Orbits **  Orbit: 2 5  Points: 2  Mult: 2  MinLength: 5.5400000  MaxLength: 5.5400000
            Prototype of 2 Equivalent Clusters in Orbit 7
                                 0.3383469    0.6616530    0.4929045 Va O
                                 0.3383469   -1.3383470    0.4929045 Va O

      ** 8 of 27 Orbits **  Orbit: 2 6  Points: 2  Mult: 2  MinLength: 7.3287311  MaxLength: 7.3287311
            Prototype of 2 Equivalent Clusters in Orbit 8
                                 0.3383469    0.6616530    0.4929045 Va O
                                -1.6616531   -2.3383470    0.4929045 Va O
**Here, I recognzied 2 and 3 are the same clusters, and also the 4 and 5. This leads in the process of finding eci me obtain the duplicated basis functions having different ECI. The CVS seems reasonalbe with various run around 15 meV. I suspect the issue is with the generating basis function not ECI. Is there a way for me to obtain basis functions without duplications, or is it my mistake of making "bspecs.json"?**

**Comment by jcthomas** [comment]
Could you include a copy of your `prim.json` file? CASM uses a default tolerance of 1e-5 angstroms for determination of symmetry. It looks like your coordinates may be just outside this bounds, which would cause some symmetries of the crystal to be missed. You can increase this tolerance by editing the `"crystallography_tol"` field in `$PROJECTHOME/.casm/project_settings.json`. 

Alternatively, you can edit `prim.json` to increase the symmetry and precision of your lattice vectors coordinates. Where appropriate, you may want to specify fractional coordinates as being at least 6 decimal digits of rational numbers, like n/3 o n/6. Hexagonal/trigonal lattice vectors should be specified in such a way that irrational numbers are carried to at least 6 decimal digits. For example, if your 'a' lattice vector is
**avec**=(_a_, 0, 0)
then you should set
**bvec**=(_a_/2, _a_*sqrt(3)/2, 0)
assuming the conventional setting, with the 'c' vector normal to the basal plane:
**cvec**=(0, 0, _c_) 

 Note that editing `prim.json` will affect the coordinates of any future calculation files that are created (e.g., POSCAR). This may have a small effect on the DFT energy of future training data, depending on your calculation settings.

**Comment by HojeChun** [comment]
**Thank you for your comment! Here is my "prim.json" file.** 
{
  "basis" : [
    {
      "coordinate" : [ 0.0013799449602503, -0.0013794507280650,  0.1108996805825493 ],
      "occupant_dof" : [ "Pt" ]
    },
    {
      "coordinate" : [ 0.0053447645253115, -0.0053451534047611,  0.4325249156658264 ],
      "occupant_dof" : [ "Pt" ]
    },
    {
      "coordinate" : [ 0.3354479056324403,  0.6645526357436290,  0.2193742315266467 ],
      "occupant_dof" : [ "Pt" ]
    },
        {
      "coordinate" : [ 0.6680017420630258,  0.3319980052098507,  0.0006854095394725 ],
      "occupant_dof" : [ "Pt" ]
    },
    {
      "coordinate" : [ 0.6714787717634978,  0.3285209181179816,  0.3280511534624933 ],
      "occupant_dof" : [ "Pt" ]
    },
    {
      "coordinate" : [ 0.3383468710554706,  0.6616530450613691,  0.4929045292230129 ],
      "occupant_dof" : [ "Va", "O" ]
    }
  ],
  "coordinate_mode" : "Fractional",
  "description" : "Pt 111 surface with O ",
  "lattice_vectors" : [
    [  2.7699999809000002,    0.0000000000000000,    0.0000000000000000 ],
    [ -1.3849999904999999,    2.3988903520000000,    0.0000000000000000 ],
    [  0.0000000000000000,    0.0000000000000000,   21.0466995238999992 ]
  ],
  "title" : "Pt_O"
}
**As far as I understand. The second option you gave me is not working because I already set the lattice constant more than 6 decimal digits. Thus I am trying the first option, it says ""crystallography_tol" : 1.000000000000000082e-05". Then do I need to change to lower tolerance like 1.00e-04, and redo all steps from the beginning?
Thanks**

**Comment by jcthomas** [comment]
This `prim.json` is very far from trigonal symmetry, which is what you should expect to find from `casm sym`. The lattice vectors are sufficiently precise, but the coordinates break nearly all symmetries of the crystal. I was able to find the correct symmetry by increasing `crystallography_tol` to 0.1 Angstr., but using such a large tolerance is likely to cause other problems.

I am attaching a symmetrized prim file, `sym_prim.json`, which yields the correct symmetry. Please verify for yourself that this is the correct structure. You may wish to perform a DFT relaxation from these starting coordinates to find a more suitable set of coordinates.  

Best practice is to start over in a new project, and repeat all steps from the beginning. Due to the higher symmetry, you will enumerate fewer unique configurations and fewer unique clusters and basis functions.  If you are confident in the validity your previous calculations, you can import these data using `casm import`.

**Comment by jcthomas** [comment]
[sym_prim.json.txt](https://github.com/prisms-center/CASMcode/files/1208356/sym_prim.json.txt)
Here is the file.

**Comment by HojeChun** [comment]
Thanks a lot.
I will try in the way you recommend. Also let you know if any porblem occurs
Thanks again!
