### ISSUE TITLE
ERROR: The structure in the prim.json file is not the niggli cell

### ISSUE THREAD

**Issue by Anu-Maria** [prisms-center/CASMcode#69]
When I  give the command _casm init_ I am getting the error

ERROR: The structure in the prim.json file is not the niggli cell in the CASM standard
       orientation. Writing the suggested structure to 'prim.niggli.json'.

       If you want to use the current prim.json anyway, re-run with the --force option.
When I give the command _casm init --force_ I am getting the following message 

**WARNING: The structure in the prim.json file is not the standard orientation Niggli
         cell. Continuing anyway because the --force option is on.

Initializing CASM project 'LiCoO2'
                                                                                  DONE****                                    

How can I make the Niggli cell for my input?

If I proceed with casm init --force, how does it affect the formation energy?

It will be grateful if anyone could give me some comments on this

Thanks

**Comment by skk74** [comment]
To make the niggli cell your input simply copy prim.niggli.json as prim.json and run `casm init` again. If you run with casm init --force, the effect on the formation energies will be for normalization factors if your initial "prim" was for example 8 atoms instead of 4. Also, certain CASM functionalities regarding symmetry routines for advanced usage depend on the prim.json being in the CASM standard it may be difficult to use some of these routines.

**Comment by jcthomas** [comment]
The Niggli cell and standard orientation are just suggestions. There should be no difference in results if you choose to use a different definition of the primitive cell (as long as it is actually primitive, as @skk74 mentioned). When CASM generates training data, it writes files using the Niggli cell, regardless of your choice.  This means that, if you do not use the CASM-suggested structure, the volume-1 supercell, `SCEL1_1_1_1_0_0_0`, will have different lattice vectors than the `prim.json`.

To clarify what @skk74 said, the choice of primitive cell will not affect the calculated symmetry of your system, and it is mostly a matter of convenience.

**Comment by Anu-Maria** [comment]
Thank you very much. That was really helpful.
