### ISSUE TITLE
'fit_1_ga_halloffame.pkl' is not Generating

### ISSUE THREAD

**Issue by Anu-Maria** [prisms-center/CASMcode#70]
When I give the command 'casm-learn -s fit_1_ga.json' I am getting the following error

TypeError: bad operand type for unary -: 'str'

And not generating 'fit_1_ga_halloffame.pkl' 

It will be grateful for any help.
Thanks

**Comment by skk74** [comment]
I apologize for the long wait for the response, but unfortunately I don't think we have enough information to answer your question. Could you provide us with the contents of your fit_1_ga.json if this is still an issue for you?

**Comment by Anu-Maria** [comment]
Thank you for your response. I could come out of it.
