### ISSUE TITLE
Traing within a selected range of composition & energy convex hull

### ISSUE THREAD

**Issue by HojeChun** [prisms-center/CASMcode#84]
****Dear. CASMcode develpers

**Hi, I am one of the CASM code users. Thanks a lot for your contributions and kind answers to the questions.

I have an issue with generating eci within selected composition range and questions about drawing energy convex hull.

Q 1. I have generated and calculated all the configurations from 0 to 1 coverage of the surface system. 
Then I wanted to train and obtain eci from 0 to 0.5 coverage because the adosrption of the adsorbate exceeded the monolayer becoming di-, tri-layers. So, I would like to consider only upto 0.5 coverage, using data from 0 to 0.5 coverage only, even for the energy convex hull.**** 
**Thus I change the reference from 0 to 0.5 and revised the train file in the cluster expansion folder as this****
            configname    selected
    SCEL1_1_1_1_0_0_0/0           1
    SCEL1_1_1_1_0_0_0/1           0
    SCEL2_1_2_1_0_0_0/0           1
    SCEL3_1_3_1_0_0_0/0           1
    SCEL3_1_3_1_0_0_0/1           0
    SCEL3_3_1_1_0_0_2/0           1
    SCEL3_3_1_1_0_0_2/1           0
    SCEL4_1_4_1_0_0_0/0           1
    SCEL4_1_4_1_0_0_0/1           1
    SCEL4_1_4_1_0_0_0/2           0
    SCEL4_2_2_1_0_0_0/0           1
    SCEL4_2_2_1_0_0_0/1           0
    SCEL4_4_1_1_0_0_2/0           1
    SCEL4_4_1_1_0_0_2/1           1
    SCEL4_4_1_1_0_0_2/2           0
    SCEL5_1_5_1_0_0_0/0           1
    SCEL5_1_5_1_0_0_0/1           1
    SCEL5_1_5_1_0_0_0/2           1
    SCEL5_1_5_1_0_0_0/3           0
    SCEL5_1_5_1_0_0_0/4           0
    SCEL5_1_5_1_0_0_0/5           0
    SCEL5_5_1_1_0_0_4/0           1
    SCEL5_5_1_1_0_0_4/1           1
    SCEL5_5_1_1_0_0_4/2           1
    SCEL5_5_1_1_0_0_4/3           0
    SCEL5_5_1_1_0_0_4/4           0
    SCEL5_5_1_1_0_0_4/5           0
## **Then, I ran cluster expansion with defaulted exGeneticAlgorithm like this**
{
  "estimator": {
    "method": "LinearRegression"
  }, 
  "feature_selection": {
    "method": "GeneticAlgorithm", 
    "kwargs": {
      "constraints_kwargs": {
        "fix_on": [], 
        "n_features_min": 5, 
        "fix_off": [], 
        "n_features_max": "all"
      }, 
      "cxUniformProb": 0.5, 
      "mutFlipBitProb": 0.01, 
      "evolve_params_kwargs": {
        "n_population": 100, 
        "n_generation": 10, 
        "n_repetition": 25, 
        "n_halloffame": 50, 
        "n_features_init": 5
      }, 
      "selTournamentSize": 3
    }
  }, 
  "problem_specs": {
    "data": {
      "y": "formation_energy", 
      "X": "corr", 
      "kwargs": null, 
      "type": "selection", 
      "filename": "train"
    }, 
    "cv": {
      "penalty": 0.0, 
      "method": "KFold", 
      "kwargs": {
        "n_folds": 10, 
        "shuffle": true
      }
    }, 
    "weight": {
      "method": "wHullDist", 
      "kwargs": {
        "A": 0.0, 
        "B": 1.0, 
        "kT": 0.01
      }
    }
  }, 
  "n_halloffame": 25
}
## **However, it seems that I obtain the data considering the configurations above 0.5 as well because I have gotten the results as this,**
-- Load project data -- 
refresh cluster expansions

DFT ground states:
configname  comp(a)  dft_hull_dist  formation_energy  clex_hull_dist  clex(formation_energy)  clex_dft_hull_dist
SCEL1_1_1_1_0_0_0/0     0.00            0.0          0.000000             0.0                0.000000                 0.0
SCEL4_2_2_1_0_0_0/0     0.25            0.0         -0.111245             0.0               -0.100561                 0.0
SCEL5_5_1_1_0_0_4/1     0.40            0.0         -0.109739             0.0               -0.138664                 0.0
SCEL5_5_1_1_0_0_4/5     0.80            0.0          0.315227             0.0                2.660849                 0.0
SCEL1_1_1_1_0_0_0/1     1.00            0.0          2.053564             0.0                7.434595                 0.0

Predicted ground states:
configname   comp(a) dft_hull_dist formation_energy  clex_hull_dist  clex(formation_energy)  clex_dft_hull_dist
SCEL1_1_1_1_0_0_0/0  0.000000    0.00000000       0.00000000             0.0                0.000000            0.000000
SCEL4_2_2_1_0_0_0/0  0.250000    0.00000000      -0.11124485             0.0               -0.100561            0.000000
SCEL5_5_1_1_0_0_4/1  0.400000    0.00000000      -0.10973938             0.0               -0.138664            0.000000
SCEL4_4_1_1_0_0_2/1  0.500000    0.00063598       0.00000000             0.0               -0.000534           -0.102136
SCEL3_3_1_1_0_0_2/1  0.666667    0.04207150       0.41197640             0.0                0.527661           -0.211768
SCEL5_5_1_1_0_0_4/5  0.800000    0.00000000       0.31522652             0.0                2.660849            0.000000
SCEL1_1_1_1_0_0_0/1  1.000000    0.00000000       2.05356353             0.0                7.434595            0.000000

Predicted ground states that are not DFT ground states:
configname   comp(a)  dft_hull_dist  formation_energy  clex_hull_dist  clex(formation_energy)  clex_dft_hull_dist
SCEL4_4_1_1_0_0_2/1  0.500000       0.000636          0.000000             0.0               -0.000534           -0.102136
SCEL3_3_1_1_0_0_2/1  0.666667       0.042071          0.411976             0.0                0.527661           -0.211768

All configurations predicted below the prediction of the DFT hull:
configname   comp(a) dft_hull_dist formation_energy  clex_hull_dist  clex(formation_energy)  clex_dft_hull_dist
SCEL4_4_1_1_0_0_2/1  0.500000    0.00063598       0.00000000        0.000000               -0.000534           -0.102136
SCEL4_1_4_1_0_0_0/1  0.500000    0.06422851       0.34975892        0.058936                0.323613           -0.043200
SCEL2_1_2_1_0_0_0/0  0.500000    0.08993289       0.49113299        0.076034                0.417651           -0.026102
SCEL5_5_1_1_0_0_4/4  0.600000       unknown          unknown        0.040325                0.542201           -0.128374
SCEL5_1_5_1_0_0_0/4  0.600000    0.01807386       0.20395721        0.052817                0.612157           -0.115881
SCEL5_5_1_1_0_0_4/3  0.600000    0.02151865       0.22324800        0.008852                0.365953           -0.159846
SCEL3_3_1_1_0_0_2/1  0.666667    0.04207150       0.41197640        0.000000                0.527661           -0.211768
SCEL3_1_3_1_0_0_0/1  0.666667    0.02550917       0.31812317        0.037794                0.741827           -0.173974
SCEL4_4_1_1_0_0_2/2  0.750000    0.01910166       0.37194031        0.025569                2.007924           -0.052693

ranged_rms:
  RMS error for 8 calculated configurations within 0.001 eV/unitcell of the DFT hull: 2.07596495484
  RMS error for 8 calculated configurations within 0.005 eV/unitcell of the DFT hull: 2.07596495484
  RMS error for 8 calculated configurations within 0.01 eV/unitcell of the DFT hull: 2.07596495484
  RMS error for 20 calculated configurations within 0.05 eV/unitcell of the DFT hull: 1.57904255261
  RMS error for 24 calculated configurations within 0.1 eV/unitcell of the DFT hull: 1.44174279
  RMS error for 25 calculated configurations within 0.5 eV/unitcell of the DFT hull: 1.44820441777
  RMS error for 25 calculated configurations within all eV/unitcell of the DFT hull: 0.0634905077885

## **This seems to me that code runs through all coverage configurations. In which part should I change the settings to do the cluster expansion with a ceratin range of coverage?**
**These are minor technical problems which I would be really gratefull if you answer.
Q2. Is there a way to obtain energy convex hull data points within the code? 
Q3. How do I use/treat/excess the output files of cluster expansion such as fit_1_ga_population_end.pkl, fit_1_ga_evolve_halloffame.pkl and etc..?**
**Thank you so much for reading this and help again**

**Comment by skk74** [comment]
A1. So your cluster expansion is only being trained on those selected in the file "train". The output from checkhull is an analysis output. As of now you are doing the analysis on ALL of your configurations. If you would like the checkhull output to only do the analysis on the converage < 0.5 configurations, you can add a field in the fit_1_ga.json called "checkhull" and specify a selection file to do the analysis on. see casm-learn --settings-format for details. 

A2. Yes there is a way to get the data required to make convex hull plots. `casm query` is a casm command that can give you information about certain configurations (see `casm query -h` for details). running `casm query -h properties` will show all the options that are available. for example, if I want the data for a convex hull plot I might do the following:
`casm select --set 'le(comp,0.5)'`
`casm query -k  comp formation_energy`
and then plot the appropriate columns.

A3. Unfortunately, .pkl files are not human readable. If you want to see the hall of fame again you can always run `casm-learn -s fit_1_ga.json --hall` if you want to see the basis functions that were selected in a given fit you will have to load it and view the respective eci.json file for details.
