### ISSUE TITLE
'casm status -n' dialog errors and SCons issues

### ISSUE THREAD

**Issue by flwalsh** [prisms-center/CASMcode#88]
I recently installed CASM and noticed several outdated commands in the instructions provided by the `casm status -n` dialog.

For instance, in the "Enumerate supercells" step, 
`casm enum --supercells --max V`
should be
`casm enum --method ScelEnum --max V`

Likewise, `casm enum --configs --all` needs to be `casm enum --method ConfigEnumAllOccupations` and similarly for `casm enum --configs --scellname NAME`.

Then in the "Calculate configuration properties" step, `casm select --set on` should be `casm select --set-on`. These are all the ones I've encountered, but there may be others.

Also to be noted:

I was unable to successfully build with SCons on Ubuntu 16.04, which was plagued with environmental variable issues pertaining to boost. If I used a manual install of boost, `scons configure` would pass, but it still broke on build. With an apt-get install, I couldn't get the environmental variables configured properly to pass the configure stage. Instead, automake proved successful and relatively painless (thanks @goirijo).

**Comment by skk74** [comment]
Thanks for pointing this out flynn. I've made appropriate changes and added them to the pull request regarding the double printing of atoms in the POSCAR #87.

**Comment by bpuchala** [comment]
Thanks for the notes @flynnbw and modifications @skk74. I've merged the changes into the development branch.  We're working on improving the build and distribution.
