### ISSUE TITLE
Occupation variables & how to relate them to the clusters

### ISSUE THREAD

**Issue by DaehyeonChoi** [prisms-center/CASMcode#91]
Dear CASM developers

I think I'm almost done with my research and thanks for your ongoing help.

Here is the thing I'm not sure about. I would appreciate your kind advice.

1. with casm bset --function, I've got the below result.
Asymmetric unit 1:
  Basis site 0:
                 0.0000000    0.0000000    0.0000000 A B
        \phi_0_0[A] = -0.0000000,       \phi_0_0[B] = 1.0000000
Asymmetric unit 2:
  Basis site 1:
                 0.5000000    0.5000000    0.5000000 C
        [No site basis functions]

According to this result, I can figure out we have occupation variables, 0 for A metal and 1 for B metal.
The previous reports, such as A. Van der Ven et. al, PRB 58 (1998) 2975 and Electrochimica Acta 45 (1999) 131, used +1, -1 for occupation variables in binary cluster expansions. I'm wondering why CASM code uses 0, 1 for occupation variables as default. Is there any special reason for choosing different variables from previous reports?

2. According to the previous reports as I mentioned above, ECI values range from -10 to 50 meV. I know ECI are just the constant expansion coefficients. My ECI values range from -0.8 to 0.6 eV, 18 clusters. And they converge well to zero as the number of sites or the distance between the sites in the cluster increases. So they look fine but It's been on my mind when comparing with the previous reports because of scale. I guess that occupation variables [(0, 1), not (-1, 1)] could be the reason for this situation.

Please let me know whether it is not a big deal.

Thanks

**Comment by jcthomas** [comment]
To answer your first question, the site basis functions are constructed based on the settings in 'bspecs.json'. The occupation (i.e., [0,1]) convention is used when the following field is provided:
````
  "basis_functions" : {
    "site_basis_functions" : "occupation"
  }
````
The spin, or Chebychev, convention (i.e., [-1,1]) is used when the following field is provided:
````
  "basis_functions" : {
    "site_basis_functions" : "chebychev"
  }
````

You can read more about available options by running `casm format --bspecs`.

To answer your second question, the ECI will depend on whether you use the [0,1] or [-1,1] convention (or a different convention altogether). The source of this difference is described nicely in this paper: https://doi.org/10.1103/PhysRevB.44.4914 However, I'm not sure that the difference would be an order of magnitude, as you are observing. 

Another important factor that affects the ECI of the 1-site clusters (but *not* 2-site, 3-site, etc.) is the choice of chemical references for calculating formation energy (which are specified using the `casm ref` command). The 1-site ECIs can be related to the chemical potentials of your chosen reference compounds. In particular, if you don't select chemical references at all (or set reference compounds having zero energy), the 1-site ECIs can be very large.
