### ISSUE TITLE
scons: *** [src/casm/clex/Supercell.os] Error 1

### ISSUE THREAD

**Issue by Yangxinsix** [prisms-center/CASMcode#96]
Hello, thank you for your code.

I believe this could help me a lot, though till now I can't even install it  both on my personal computer and supercomputer. 

My dependencies:

(1) gcc version 5.4.0 (GCC)
(2) SCons 2.5.1
(3) boost 1.62.0

First, when I tried to install the code on the supercomputer:
` Reading SConscript files ...
Checking for c++11... no
Configuration checks failed.
C++11 is required. Please check your compiler.
`
It can not find the c++11 compiler.

And then I transferred to my personal computer with ubuntu 17.04, gcc version 6.3.0, SCons 2.5.1 and boost 1.66.0. Although I set the environment of the path of boost before the installation, it warned me like this:

`scons:Reading SConscript files ...
Checking for c++11... yes
Checking for C library z... yes
Checking for C library dl... yes
Checking for C library dl... yes
BOOST_PREFIX: ~/local/boost
(cached) Checking for boost headers... (cached) no
Configuration checks failed.
Please check your boost installation or the CASM_BOOST_PREFIX environment variable
`

Boost lib could not be linked properly.

And finally I added `boost_prefix=path` after `scons configure`, the configure worked. But `scons` failed again with:

`include/casm/clex/ParamComposition.hh:79:55:   required from here
include/casm/external/Eigen/src/Core/DenseCoeffsBase.h:56:30: warning: ignoring attributes on template argument 'Eigen::internal::packet_traits<double>::type {aka __vector(2) double}' [-Wignored-attributes]
cc1plus: warning: unrecognized command line option '-Wno-deprecated-register'
scons: *** [src/casm/clex/Supercell.os] Error 1
`

Since the administer of supercomputer said they could not install a higher version of gcc on it, is there any idea for me 1) to compile this code with gcc 5.4.0; 2) to `scons` successfully.

Thanks for your reply!

Regards,

Yangxinsix

**Comment by bpuchala** [comment]
Hi Yangxinsix,

Thank you for your interest in CASM. What I've had success doing previously is taking a users dependencies and making a Dockerfile that successfully builds a CASM container, not for actually running CASM as much as a recipe that can be followed to install CASM on the system of interest. I can make one for:

- ubuntu 17.04, gcc version 6.3.0, SCons 2.5.1 and boost 1.66.0

what is the operating system for your other system?

- os?, gcc version 5.4.0 (GCC), SCons 2.5.1, boost 1.62.0

**Comment by bpuchala** [comment]
I've updated the scons build to make it easier to set compile and link flags from the command line. Here is an example Dockerfile for building (ubuntu 17.04, gcc version 6.3.0, SCons 2.5.1 and boost 1.66.0) the development branch 0.2.X with scons. And below gives the autotools build option. We are transitioning to autotools, but it's just not really documented yet.

Scons:
```
FROM ubuntu:17.04

# Build with: docker build . -t username:casm_0.2.X
# Use with: docker run -v $HOSTDIR:$CONTAINERDIR --rm -it username:casm_0.2.X
# where $HOSTDIR is a directory from your machine and $CONTAINERDIR is where you
# want to find it in your container,
#   typically something like "/path/to/MyProject:/root/MyProject"

LABEL description="ubuntu 17.04 test environment"

RUN apt-get update \
  && apt-get install -y \
  gcc-6 \
  g++-6 \
  automake \
  autoconf \
  autoconf-archive \
  libtool \
  pkg-config \
  make \
  zlib1g-dev \
  binutils-dev \
  curl \
  bzip2 \
  wget \
  git \
  bash-completion \
  python \
  scons

# Compile CASM required boost libraries with default g++, c++11
# Install boost in '/usr/local';
#   Change --prefix option to install elsewhere
RUN cd /root \
  && wget https://dl.bintray.com/boostorg/beta/1.66.0.beta.1/source/boost_1_66_0_b1.tar.bz2 \
  && tar -xf boost_1_66_0_b1.tar.bz2 \
  && cd boost_1_66_0 \
  && ./bootstrap.sh \
    --prefix=/usr/local \
    --with-libraries=system,filesystem,program_options,regex,chrono,timer,test \
  && ./b2 cxxflags="-std=c++11 -O3" \
  && ./b2 install

RUN cd /root \
  && wget https://bootstrap.pypa.io/get-pip.py \
  && python get-pip.py \
  && pip install \
    bokeh==0.12.3 \
    deap \
    mock \
    pandas \
    scikit-learn==0.19 \
    scipy==0.19 \
    tornado==4.3

# Install 'pbs' Python package for automating job submission on a cluster
# installs in /usr/local; set 'BIN' and 'PYINSTALL' to customize install location
# see https://github.com/prisms-center/pbs
RUN cd /root \
  && git clone https://github.com/prisms-center/pbs.git \
  && cd pbs \
  && git checkout v2.0.0 \
  && make install

# Set environment variables to find boost in '/usr/local'
ENV CASM_BOOST_PREFIX=/usr/local

# Checkout development CASM 0.2.X (90dfbdc3a3590b45d314a678e1e091ad37cfc916)
RUN cd /root \
  && git clone https://github.com/prisms-center/CASMcode.git \
  && cd CASMcode \
  && git checkout 0.2.X \
  && CXXFLAGS="-Wno-ignored-attributes -Wno-deprecated-declarations" \
  && LDFLAGS="-Wl,--no-as-needed" \
  && scons configure cxxflags="$CXXFLAGS" ldflags="$LDFLAGS" \
  && scons cxxflags="$CXXFLAGS" ldflags="$LDFLAGS" \
  && scons install cxxflags="$CXXFLAGS" ldflags="$LDFLAGS"

WORKDIR /root

CMD ["/bin/bash"]

```

For autotools, just replace the last RUN command with:
```
# Checkout development CASM 0.2.X (90dfbdc3a3590b45d314a678e1e091ad37cfc916)
RUN cd /root \
  && git clone https://github.com/prisms-center/CASMcode.git \
  && cd CASMcode \
  && git checkout 0.2.X \
  && ./bootstrap.sh \
  && ./configure CXXFLAGS="-O3 -DNDEBUG -Wno-ignored-attributes -Wno-deprecated-declarations" --with-bash-completion-dir=$BASH_COMPLETION_DIR \
  && make -j 2 \
  && make install
```

**Comment by Yangxinsix** [comment]
Thanks for your kindly help! The operating system for the supercomputer was attached below. Since I have never tried Docker before, it may take a while for me to figure this out...

Again I was really appreciated. Thanks!

LSB  Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.5 (Santiago)
Release:	6.5
Codename:	Santiago

**Comment by Yangxinsix** [comment]
`#0  0x00002b7c33064340 in CASM::ParamComposition::calc_composition_object(Eigen::Matrix<double, -1, 1, 0, -1, 1> const&, CASM::Array<Eigen::Matrix<double, -1, 1, 0, -1, 1> >) ()`
   `from /THL6/home/lijia_nano/local/casm/bin/../lib/libcasm.so`
