### ISSUE TITLE
Build problems: Implicit dependency `lib/None' not found, needed by target `lib/libcasm.so'.

### ISSUE THREAD

**Issue by ajjackson** [prisms-center/CASMcode#99]
I am getting this interesting error when trying to build CASM from the git master branch (f83893d).
_Edit: this seems to be the wrong hash, the current "master" commit is e413032._

`scons configure` runs ok once I provide a CASM_BOOST_PREFIX to a user installation of Boost. The only missing dependency at this stage is the Python pbs package. My scons version is v2.3.0, from the Linux Mint package manager. `scons` then fails after a good amount of successful building with
```
scons: *** [lib/libcasm.so] Implicit dependency `lib/None' not found, needed by target `lib/libcasm.so'.
scons: building terminated because of errors.
```
Has anyone seen this before?

**Comment by bpuchala** [comment]
I believe this is fixed in the development branch, 0.2.X.  In another issue (#96) I've added example Dockerfiles that can be used to build and install CASM as an example to follow on other systems.

**Comment by ajjackson** [comment]
It does seem to be fixed in the development branch. I switched to the head of the 0.2.X branch (f83893d). After cleaning and building a couple of times, I was able to build with `scons` without this error appearing. I also found that my boost lib needs to be added to LD_LIBRARY_PATH in order to build the tests, regardless of whether CASM_BOOST_PREFIX is set.

**Comment by ajjackson** [comment]
I've tried to rebuild casm while troubleshooting something else and this problem has come back! No amount of cleaning and rebuilding is working now. I tried the docker file and that does seem to build ok after changing the Ubuntu version to 17.10.

I noticed from the docker build you mentioned that CASM is moving towards autotools, so gave that a try. After bootstrapping, `./configure --prefix=${HOME}/opt/casm` gives me
```
checking for dlerror... yes
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dld_link in -ldld... no
./configure: line 16023: AX_CXX_COMPILE_STDCXX_11: command not found
./configure: line 16025: syntax error near unexpected token `$BOOSTV,,as_fn_error'
./configure: line 16025: `AX_BOOST_BASE($BOOSTV,,as_fn_error $? "You need Boost $BOOSTV libraries or higher." "$LINENO" 5)'
```
How can I specify the location of Boost for installation with autotools? In the Docker example you sudo installed from source to a system-level directory but that's undesirable for a production system and I keep my Boost build in _~/opt_. (I don't want to have conflicts with the older version of Boost installed by the package manager.)

**Comment by skk74** [comment]
This particular issue with your configuration step is related to the absence of certain autoconf m4 macros that are missing with the boost installation that you are attempting to use. @goirijo can explain the specifics but if you look for an autoconf archive at http://mirror.team-cymru.com/gnu/autoconf-archive/ 
And unpack it in your build/m4 directory, then the configure output might give more helpful output. Also I believe if $BOOST_ROOT is set then autotools will be able to find boost. $BOOST_ROOT is typically set automatically when loading the boost module on whatever cluster you may be operating on.

**Comment by bpuchala** [comment]
I think I've found all the missing m4 files for version 0.3.X.  You could copy them from here: https://github.com/bpuchala/CASMcode/tree/0.3.X/build-aux/m4 into the same directory in your version.

**Comment by ajjackson** [comment]
Thanks. I have rebuilt Boost following the Dockerfile recipe. After copying the m4 files to _build-aux/m4_ the bootstrap -> configure process seems to work but `make` eventually fails with 

```
./.libs/libcasm.so: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
make[1]: *** [casm] Error 1
```

I'm not sure that BOOST_ROOT is being honoured; there are lots of `-l` link commands to bits of boost but no `-L` to help find them or `-I` for the include file.

Build commands:
```
> BOOST_ROOT=${HOME}/opt/boost ./configure --prefix=${HOME}/opt/casm CXXFLAGS="-O3 -DNDEBUG -Wno-ignored-attributes -Wno-deprecated-declarations" --with-bash-completion-dir=${HOME}/opt/casm/bash-completion

> BOOST_ROOT=${HOME}/opt/boost make -j 4
```

**Comment by bpuchala** [comment]
I don't know that BOOST_ROOT is checked. I usually configure with:```--with-boost=$BOOST_ROOT```.  See for example: https://github.com/bpuchala/CASMcode/blob/0.3.X/build_scripts/install-casm.sh

**Comment by ajjackson** [comment]
That seems to have done it. `./configure --with-boost=...` is what I needed. Many thanks!
